package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiArea generated by hbm2java
 */
@Entity
@Table(name="TDI_AREA"
    ,schema="ESQ_SIEC"
)
public class TdiArea  implements java.io.Serializable {


     private BigDecimal arId;
     private String arNombre;
     private char arVigente;
     private Date arFechaCreacion;
     private Date arFechaActualizacion;
     private BigDecimal arEquiIdNsga;
     private String arNombreEtiqueta;
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);
     private Set<TdiDepartamento> tdiDepartamentos = new HashSet<TdiDepartamento>(0);
     private Set<TheActividadesEvaAvance> theActividadesEvaAvances = new HashSet<TheActividadesEvaAvance>(0);

    public TdiArea() {
    }

	
    public TdiArea(BigDecimal arId, String arNombre, char arVigente, Date arFechaCreacion) {
        this.arId = arId;
        this.arNombre = arNombre;
        this.arVigente = arVigente;
        this.arFechaCreacion = arFechaCreacion;
    }
    public TdiArea(BigDecimal arId, String arNombre, char arVigente, Date arFechaCreacion, Date arFechaActualizacion, BigDecimal arEquiIdNsga, String arNombreEtiqueta, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets, Set<TdiDepartamento> tdiDepartamentos, Set<TheActividadesEvaAvance> theActividadesEvaAvances) {
       this.arId = arId;
       this.arNombre = arNombre;
       this.arVigente = arVigente;
       this.arFechaCreacion = arFechaCreacion;
       this.arFechaActualizacion = arFechaActualizacion;
       this.arEquiIdNsga = arEquiIdNsga;
       this.arNombreEtiqueta = arNombreEtiqueta;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
       this.tdiDepartamentos = tdiDepartamentos;
       this.theActividadesEvaAvances = theActividadesEvaAvances;
    }
   
     @Id 

    
    @Column(name="AR_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getArId() {
        return this.arId;
    }
    
    public void setArId(BigDecimal arId) {
        this.arId = arId;
    }

    
    @Column(name="AR_NOMBRE", nullable=false, length=50)
    public String getArNombre() {
        return this.arNombre;
    }
    
    public void setArNombre(String arNombre) {
        this.arNombre = arNombre;
    }

    
    @Column(name="AR_VIGENTE", nullable=false, length=1)
    public char getArVigente() {
        return this.arVigente;
    }
    
    public void setArVigente(char arVigente) {
        this.arVigente = arVigente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AR_FECHA_CREACION", nullable=false, length=7)
    public Date getArFechaCreacion() {
        return this.arFechaCreacion;
    }
    
    public void setArFechaCreacion(Date arFechaCreacion) {
        this.arFechaCreacion = arFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AR_FECHA_ACTUALIZACION", length=7)
    public Date getArFechaActualizacion() {
        return this.arFechaActualizacion;
    }
    
    public void setArFechaActualizacion(Date arFechaActualizacion) {
        this.arFechaActualizacion = arFechaActualizacion;
    }

    
    @Column(name="AR_EQUI_ID_NSGA", precision=22, scale=0)
    public BigDecimal getArEquiIdNsga() {
        return this.arEquiIdNsga;
    }
    
    public void setArEquiIdNsga(BigDecimal arEquiIdNsga) {
        this.arEquiIdNsga = arEquiIdNsga;
    }

    
    @Column(name="AR_NOMBRE_ETIQUETA", length=50)
    public String getArNombreEtiqueta() {
        return this.arNombreEtiqueta;
    }
    
    public void setArNombreEtiqueta(String arNombreEtiqueta) {
        this.arNombreEtiqueta = arNombreEtiqueta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiArea")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiArea")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiArea")
    public Set<TdiDepartamento> getTdiDepartamentos() {
        return this.tdiDepartamentos;
    }
    
    public void setTdiDepartamentos(Set<TdiDepartamento> tdiDepartamentos) {
        this.tdiDepartamentos = tdiDepartamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiArea")
    public Set<TheActividadesEvaAvance> getTheActividadesEvaAvances() {
        return this.theActividadesEvaAvances;
    }
    
    public void setTheActividadesEvaAvances(Set<TheActividadesEvaAvance> theActividadesEvaAvances) {
        this.theActividadesEvaAvances = theActividadesEvaAvances;
    }




}


