package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiCriteriosEvaluacion generated by hbm2java
 */
@Entity
@Table(name="TDI_CRITERIOS_EVALUACION"
    ,schema="ESQ_SIEC"
)
public class TdiCriteriosEvaluacion  implements java.io.Serializable {


     private BigDecimal cvId;
     private TdiGlosario tdiGlosario;
     private String cvCodigo;
     private String cvNombre;
     private Date cvFechaInicioVigencia;
     private Date cvFechaFinVigencia;
     private String cvVigente;
     private String usuarioApexCrea;
     private String usuarioApexUltAct;
     private Date cvFechaCreacion;
     private Date cvFechaUltAct;
     private String cvNumeracion;
     private Set<TdiIndicador> tdiIndicadors = new HashSet<TdiIndicador>(0);

    public TdiCriteriosEvaluacion() {
    }

	
    public TdiCriteriosEvaluacion(BigDecimal cvId, TdiGlosario tdiGlosario, String cvCodigo, String cvNombre, Date cvFechaInicioVigencia, String cvVigente) {
        this.cvId = cvId;
        this.tdiGlosario = tdiGlosario;
        this.cvCodigo = cvCodigo;
        this.cvNombre = cvNombre;
        this.cvFechaInicioVigencia = cvFechaInicioVigencia;
        this.cvVigente = cvVigente;
    }
    public TdiCriteriosEvaluacion(BigDecimal cvId, TdiGlosario tdiGlosario, String cvCodigo, String cvNombre, Date cvFechaInicioVigencia, Date cvFechaFinVigencia, String cvVigente, String usuarioApexCrea, String usuarioApexUltAct, Date cvFechaCreacion, Date cvFechaUltAct, String cvNumeracion, Set<TdiIndicador> tdiIndicadors) {
       this.cvId = cvId;
       this.tdiGlosario = tdiGlosario;
       this.cvCodigo = cvCodigo;
       this.cvNombre = cvNombre;
       this.cvFechaInicioVigencia = cvFechaInicioVigencia;
       this.cvFechaFinVigencia = cvFechaFinVigencia;
       this.cvVigente = cvVigente;
       this.usuarioApexCrea = usuarioApexCrea;
       this.usuarioApexUltAct = usuarioApexUltAct;
       this.cvFechaCreacion = cvFechaCreacion;
       this.cvFechaUltAct = cvFechaUltAct;
       this.cvNumeracion = cvNumeracion;
       this.tdiIndicadors = tdiIndicadors;
    }
   
     @Id 

    
    @Column(name="CV_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCvId() {
        return this.cvId;
    }
    
    public void setCvId(BigDecimal cvId) {
        this.cvId = cvId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CV_PERTENECE_A", nullable=false)
    public TdiGlosario getTdiGlosario() {
        return this.tdiGlosario;
    }
    
    public void setTdiGlosario(TdiGlosario tdiGlosario) {
        this.tdiGlosario = tdiGlosario;
    }

    
    @Column(name="CV_CODIGO", nullable=false, length=50)
    public String getCvCodigo() {
        return this.cvCodigo;
    }
    
    public void setCvCodigo(String cvCodigo) {
        this.cvCodigo = cvCodigo;
    }

    
    @Column(name="CV_NOMBRE", nullable=false, length=500)
    public String getCvNombre() {
        return this.cvNombre;
    }
    
    public void setCvNombre(String cvNombre) {
        this.cvNombre = cvNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CV_FECHA_INICIO_VIGENCIA", nullable=false, length=7)
    public Date getCvFechaInicioVigencia() {
        return this.cvFechaInicioVigencia;
    }
    
    public void setCvFechaInicioVigencia(Date cvFechaInicioVigencia) {
        this.cvFechaInicioVigencia = cvFechaInicioVigencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CV_FECHA_FIN_VIGENCIA", length=7)
    public Date getCvFechaFinVigencia() {
        return this.cvFechaFinVigencia;
    }
    
    public void setCvFechaFinVigencia(Date cvFechaFinVigencia) {
        this.cvFechaFinVigencia = cvFechaFinVigencia;
    }

    
    @Column(name="CV_VIGENTE", nullable=false, length=1)
    public String getCvVigente() {
        return this.cvVigente;
    }
    
    public void setCvVigente(String cvVigente) {
        this.cvVigente = cvVigente;
    }

    
    @Column(name="USUARIO_APEX_CREA", length=50)
    public String getUsuarioApexCrea() {
        return this.usuarioApexCrea;
    }
    
    public void setUsuarioApexCrea(String usuarioApexCrea) {
        this.usuarioApexCrea = usuarioApexCrea;
    }

    
    @Column(name="USUARIO_APEX_ULT_ACT", length=50)
    public String getUsuarioApexUltAct() {
        return this.usuarioApexUltAct;
    }
    
    public void setUsuarioApexUltAct(String usuarioApexUltAct) {
        this.usuarioApexUltAct = usuarioApexUltAct;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CV_FECHA_CREACION", length=7)
    public Date getCvFechaCreacion() {
        return this.cvFechaCreacion;
    }
    
    public void setCvFechaCreacion(Date cvFechaCreacion) {
        this.cvFechaCreacion = cvFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CV_FECHA_ULT_ACT", length=7)
    public Date getCvFechaUltAct() {
        return this.cvFechaUltAct;
    }
    
    public void setCvFechaUltAct(Date cvFechaUltAct) {
        this.cvFechaUltAct = cvFechaUltAct;
    }

    
    @Column(name="CV_NUMERACION", length=30)
    public String getCvNumeracion() {
        return this.cvNumeracion;
    }
    
    public void setCvNumeracion(String cvNumeracion) {
        this.cvNumeracion = cvNumeracion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiCriteriosEvaluacion")
    public Set<TdiIndicador> getTdiIndicadors() {
        return this.tdiIndicadors;
    }
    
    public void setTdiIndicadors(Set<TdiIndicador> tdiIndicadors) {
        this.tdiIndicadors = tdiIndicadors;
    }




}


