package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TdiComponenteEducativo generated by hbm2java
 */
@Entity
@Table(name="TDI_COMPONENTE_EDUCATIVO"
    ,schema="ESQ_SIEC"
)
public class TdiComponenteEducativo  implements java.io.Serializable {


     private BigDecimal ceId;
     private TdiComponenteEducativo tdiComponenteEducativo;
     private TdiSeccionDepartamental tdiSeccionDepartamental;
     private String ceCodigo;
     private String ceNombre;
     private Date ceFechaIniVigencia;
     private Date ceFechaFinVigencia;
     private String ceVigencia;
     private String ceEsIntegrado;
     private BigDecimal ceIdComponentePadre;
     private BigDecimal ceNumeroCreditos;
     private Character ceValidado;
     private BigDecimal ceIdEquivalenciaNsga;
     private String ceCompetencias;
     private String ceObservacionesSecr;
     private String ceCodigoUnificadoUtpl;
     private BigDecimal couId;
     private String ceCodigoUnificadoProcesos;
     private String ceCodigoUnificadoSiec;
     private String ceCodigoUnificadoUtplFinal;
     private String ceCodigoUnicoDistributivo;
     private BigDecimal ceTipoAprobacion;
     private Date ceFechaActualizacion;
     private String ceUsuarioApexCrea;
     private String ceUsuarioApexActualiza;
     private BigDecimal ceIdEquivalenciaEc;
     private Date ceFechaCreacionSiec;
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);
     private Set<TheActividadesEvaAvance> theActividadesEvaAvances = new HashSet<TheActividadesEvaAvance>(0);
     //private TdiComponenteEducativo tdiComponenteEducativo;
     private Set<TdiOfertaNsga> tdiOfertaNsgas = new HashSet<TdiOfertaNsga>(0);
     private Set<TevaMicrovideos> tevaMicrovideoses = new HashSet<TevaMicrovideos>(0);

    public TdiComponenteEducativo() {
    }

	
    public TdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo, TdiSeccionDepartamental tdiSeccionDepartamental, String ceCodigo, String ceNombre, Date ceFechaIniVigencia, String ceVigencia) {
        this.tdiComponenteEducativo = tdiComponenteEducativo;
        this.tdiSeccionDepartamental = tdiSeccionDepartamental;
        this.ceCodigo = ceCodigo;
        this.ceNombre = ceNombre;
        this.ceFechaIniVigencia = ceFechaIniVigencia;
        this.ceVigencia = ceVigencia;
    }
    /*public TdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo, TdiSeccionDepartamental tdiSeccionDepartamental, String ceCodigo, String ceNombre, Date ceFechaIniVigencia, Date ceFechaFinVigencia, String ceVigencia, String ceEsIntegrado, BigDecimal ceIdComponentePadre, BigDecimal ceNumeroCreditos, Character ceValidado, BigDecimal ceIdEquivalenciaNsga, String ceCompetencias, String ceObservacionesSecr, String ceCodigoUnificadoUtpl, BigDecimal couId, String ceCodigoUnificadoProcesos, String ceCodigoUnificadoSiec, String ceCodigoUnificadoUtplFinal, String ceCodigoUnicoDistributivo, BigDecimal ceTipoAprobacion, Date ceFechaActualizacion, String ceUsuarioApexCrea, String ceUsuarioApexActualiza, BigDecimal ceIdEquivalenciaEc, Date ceFechaCreacionSiec, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets, Set<TheActividadesEvaAvance> theActividadesEvaAvances, TdiComponenteEducativo tdiComponenteEducativo, Set<TdiOfertaNsga> tdiOfertaNsgas, Set<TevaMicrovideos> tevaMicrovideoses) {
       this.tdiComponenteEducativo = tdiComponenteEducativo;
       this.tdiSeccionDepartamental = tdiSeccionDepartamental;
       this.ceCodigo = ceCodigo;
       this.ceNombre = ceNombre;
       this.ceFechaIniVigencia = ceFechaIniVigencia;
       this.ceFechaFinVigencia = ceFechaFinVigencia;
       this.ceVigencia = ceVigencia;
       this.ceEsIntegrado = ceEsIntegrado;
       this.ceIdComponentePadre = ceIdComponentePadre;
       this.ceNumeroCreditos = ceNumeroCreditos;
       this.ceValidado = ceValidado;
       this.ceIdEquivalenciaNsga = ceIdEquivalenciaNsga;
       this.ceCompetencias = ceCompetencias;
       this.ceObservacionesSecr = ceObservacionesSecr;
       this.ceCodigoUnificadoUtpl = ceCodigoUnificadoUtpl;
       this.couId = couId;
       this.ceCodigoUnificadoProcesos = ceCodigoUnificadoProcesos;
       this.ceCodigoUnificadoSiec = ceCodigoUnificadoSiec;
       this.ceCodigoUnificadoUtplFinal = ceCodigoUnificadoUtplFinal;
       this.ceCodigoUnicoDistributivo = ceCodigoUnicoDistributivo;
       this.ceTipoAprobacion = ceTipoAprobacion;
       this.ceFechaActualizacion = ceFechaActualizacion;
       this.ceUsuarioApexCrea = ceUsuarioApexCrea;
       this.ceUsuarioApexActualiza = ceUsuarioApexActualiza;
       this.ceIdEquivalenciaEc = ceIdEquivalenciaEc;
       this.ceFechaCreacionSiec = ceFechaCreacionSiec;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
       this.theActividadesEvaAvances = theActividadesEvaAvances;
       this.tdiComponenteEducativo = tdiComponenteEducativo;
       this.tdiOfertaNsgas = tdiOfertaNsgas;
       this.tevaMicrovideoses = tevaMicrovideoses;
    }*/
    
    public TdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo, TdiSeccionDepartamental tdiSeccionDepartamental, String ceCodigo, String ceNombre, Date ceFechaIniVigencia, Date ceFechaFinVigencia, String ceVigencia, String ceEsIntegrado, BigDecimal ceIdComponentePadre, BigDecimal ceNumeroCreditos, Character ceValidado, BigDecimal ceIdEquivalenciaNsga, String ceCompetencias, String ceObservacionesSecr, String ceCodigoUnificadoUtpl, BigDecimal couId, String ceCodigoUnificadoProcesos, String ceCodigoUnificadoSiec, String ceCodigoUnificadoUtplFinal, String ceCodigoUnicoDistributivo, BigDecimal ceTipoAprobacion, Date ceFechaActualizacion, String ceUsuarioApexCrea, String ceUsuarioApexActualiza, BigDecimal ceIdEquivalenciaEc, Date ceFechaCreacionSiec, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets, Set<TheActividadesEvaAvance> theActividadesEvaAvances, Set<TdiOfertaNsga> tdiOfertaNsgas, Set<TevaMicrovideos> tevaMicrovideoses) {
       this.tdiComponenteEducativo = tdiComponenteEducativo;
       this.tdiSeccionDepartamental = tdiSeccionDepartamental;
       this.ceCodigo = ceCodigo;
       this.ceNombre = ceNombre;
       this.ceFechaIniVigencia = ceFechaIniVigencia;
       this.ceFechaFinVigencia = ceFechaFinVigencia;
       this.ceVigencia = ceVigencia;
       this.ceEsIntegrado = ceEsIntegrado;
       this.ceIdComponentePadre = ceIdComponentePadre;
       this.ceNumeroCreditos = ceNumeroCreditos;
       this.ceValidado = ceValidado;
       this.ceIdEquivalenciaNsga = ceIdEquivalenciaNsga;
       this.ceCompetencias = ceCompetencias;
       this.ceObservacionesSecr = ceObservacionesSecr;
       this.ceCodigoUnificadoUtpl = ceCodigoUnificadoUtpl;
       this.couId = couId;
       this.ceCodigoUnificadoProcesos = ceCodigoUnificadoProcesos;
       this.ceCodigoUnificadoSiec = ceCodigoUnificadoSiec;
       this.ceCodigoUnificadoUtplFinal = ceCodigoUnificadoUtplFinal;
       this.ceCodigoUnicoDistributivo = ceCodigoUnicoDistributivo;
       this.ceTipoAprobacion = ceTipoAprobacion;
       this.ceFechaActualizacion = ceFechaActualizacion;
       this.ceUsuarioApexCrea = ceUsuarioApexCrea;
       this.ceUsuarioApexActualiza = ceUsuarioApexActualiza;
       this.ceIdEquivalenciaEc = ceIdEquivalenciaEc;
       this.ceFechaCreacionSiec = ceFechaCreacionSiec;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
       this.theActividadesEvaAvances = theActividadesEvaAvances;
       //this.tdiComponenteEducativo = tdiComponenteEducativo;
       this.tdiOfertaNsgas = tdiOfertaNsgas;
       this.tevaMicrovideoses = tevaMicrovideoses;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="tdiComponenteEducativo"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="CE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCeId() {
        return this.ceId;
    }
    
    public void setCeId(BigDecimal ceId) {
        this.ceId = ceId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public TdiComponenteEducativo getTdiComponenteEducativo() {
        return this.tdiComponenteEducativo;
    }
    
    public void setTdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo) {
        this.tdiComponenteEducativo = tdiComponenteEducativo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SE_ID", nullable=false)
    public TdiSeccionDepartamental getTdiSeccionDepartamental() {
        return this.tdiSeccionDepartamental;
    }
    
    public void setTdiSeccionDepartamental(TdiSeccionDepartamental tdiSeccionDepartamental) {
        this.tdiSeccionDepartamental = tdiSeccionDepartamental;
    }

    
    @Column(name="CE_CODIGO", nullable=false, length=25)
    public String getCeCodigo() {
        return this.ceCodigo;
    }
    
    public void setCeCodigo(String ceCodigo) {
        this.ceCodigo = ceCodigo;
    }

    
    @Column(name="CE_NOMBRE", nullable=false, length=200)
    public String getCeNombre() {
        return this.ceNombre;
    }
    
    public void setCeNombre(String ceNombre) {
        this.ceNombre = ceNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CE_FECHA_INI_VIGENCIA", nullable=false, length=7)
    public Date getCeFechaIniVigencia() {
        return this.ceFechaIniVigencia;
    }
    
    public void setCeFechaIniVigencia(Date ceFechaIniVigencia) {
        this.ceFechaIniVigencia = ceFechaIniVigencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CE_FECHA_FIN_VIGENCIA", length=7)
    public Date getCeFechaFinVigencia() {
        return this.ceFechaFinVigencia;
    }
    
    public void setCeFechaFinVigencia(Date ceFechaFinVigencia) {
        this.ceFechaFinVigencia = ceFechaFinVigencia;
    }

    
    @Column(name="CE_VIGENCIA", nullable=false, length=5)
    public String getCeVigencia() {
        return this.ceVigencia;
    }
    
    public void setCeVigencia(String ceVigencia) {
        this.ceVigencia = ceVigencia;
    }

    
    @Column(name="CE_ES_INTEGRADO", length=1)
    public String getCeEsIntegrado() {
        return this.ceEsIntegrado;
    }
    
    public void setCeEsIntegrado(String ceEsIntegrado) {
        this.ceEsIntegrado = ceEsIntegrado;
    }

    
    @Column(name="CE_ID_COMPONENTE_PADRE", precision=22, scale=0)
    public BigDecimal getCeIdComponentePadre() {
        return this.ceIdComponentePadre;
    }
    
    public void setCeIdComponentePadre(BigDecimal ceIdComponentePadre) {
        this.ceIdComponentePadre = ceIdComponentePadre;
    }

    
    @Column(name="CE_NUMERO_CREDITOS", precision=22, scale=0)
    public BigDecimal getCeNumeroCreditos() {
        return this.ceNumeroCreditos;
    }
    
    public void setCeNumeroCreditos(BigDecimal ceNumeroCreditos) {
        this.ceNumeroCreditos = ceNumeroCreditos;
    }

    
    @Column(name="CE_VALIDADO", length=1)
    public Character getCeValidado() {
        return this.ceValidado;
    }
    
    public void setCeValidado(Character ceValidado) {
        this.ceValidado = ceValidado;
    }

    
    @Column(name="CE_ID_EQUIVALENCIA_NSGA", precision=22, scale=0)
    public BigDecimal getCeIdEquivalenciaNsga() {
        return this.ceIdEquivalenciaNsga;
    }
    
    public void setCeIdEquivalenciaNsga(BigDecimal ceIdEquivalenciaNsga) {
        this.ceIdEquivalenciaNsga = ceIdEquivalenciaNsga;
    }

    
    @Column(name="CE_COMPETENCIAS", length=3000)
    public String getCeCompetencias() {
        return this.ceCompetencias;
    }
    
    public void setCeCompetencias(String ceCompetencias) {
        this.ceCompetencias = ceCompetencias;
    }

    
    @Column(name="CE_OBSERVACIONES_SECR", length=500)
    public String getCeObservacionesSecr() {
        return this.ceObservacionesSecr;
    }
    
    public void setCeObservacionesSecr(String ceObservacionesSecr) {
        this.ceObservacionesSecr = ceObservacionesSecr;
    }

    
    @Column(name="CE_CODIGO_UNIFICADO_UTPL", length=50)
    public String getCeCodigoUnificadoUtpl() {
        return this.ceCodigoUnificadoUtpl;
    }
    
    public void setCeCodigoUnificadoUtpl(String ceCodigoUnificadoUtpl) {
        this.ceCodigoUnificadoUtpl = ceCodigoUnificadoUtpl;
    }

    
    @Column(name="COU_ID", precision=22, scale=0)
    public BigDecimal getCouId() {
        return this.couId;
    }
    
    public void setCouId(BigDecimal couId) {
        this.couId = couId;
    }

    
    @Column(name="CE_CODIGO_UNIFICADO_PROCESOS", length=50)
    public String getCeCodigoUnificadoProcesos() {
        return this.ceCodigoUnificadoProcesos;
    }
    
    public void setCeCodigoUnificadoProcesos(String ceCodigoUnificadoProcesos) {
        this.ceCodigoUnificadoProcesos = ceCodigoUnificadoProcesos;
    }

    
    @Column(name="CE_CODIGO_UNIFICADO_SIEC", length=50)
    public String getCeCodigoUnificadoSiec() {
        return this.ceCodigoUnificadoSiec;
    }
    
    public void setCeCodigoUnificadoSiec(String ceCodigoUnificadoSiec) {
        this.ceCodigoUnificadoSiec = ceCodigoUnificadoSiec;
    }

    
    @Column(name="CE_CODIGO_UNIFICADO_UTPL_FINAL", length=50)
    public String getCeCodigoUnificadoUtplFinal() {
        return this.ceCodigoUnificadoUtplFinal;
    }
    
    public void setCeCodigoUnificadoUtplFinal(String ceCodigoUnificadoUtplFinal) {
        this.ceCodigoUnificadoUtplFinal = ceCodigoUnificadoUtplFinal;
    }

    
    @Column(name="CE_CODIGO_UNICO_DISTRIBUTIVO", length=25)
    public String getCeCodigoUnicoDistributivo() {
        return this.ceCodigoUnicoDistributivo;
    }
    
    public void setCeCodigoUnicoDistributivo(String ceCodigoUnicoDistributivo) {
        this.ceCodigoUnicoDistributivo = ceCodigoUnicoDistributivo;
    }

    
    @Column(name="CE_TIPO_APROBACION", precision=22, scale=0)
    public BigDecimal getCeTipoAprobacion() {
        return this.ceTipoAprobacion;
    }
    
    public void setCeTipoAprobacion(BigDecimal ceTipoAprobacion) {
        this.ceTipoAprobacion = ceTipoAprobacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CE_FECHA_ACTUALIZACION", length=7)
    public Date getCeFechaActualizacion() {
        return this.ceFechaActualizacion;
    }
    
    public void setCeFechaActualizacion(Date ceFechaActualizacion) {
        this.ceFechaActualizacion = ceFechaActualizacion;
    }

    
    @Column(name="CE_USUARIO_APEX_CREA", length=50)
    public String getCeUsuarioApexCrea() {
        return this.ceUsuarioApexCrea;
    }
    
    public void setCeUsuarioApexCrea(String ceUsuarioApexCrea) {
        this.ceUsuarioApexCrea = ceUsuarioApexCrea;
    }

    
    @Column(name="CE_USUARIO_APEX_ACTUALIZA", length=50)
    public String getCeUsuarioApexActualiza() {
        return this.ceUsuarioApexActualiza;
    }
    
    public void setCeUsuarioApexActualiza(String ceUsuarioApexActualiza) {
        this.ceUsuarioApexActualiza = ceUsuarioApexActualiza;
    }

    
    @Column(name="CE_ID_EQUIVALENCIA_EC", precision=22, scale=0)
    public BigDecimal getCeIdEquivalenciaEc() {
        return this.ceIdEquivalenciaEc;
    }
    
    public void setCeIdEquivalenciaEc(BigDecimal ceIdEquivalenciaEc) {
        this.ceIdEquivalenciaEc = ceIdEquivalenciaEc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CE_FECHA_CREACION_SIEC", length=7)
    public Date getCeFechaCreacionSiec() {
        return this.ceFechaCreacionSiec;
    }
    
    public void setCeFechaCreacionSiec(Date ceFechaCreacionSiec) {
        this.ceFechaCreacionSiec = ceFechaCreacionSiec;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiComponenteEducativo")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiComponenteEducativo")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiComponenteEducativo")
    public Set<TheActividadesEvaAvance> getTheActividadesEvaAvances() {
        return this.theActividadesEvaAvances;
    }
    
    public void setTheActividadesEvaAvances(Set<TheActividadesEvaAvance> theActividadesEvaAvances) {
        this.theActividadesEvaAvances = theActividadesEvaAvances;
    }

/*@OneToOne(fetch=FetchType.LAZY, mappedBy="tdiComponenteEducativo")
    public TdiComponenteEducativo getTdiComponenteEducativo() {
        return this.tdiComponenteEducativo;
    }
    
    public void setTdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo) {
        this.tdiComponenteEducativo = tdiComponenteEducativo;
    }*/

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiComponenteEducativo")
    public Set<TdiOfertaNsga> getTdiOfertaNsgas() {
        return this.tdiOfertaNsgas;
    }
    
    public void setTdiOfertaNsgas(Set<TdiOfertaNsga> tdiOfertaNsgas) {
        this.tdiOfertaNsgas = tdiOfertaNsgas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiComponenteEducativo")
    public Set<TevaMicrovideos> getTevaMicrovideoses() {
        return this.tevaMicrovideoses;
    }
    
    public void setTevaMicrovideoses(Set<TevaMicrovideos> tevaMicrovideoses) {
        this.tevaMicrovideoses = tevaMicrovideoses;
    }




}


