package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiCentroUniversitario generated by hbm2java
 */
@Entity
@Table(name="TDI_CENTRO_UNIVERSITARIO"
    ,schema="ESQ_SIEC"
)
public class TdiCentroUniversitario  implements java.io.Serializable {


     private BigDecimal cuId;
     private TdiGlosario tdiGlosarioByCuIdProvincia;
     private TdiGlosario tdiGlosarioByCuTipoSede;
     private TdiGlosario tdiGlosarioByCuTipoCentro;
     private String cuCodigo;
     private String cuNombre;
     private Date cuFechaCreacion;
     private Date cuFechaActualizacion;
     private String cuVigente;
     private BigDecimal cuEquIdNsga;
     private String cuEquNombreNsga;
     private BigDecimal cuEquIdSga;
     private String cuEquNombreSga;
     private BigDecimal cuEquIdEva;
     private String cuEquNombreEva;
     private BigDecimal cuEquIdRrhh;
     private String cuEquNombreRrhh;
     private String cuValidado;
     private BigDecimal cuIdPadre;
     private BigDecimal cuLongitud;
     private BigDecimal cuLatitud;
     private String cuDireccion;
     private String cuTelefono;
     private String cuFax;
     private String cuCorreo;
     private String cuTipoRegion;
     private BigDecimal cuIdCanton;
     private BigDecimal cuIdPais;
     private Set<TdiDocente> tdiDocentes = new HashSet<TdiDocente>(0);

    public TdiCentroUniversitario() {
    }

	
    public TdiCentroUniversitario(BigDecimal cuId, String cuCodigo, String cuNombre, Date cuFechaCreacion, BigDecimal cuEquIdNsga, String cuEquNombreNsga, String cuValidado) {
        this.cuId = cuId;
        this.cuCodigo = cuCodigo;
        this.cuNombre = cuNombre;
        this.cuFechaCreacion = cuFechaCreacion;
        this.cuEquIdNsga = cuEquIdNsga;
        this.cuEquNombreNsga = cuEquNombreNsga;
        this.cuValidado = cuValidado;
    }
    public TdiCentroUniversitario(BigDecimal cuId, TdiGlosario tdiGlosarioByCuIdProvincia, TdiGlosario tdiGlosarioByCuTipoSede, TdiGlosario tdiGlosarioByCuTipoCentro, String cuCodigo, String cuNombre, Date cuFechaCreacion, Date cuFechaActualizacion, String cuVigente, BigDecimal cuEquIdNsga, String cuEquNombreNsga, BigDecimal cuEquIdSga, String cuEquNombreSga, BigDecimal cuEquIdEva, String cuEquNombreEva, BigDecimal cuEquIdRrhh, String cuEquNombreRrhh, String cuValidado, BigDecimal cuIdPadre, BigDecimal cuLongitud, BigDecimal cuLatitud, String cuDireccion, String cuTelefono, String cuFax, String cuCorreo, String cuTipoRegion, BigDecimal cuIdCanton, BigDecimal cuIdPais, Set<TdiDocente> tdiDocentes) {
       this.cuId = cuId;
       this.tdiGlosarioByCuIdProvincia = tdiGlosarioByCuIdProvincia;
       this.tdiGlosarioByCuTipoSede = tdiGlosarioByCuTipoSede;
       this.tdiGlosarioByCuTipoCentro = tdiGlosarioByCuTipoCentro;
       this.cuCodigo = cuCodigo;
       this.cuNombre = cuNombre;
       this.cuFechaCreacion = cuFechaCreacion;
       this.cuFechaActualizacion = cuFechaActualizacion;
       this.cuVigente = cuVigente;
       this.cuEquIdNsga = cuEquIdNsga;
       this.cuEquNombreNsga = cuEquNombreNsga;
       this.cuEquIdSga = cuEquIdSga;
       this.cuEquNombreSga = cuEquNombreSga;
       this.cuEquIdEva = cuEquIdEva;
       this.cuEquNombreEva = cuEquNombreEva;
       this.cuEquIdRrhh = cuEquIdRrhh;
       this.cuEquNombreRrhh = cuEquNombreRrhh;
       this.cuValidado = cuValidado;
       this.cuIdPadre = cuIdPadre;
       this.cuLongitud = cuLongitud;
       this.cuLatitud = cuLatitud;
       this.cuDireccion = cuDireccion;
       this.cuTelefono = cuTelefono;
       this.cuFax = cuFax;
       this.cuCorreo = cuCorreo;
       this.cuTipoRegion = cuTipoRegion;
       this.cuIdCanton = cuIdCanton;
       this.cuIdPais = cuIdPais;
       this.tdiDocentes = tdiDocentes;
    }
   
     @Id 

    
    @Column(name="CU_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCuId() {
        return this.cuId;
    }
    
    public void setCuId(BigDecimal cuId) {
        this.cuId = cuId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CU_ID_PROVINCIA")
    public TdiGlosario getTdiGlosarioByCuIdProvincia() {
        return this.tdiGlosarioByCuIdProvincia;
    }
    
    public void setTdiGlosarioByCuIdProvincia(TdiGlosario tdiGlosarioByCuIdProvincia) {
        this.tdiGlosarioByCuIdProvincia = tdiGlosarioByCuIdProvincia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CU_TIPO_SEDE")
    public TdiGlosario getTdiGlosarioByCuTipoSede() {
        return this.tdiGlosarioByCuTipoSede;
    }
    
    public void setTdiGlosarioByCuTipoSede(TdiGlosario tdiGlosarioByCuTipoSede) {
        this.tdiGlosarioByCuTipoSede = tdiGlosarioByCuTipoSede;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CU_TIPO_CENTRO")
    public TdiGlosario getTdiGlosarioByCuTipoCentro() {
        return this.tdiGlosarioByCuTipoCentro;
    }
    
    public void setTdiGlosarioByCuTipoCentro(TdiGlosario tdiGlosarioByCuTipoCentro) {
        this.tdiGlosarioByCuTipoCentro = tdiGlosarioByCuTipoCentro;
    }

    
    @Column(name="CU_CODIGO", nullable=false, length=30)
    public String getCuCodigo() {
        return this.cuCodigo;
    }
    
    public void setCuCodigo(String cuCodigo) {
        this.cuCodigo = cuCodigo;
    }

    
    @Column(name="CU_NOMBRE", nullable=false, length=100)
    public String getCuNombre() {
        return this.cuNombre;
    }
    
    public void setCuNombre(String cuNombre) {
        this.cuNombre = cuNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CU_FECHA_CREACION", nullable=false, length=7)
    public Date getCuFechaCreacion() {
        return this.cuFechaCreacion;
    }
    
    public void setCuFechaCreacion(Date cuFechaCreacion) {
        this.cuFechaCreacion = cuFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CU_FECHA_ACTUALIZACION", length=7)
    public Date getCuFechaActualizacion() {
        return this.cuFechaActualizacion;
    }
    
    public void setCuFechaActualizacion(Date cuFechaActualizacion) {
        this.cuFechaActualizacion = cuFechaActualizacion;
    }

    
    @Column(name="CU_VIGENTE", length=1)
    public String getCuVigente() {
        return this.cuVigente;
    }
    
    public void setCuVigente(String cuVigente) {
        this.cuVigente = cuVigente;
    }

    
    @Column(name="CU_EQU_ID_NSGA", nullable=false, precision=22, scale=0)
    public BigDecimal getCuEquIdNsga() {
        return this.cuEquIdNsga;
    }
    
    public void setCuEquIdNsga(BigDecimal cuEquIdNsga) {
        this.cuEquIdNsga = cuEquIdNsga;
    }

    
    @Column(name="CU_EQU_NOMBRE_NSGA", nullable=false, length=100)
    public String getCuEquNombreNsga() {
        return this.cuEquNombreNsga;
    }
    
    public void setCuEquNombreNsga(String cuEquNombreNsga) {
        this.cuEquNombreNsga = cuEquNombreNsga;
    }

    
    @Column(name="CU_EQU_ID_SGA", precision=22, scale=0)
    public BigDecimal getCuEquIdSga() {
        return this.cuEquIdSga;
    }
    
    public void setCuEquIdSga(BigDecimal cuEquIdSga) {
        this.cuEquIdSga = cuEquIdSga;
    }

    
    @Column(name="CU_EQU_NOMBRE_SGA", length=100)
    public String getCuEquNombreSga() {
        return this.cuEquNombreSga;
    }
    
    public void setCuEquNombreSga(String cuEquNombreSga) {
        this.cuEquNombreSga = cuEquNombreSga;
    }

    
    @Column(name="CU_EQU_ID_EVA", precision=22, scale=0)
    public BigDecimal getCuEquIdEva() {
        return this.cuEquIdEva;
    }
    
    public void setCuEquIdEva(BigDecimal cuEquIdEva) {
        this.cuEquIdEva = cuEquIdEva;
    }

    
    @Column(name="CU_EQU_NOMBRE_EVA", length=100)
    public String getCuEquNombreEva() {
        return this.cuEquNombreEva;
    }
    
    public void setCuEquNombreEva(String cuEquNombreEva) {
        this.cuEquNombreEva = cuEquNombreEva;
    }

    
    @Column(name="CU_EQU_ID_RRHH", precision=22, scale=0)
    public BigDecimal getCuEquIdRrhh() {
        return this.cuEquIdRrhh;
    }
    
    public void setCuEquIdRrhh(BigDecimal cuEquIdRrhh) {
        this.cuEquIdRrhh = cuEquIdRrhh;
    }

    
    @Column(name="CU_EQU_NOMBRE_RRHH", length=100)
    public String getCuEquNombreRrhh() {
        return this.cuEquNombreRrhh;
    }
    
    public void setCuEquNombreRrhh(String cuEquNombreRrhh) {
        this.cuEquNombreRrhh = cuEquNombreRrhh;
    }

    
    @Column(name="CU_VALIDADO", nullable=false, length=1)
    public String getCuValidado() {
        return this.cuValidado;
    }
    
    public void setCuValidado(String cuValidado) {
        this.cuValidado = cuValidado;
    }

    
    @Column(name="CU_ID_PADRE", precision=22, scale=0)
    public BigDecimal getCuIdPadre() {
        return this.cuIdPadre;
    }
    
    public void setCuIdPadre(BigDecimal cuIdPadre) {
        this.cuIdPadre = cuIdPadre;
    }

    
    @Column(name="CU_LONGITUD", precision=22, scale=0)
    public BigDecimal getCuLongitud() {
        return this.cuLongitud;
    }
    
    public void setCuLongitud(BigDecimal cuLongitud) {
        this.cuLongitud = cuLongitud;
    }

    
    @Column(name="CU_LATITUD", precision=22, scale=0)
    public BigDecimal getCuLatitud() {
        return this.cuLatitud;
    }
    
    public void setCuLatitud(BigDecimal cuLatitud) {
        this.cuLatitud = cuLatitud;
    }

    
    @Column(name="CU_DIRECCION", length=500)
    public String getCuDireccion() {
        return this.cuDireccion;
    }
    
    public void setCuDireccion(String cuDireccion) {
        this.cuDireccion = cuDireccion;
    }

    
    @Column(name="CU_TELEFONO", length=25)
    public String getCuTelefono() {
        return this.cuTelefono;
    }
    
    public void setCuTelefono(String cuTelefono) {
        this.cuTelefono = cuTelefono;
    }

    
    @Column(name="CU_FAX", length=25)
    public String getCuFax() {
        return this.cuFax;
    }
    
    public void setCuFax(String cuFax) {
        this.cuFax = cuFax;
    }

    
    @Column(name="CU_CORREO", length=100)
    public String getCuCorreo() {
        return this.cuCorreo;
    }
    
    public void setCuCorreo(String cuCorreo) {
        this.cuCorreo = cuCorreo;
    }

    
    @Column(name="CU_TIPO_REGION", length=1)
    public String getCuTipoRegion() {
        return this.cuTipoRegion;
    }
    
    public void setCuTipoRegion(String cuTipoRegion) {
        this.cuTipoRegion = cuTipoRegion;
    }

    
    @Column(name="CU_ID_CANTON", precision=22, scale=0)
    public BigDecimal getCuIdCanton() {
        return this.cuIdCanton;
    }
    
    public void setCuIdCanton(BigDecimal cuIdCanton) {
        this.cuIdCanton = cuIdCanton;
    }

    
    @Column(name="CU_ID_PAIS", precision=22, scale=0)
    public BigDecimal getCuIdPais() {
        return this.cuIdPais;
    }
    
    public void setCuIdPais(BigDecimal cuIdPais) {
        this.cuIdPais = cuIdPais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiCentroUniversitario")
    public Set<TdiDocente> getTdiDocentes() {
        return this.tdiDocentes;
    }
    
    public void setTdiDocentes(Set<TdiDocente> tdiDocentes) {
        this.tdiDocentes = tdiDocentes;
    }




}


