package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiDepartamento generated by hbm2java
 */
@Entity
@Table(name="TDI_DEPARTAMENTO"
    ,schema="ESQ_SIEC"
)
public class TdiDepartamento  implements java.io.Serializable {


     private BigDecimal deId;
     private TdiArea tdiArea;
     private String deNombre;
     private Date deFechaInicioVigencia;
     private Date deFechaFinVigencia;
     private String deVigente;
     private Date deFechaActualizacion;
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);
     private Set<TheActividadesEvaAvance> theActividadesEvaAvances = new HashSet<TheActividadesEvaAvance>(0);
     private Set<TdiSeccionDepartamental> tdiSeccionDepartamentals = new HashSet<TdiSeccionDepartamental>(0);

    public TdiDepartamento() {
    }

	
    public TdiDepartamento(BigDecimal deId, TdiArea tdiArea, String deNombre, Date deFechaInicioVigencia, String deVigente) {
        this.deId = deId;
        this.tdiArea = tdiArea;
        this.deNombre = deNombre;
        this.deFechaInicioVigencia = deFechaInicioVigencia;
        this.deVigente = deVigente;
    }
    public TdiDepartamento(BigDecimal deId, TdiArea tdiArea, String deNombre, Date deFechaInicioVigencia, Date deFechaFinVigencia, String deVigente, Date deFechaActualizacion, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TheActividadesEvaAvance> theActividadesEvaAvances, Set<TdiSeccionDepartamental> tdiSeccionDepartamentals) {
       this.deId = deId;
       this.tdiArea = tdiArea;
       this.deNombre = deNombre;
       this.deFechaInicioVigencia = deFechaInicioVigencia;
       this.deFechaFinVigencia = deFechaFinVigencia;
       this.deVigente = deVigente;
       this.deFechaActualizacion = deFechaActualizacion;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.theActividadesEvaAvances = theActividadesEvaAvances;
       this.tdiSeccionDepartamentals = tdiSeccionDepartamentals;
    }
   
     @Id 

    
    @Column(name="DE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getDeId() {
        return this.deId;
    }
    
    public void setDeId(BigDecimal deId) {
        this.deId = deId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AR_ID", nullable=false)
    public TdiArea getTdiArea() {
        return this.tdiArea;
    }
    
    public void setTdiArea(TdiArea tdiArea) {
        this.tdiArea = tdiArea;
    }

    
    @Column(name="DE_NOMBRE", nullable=false, length=300)
    public String getDeNombre() {
        return this.deNombre;
    }
    
    public void setDeNombre(String deNombre) {
        this.deNombre = deNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DE_FECHA_INICIO_VIGENCIA", nullable=false, length=7)
    public Date getDeFechaInicioVigencia() {
        return this.deFechaInicioVigencia;
    }
    
    public void setDeFechaInicioVigencia(Date deFechaInicioVigencia) {
        this.deFechaInicioVigencia = deFechaInicioVigencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DE_FECHA_FIN_VIGENCIA", length=7)
    public Date getDeFechaFinVigencia() {
        return this.deFechaFinVigencia;
    }
    
    public void setDeFechaFinVigencia(Date deFechaFinVigencia) {
        this.deFechaFinVigencia = deFechaFinVigencia;
    }

    
    @Column(name="DE_VIGENTE", nullable=false, length=1)
    public String getDeVigente() {
        return this.deVigente;
    }
    
    public void setDeVigente(String deVigente) {
        this.deVigente = deVigente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DE_FECHA_ACTUALIZACION", length=7)
    public Date getDeFechaActualizacion() {
        return this.deFechaActualizacion;
    }
    
    public void setDeFechaActualizacion(Date deFechaActualizacion) {
        this.deFechaActualizacion = deFechaActualizacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDepartamento")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDepartamento")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDepartamento")
    public Set<TheActividadesEvaAvance> getTheActividadesEvaAvances() {
        return this.theActividadesEvaAvances;
    }
    
    public void setTheActividadesEvaAvances(Set<TheActividadesEvaAvance> theActividadesEvaAvances) {
        this.theActividadesEvaAvances = theActividadesEvaAvances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDepartamento")
    public Set<TdiSeccionDepartamental> getTdiSeccionDepartamentals() {
        return this.tdiSeccionDepartamentals;
    }
    
    public void setTdiSeccionDepartamentals(Set<TdiSeccionDepartamental> tdiSeccionDepartamentals) {
        this.tdiSeccionDepartamentals = tdiSeccionDepartamentals;
    }




}


