package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiDetParametrosIndicador generated by hbm2java
 */
@Entity
@Table(name="TDI_DET_PARAMETROS_INDICADOR"
    ,schema="ESQ_SIEC"
)
public class TdiDetParametrosIndicador  implements java.io.Serializable {


     private BigDecimal dpiId;
     private TdiParametrosIndicador tdiParametrosIndicador;
     private BigDecimal onsId;
     private BigDecimal usIdEvaCrea;
     private BigDecimal usIdEvaActualiza;
     private BigDecimal idCursoEva;
     private String dpiCodigoActividadEva;
     private String dpiEsMetacurso;
     private BigDecimal dpiCantidadObjetivo;
     private Date dpiFechaDesde;
     private String dpiUsuarioCreacionSiec;
     private Date dpiFechaHasta;
     private String dpiUsuarioActualizacionSiec;

    public TdiDetParametrosIndicador() {
    }

	
    public TdiDetParametrosIndicador(BigDecimal dpiId, TdiParametrosIndicador tdiParametrosIndicador, String dpiEsMetacurso, BigDecimal dpiCantidadObjetivo, Date dpiFechaDesde) {
        this.dpiId = dpiId;
        this.tdiParametrosIndicador = tdiParametrosIndicador;
        this.dpiEsMetacurso = dpiEsMetacurso;
        this.dpiCantidadObjetivo = dpiCantidadObjetivo;
        this.dpiFechaDesde = dpiFechaDesde;
    }
    public TdiDetParametrosIndicador(BigDecimal dpiId, TdiParametrosIndicador tdiParametrosIndicador, BigDecimal onsId, BigDecimal usIdEvaCrea, BigDecimal usIdEvaActualiza, BigDecimal idCursoEva, String dpiCodigoActividadEva, String dpiEsMetacurso, BigDecimal dpiCantidadObjetivo, Date dpiFechaDesde, String dpiUsuarioCreacionSiec, Date dpiFechaHasta, String dpiUsuarioActualizacionSiec) {
       this.dpiId = dpiId;
       this.tdiParametrosIndicador = tdiParametrosIndicador;
       this.onsId = onsId;
       this.usIdEvaCrea = usIdEvaCrea;
       this.usIdEvaActualiza = usIdEvaActualiza;
       this.idCursoEva = idCursoEva;
       this.dpiCodigoActividadEva = dpiCodigoActividadEva;
       this.dpiEsMetacurso = dpiEsMetacurso;
       this.dpiCantidadObjetivo = dpiCantidadObjetivo;
       this.dpiFechaDesde = dpiFechaDesde;
       this.dpiUsuarioCreacionSiec = dpiUsuarioCreacionSiec;
       this.dpiFechaHasta = dpiFechaHasta;
       this.dpiUsuarioActualizacionSiec = dpiUsuarioActualizacionSiec;
    }
   
     @Id 

    
    @Column(name="DPI_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getDpiId() {
        return this.dpiId;
    }
    
    public void setDpiId(BigDecimal dpiId) {
        this.dpiId = dpiId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PI_ID", nullable=false)
    public TdiParametrosIndicador getTdiParametrosIndicador() {
        return this.tdiParametrosIndicador;
    }
    
    public void setTdiParametrosIndicador(TdiParametrosIndicador tdiParametrosIndicador) {
        this.tdiParametrosIndicador = tdiParametrosIndicador;
    }

    
    @Column(name="ONS_ID", precision=22, scale=0)
    public BigDecimal getOnsId() {
        return this.onsId;
    }
    
    public void setOnsId(BigDecimal onsId) {
        this.onsId = onsId;
    }

    
    @Column(name="US_ID_EVA_CREA", precision=22, scale=0)
    public BigDecimal getUsIdEvaCrea() {
        return this.usIdEvaCrea;
    }
    
    public void setUsIdEvaCrea(BigDecimal usIdEvaCrea) {
        this.usIdEvaCrea = usIdEvaCrea;
    }

    
    @Column(name="US_ID_EVA_ACTUALIZA", precision=22, scale=0)
    public BigDecimal getUsIdEvaActualiza() {
        return this.usIdEvaActualiza;
    }
    
    public void setUsIdEvaActualiza(BigDecimal usIdEvaActualiza) {
        this.usIdEvaActualiza = usIdEvaActualiza;
    }

    
    @Column(name="ID_CURSO_EVA", precision=22, scale=0)
    public BigDecimal getIdCursoEva() {
        return this.idCursoEva;
    }
    
    public void setIdCursoEva(BigDecimal idCursoEva) {
        this.idCursoEva = idCursoEva;
    }

    
    @Column(name="DPI_CODIGO_ACTIVIDAD_EVA", length=25)
    public String getDpiCodigoActividadEva() {
        return this.dpiCodigoActividadEva;
    }
    
    public void setDpiCodigoActividadEva(String dpiCodigoActividadEva) {
        this.dpiCodigoActividadEva = dpiCodigoActividadEva;
    }

    
    @Column(name="DPI_ES_METACURSO", nullable=false, length=1)
    public String getDpiEsMetacurso() {
        return this.dpiEsMetacurso;
    }
    
    public void setDpiEsMetacurso(String dpiEsMetacurso) {
        this.dpiEsMetacurso = dpiEsMetacurso;
    }

    
    @Column(name="DPI_CANTIDAD_OBJETIVO", nullable=false, precision=22, scale=0)
    public BigDecimal getDpiCantidadObjetivo() {
        return this.dpiCantidadObjetivo;
    }
    
    public void setDpiCantidadObjetivo(BigDecimal dpiCantidadObjetivo) {
        this.dpiCantidadObjetivo = dpiCantidadObjetivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DPI_FECHA_DESDE", nullable=false, length=7)
    public Date getDpiFechaDesde() {
        return this.dpiFechaDesde;
    }
    
    public void setDpiFechaDesde(Date dpiFechaDesde) {
        this.dpiFechaDesde = dpiFechaDesde;
    }

    
    @Column(name="DPI_USUARIO_CREACION_SIEC", length=200)
    public String getDpiUsuarioCreacionSiec() {
        return this.dpiUsuarioCreacionSiec;
    }
    
    public void setDpiUsuarioCreacionSiec(String dpiUsuarioCreacionSiec) {
        this.dpiUsuarioCreacionSiec = dpiUsuarioCreacionSiec;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DPI_FECHA_HASTA", length=7)
    public Date getDpiFechaHasta() {
        return this.dpiFechaHasta;
    }
    
    public void setDpiFechaHasta(Date dpiFechaHasta) {
        this.dpiFechaHasta = dpiFechaHasta;
    }

    
    @Column(name="DPI_USUARIO_ACTUALIZACION_SIEC", length=200)
    public String getDpiUsuarioActualizacionSiec() {
        return this.dpiUsuarioActualizacionSiec;
    }
    
    public void setDpiUsuarioActualizacionSiec(String dpiUsuarioActualizacionSiec) {
        this.dpiUsuarioActualizacionSiec = dpiUsuarioActualizacionSiec;
    }




}


