package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TdiDocente generated by hbm2java
 */
@Entity
@Table(name="TDI_DOCENTE"
    ,schema="ESQ_SIEC"
    , uniqueConstraints = {@UniqueConstraint(columnNames="DO_EQU_ID_SGA"), @UniqueConstraint(columnNames="DO_EQU_ID_NSGA")} 
)
public class TdiDocente  implements java.io.Serializable {


     private BigDecimal doId;
     private TdiCentroUniversitario tdiCentroUniversitario;
     private TdiGlosario tdiGlosarioByDoTipoIdentificacion;
     private TdiGlosario tdiGlosarioByDoNacionalidad;
     private TdsUsuario tdsUsuario;
     private String doIdentificacion;
     private String doApellidoPaterno;
     private String doApellidoMaterno;
     private String doPrimerNombre;
     private String doSegundoNombre;
     private Date doFechaNacimiento;
     private BigDecimal doEquIdNsga;
     private BigDecimal doEquIdSga;
     private BigDecimal doEquIdSica;
     private BigDecimal doEquIdEva;
     private String doGenero;
     private Date doFechaCreacion;
     private Date doFechaActualizacion;
     private String doEstado;
     private String doCorreoPri;
     private String doCorreoSec;
     private String doTelefonoDom;
     private String doCelularPri;
     private String doCelularSec;
     private String doPrometeo;
     private BigDecimal doEquIdCittes;
     private BigDecimal doEquIdNsga2;
     private String doIdentificacionRrhh;
     private String doValidadoRrhh;
     private String doExtension;
     private Character doTecnicoDocente;
     private Date doFechaIngreso;
     private Date doFechaSalida;
     private String usuarioApexCrea;
     private String usuarioApexActualiza;
     private String doCorreoPersonal;
     private String doEsAdministrativo;
     private BigDecimal doIdTipoSangre;
     private BigDecimal doEquIdRrHh;
     private String doIdentificacionNomina;
     private String doRepetidoNsga;
     private String doObservacionesRepetido;
     private BigDecimal doEquiIdNomina;
     private BigDecimal doEquiIdRegistro;
     private BigDecimal doCantonNacimiento;
     private BigDecimal doProvinciaNacimiento;
     private BigDecimal doTipoDiscapacidad;
     private BigDecimal doPorcentajeDiscapacidad;
     private String doNumeroCarnetConadis;
     private String doObservacion;
     private String doIdentificacionNsga;
     private Blob doFoto;
     private String doFotoMimetype;
     private String doFotoFilename;
     private Date doFotoLastUpdate;
     private BigDecimal doEquIdNsga3;
     private Date doFechaInicioAdenda;
     private Date doFechaFinAdenda;
     private Date doFechaValidacionRrhh;
     private BigDecimal doEstadoCivil;
     private Character doContratoIndefinido;
     private Character doEstadoNomina;
     private Character doEstadoRrhh;
     private String doCodigoUtpl;
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);
     private Set<TdiOfertaDocentesNsga> tdiOfertaDocentesNsgas = new HashSet<TdiOfertaDocentesNsga>(0);
     private Set<TheActividadesEvaAvance> theActividadesEvaAvances = new HashSet<TheActividadesEvaAvance>(0);
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);
     private Set<TevaMicrovideos> tevaMicrovideoses = new HashSet<TevaMicrovideos>(0);

    public TdiDocente() {
    }

	
    public TdiDocente(BigDecimal doId, TdiGlosario tdiGlosarioByDoTipoIdentificacion, String doIdentificacion, String doApellidoPaterno, String doPrimerNombre, String doGenero, Date doFechaCreacion, String doEstado, String doPrometeo) {
        this.doId = doId;
        this.tdiGlosarioByDoTipoIdentificacion = tdiGlosarioByDoTipoIdentificacion;
        this.doIdentificacion = doIdentificacion;
        this.doApellidoPaterno = doApellidoPaterno;
        this.doPrimerNombre = doPrimerNombre;
        this.doGenero = doGenero;
        this.doFechaCreacion = doFechaCreacion;
        this.doEstado = doEstado;
        this.doPrometeo = doPrometeo;
    }
    public TdiDocente(BigDecimal doId, TdiCentroUniversitario tdiCentroUniversitario, TdiGlosario tdiGlosarioByDoTipoIdentificacion, TdiGlosario tdiGlosarioByDoNacionalidad, TdsUsuario tdsUsuario, String doIdentificacion, String doApellidoPaterno, String doApellidoMaterno, String doPrimerNombre, String doSegundoNombre, Date doFechaNacimiento, BigDecimal doEquIdNsga, BigDecimal doEquIdSga, BigDecimal doEquIdSica, BigDecimal doEquIdEva, String doGenero, Date doFechaCreacion, Date doFechaActualizacion, String doEstado, String doCorreoPri, String doCorreoSec, String doTelefonoDom, String doCelularPri, String doCelularSec, String doPrometeo, BigDecimal doEquIdCittes, BigDecimal doEquIdNsga2, String doIdentificacionRrhh, String doValidadoRrhh, String doExtension, Character doTecnicoDocente, Date doFechaIngreso, Date doFechaSalida, String usuarioApexCrea, String usuarioApexActualiza, String doCorreoPersonal, String doEsAdministrativo, BigDecimal doIdTipoSangre, BigDecimal doEquIdRrHh, String doIdentificacionNomina, String doRepetidoNsga, String doObservacionesRepetido, BigDecimal doEquiIdNomina, BigDecimal doEquiIdRegistro, BigDecimal doCantonNacimiento, BigDecimal doProvinciaNacimiento, BigDecimal doTipoDiscapacidad, BigDecimal doPorcentajeDiscapacidad, String doNumeroCarnetConadis, String doObservacion, String doIdentificacionNsga, Blob doFoto, String doFotoMimetype, String doFotoFilename, Date doFotoLastUpdate, BigDecimal doEquIdNsga3, Date doFechaInicioAdenda, Date doFechaFinAdenda, Date doFechaValidacionRrhh, BigDecimal doEstadoCivil, Character doContratoIndefinido, Character doEstadoNomina, Character doEstadoRrhh, String doCodigoUtpl, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets, Set<TdiOfertaDocentesNsga> tdiOfertaDocentesNsgas, Set<TheActividadesEvaAvance> theActividadesEvaAvances, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TevaMicrovideos> tevaMicrovideoses) {
       this.doId = doId;
       this.tdiCentroUniversitario = tdiCentroUniversitario;
       this.tdiGlosarioByDoTipoIdentificacion = tdiGlosarioByDoTipoIdentificacion;
       this.tdiGlosarioByDoNacionalidad = tdiGlosarioByDoNacionalidad;
       this.tdsUsuario = tdsUsuario;
       this.doIdentificacion = doIdentificacion;
       this.doApellidoPaterno = doApellidoPaterno;
       this.doApellidoMaterno = doApellidoMaterno;
       this.doPrimerNombre = doPrimerNombre;
       this.doSegundoNombre = doSegundoNombre;
       this.doFechaNacimiento = doFechaNacimiento;
       this.doEquIdNsga = doEquIdNsga;
       this.doEquIdSga = doEquIdSga;
       this.doEquIdSica = doEquIdSica;
       this.doEquIdEva = doEquIdEva;
       this.doGenero = doGenero;
       this.doFechaCreacion = doFechaCreacion;
       this.doFechaActualizacion = doFechaActualizacion;
       this.doEstado = doEstado;
       this.doCorreoPri = doCorreoPri;
       this.doCorreoSec = doCorreoSec;
       this.doTelefonoDom = doTelefonoDom;
       this.doCelularPri = doCelularPri;
       this.doCelularSec = doCelularSec;
       this.doPrometeo = doPrometeo;
       this.doEquIdCittes = doEquIdCittes;
       this.doEquIdNsga2 = doEquIdNsga2;
       this.doIdentificacionRrhh = doIdentificacionRrhh;
       this.doValidadoRrhh = doValidadoRrhh;
       this.doExtension = doExtension;
       this.doTecnicoDocente = doTecnicoDocente;
       this.doFechaIngreso = doFechaIngreso;
       this.doFechaSalida = doFechaSalida;
       this.usuarioApexCrea = usuarioApexCrea;
       this.usuarioApexActualiza = usuarioApexActualiza;
       this.doCorreoPersonal = doCorreoPersonal;
       this.doEsAdministrativo = doEsAdministrativo;
       this.doIdTipoSangre = doIdTipoSangre;
       this.doEquIdRrHh = doEquIdRrHh;
       this.doIdentificacionNomina = doIdentificacionNomina;
       this.doRepetidoNsga = doRepetidoNsga;
       this.doObservacionesRepetido = doObservacionesRepetido;
       this.doEquiIdNomina = doEquiIdNomina;
       this.doEquiIdRegistro = doEquiIdRegistro;
       this.doCantonNacimiento = doCantonNacimiento;
       this.doProvinciaNacimiento = doProvinciaNacimiento;
       this.doTipoDiscapacidad = doTipoDiscapacidad;
       this.doPorcentajeDiscapacidad = doPorcentajeDiscapacidad;
       this.doNumeroCarnetConadis = doNumeroCarnetConadis;
       this.doObservacion = doObservacion;
       this.doIdentificacionNsga = doIdentificacionNsga;
       this.doFoto = doFoto;
       this.doFotoMimetype = doFotoMimetype;
       this.doFotoFilename = doFotoFilename;
       this.doFotoLastUpdate = doFotoLastUpdate;
       this.doEquIdNsga3 = doEquIdNsga3;
       this.doFechaInicioAdenda = doFechaInicioAdenda;
       this.doFechaFinAdenda = doFechaFinAdenda;
       this.doFechaValidacionRrhh = doFechaValidacionRrhh;
       this.doEstadoCivil = doEstadoCivil;
       this.doContratoIndefinido = doContratoIndefinido;
       this.doEstadoNomina = doEstadoNomina;
       this.doEstadoRrhh = doEstadoRrhh;
       this.doCodigoUtpl = doCodigoUtpl;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
       this.tdiOfertaDocentesNsgas = tdiOfertaDocentesNsgas;
       this.theActividadesEvaAvances = theActividadesEvaAvances;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.tevaMicrovideoses = tevaMicrovideoses;
    }
   
     @Id 

    
    @Column(name="DO_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getDoId() {
        return this.doId;
    }
    
    public void setDoId(BigDecimal doId) {
        this.doId = doId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CU_ID")
    public TdiCentroUniversitario getTdiCentroUniversitario() {
        return this.tdiCentroUniversitario;
    }
    
    public void setTdiCentroUniversitario(TdiCentroUniversitario tdiCentroUniversitario) {
        this.tdiCentroUniversitario = tdiCentroUniversitario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DO_TIPO_IDENTIFICACION", nullable=false)
    public TdiGlosario getTdiGlosarioByDoTipoIdentificacion() {
        return this.tdiGlosarioByDoTipoIdentificacion;
    }
    
    public void setTdiGlosarioByDoTipoIdentificacion(TdiGlosario tdiGlosarioByDoTipoIdentificacion) {
        this.tdiGlosarioByDoTipoIdentificacion = tdiGlosarioByDoTipoIdentificacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DO_NACIONALIDAD")
    public TdiGlosario getTdiGlosarioByDoNacionalidad() {
        return this.tdiGlosarioByDoNacionalidad;
    }
    
    public void setTdiGlosarioByDoNacionalidad(TdiGlosario tdiGlosarioByDoNacionalidad) {
        this.tdiGlosarioByDoNacionalidad = tdiGlosarioByDoNacionalidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DO_VALIDADOR_RRHH")
    public TdsUsuario getTdsUsuario() {
        return this.tdsUsuario;
    }
    
    public void setTdsUsuario(TdsUsuario tdsUsuario) {
        this.tdsUsuario = tdsUsuario;
    }

    
    @Column(name="DO_IDENTIFICACION", nullable=false, length=13)
    public String getDoIdentificacion() {
        return this.doIdentificacion;
    }
    
    public void setDoIdentificacion(String doIdentificacion) {
        this.doIdentificacion = doIdentificacion;
    }

    
    @Column(name="DO_APELLIDO_PATERNO", nullable=false, length=100)
    public String getDoApellidoPaterno() {
        return this.doApellidoPaterno;
    }
    
    public void setDoApellidoPaterno(String doApellidoPaterno) {
        this.doApellidoPaterno = doApellidoPaterno;
    }

    
    @Column(name="DO_APELLIDO_MATERNO", length=100)
    public String getDoApellidoMaterno() {
        return this.doApellidoMaterno;
    }
    
    public void setDoApellidoMaterno(String doApellidoMaterno) {
        this.doApellidoMaterno = doApellidoMaterno;
    }

    
    @Column(name="DO_PRIMER_NOMBRE", nullable=false, length=100)
    public String getDoPrimerNombre() {
        return this.doPrimerNombre;
    }
    
    public void setDoPrimerNombre(String doPrimerNombre) {
        this.doPrimerNombre = doPrimerNombre;
    }

    
    @Column(name="DO_SEGUNDO_NOMBRE", length=100)
    public String getDoSegundoNombre() {
        return this.doSegundoNombre;
    }
    
    public void setDoSegundoNombre(String doSegundoNombre) {
        this.doSegundoNombre = doSegundoNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FECHA_NACIMIENTO", length=7)
    public Date getDoFechaNacimiento() {
        return this.doFechaNacimiento;
    }
    
    public void setDoFechaNacimiento(Date doFechaNacimiento) {
        this.doFechaNacimiento = doFechaNacimiento;
    }

    
    @Column(name="DO_EQU_ID_NSGA", unique=true, precision=22, scale=0)
    public BigDecimal getDoEquIdNsga() {
        return this.doEquIdNsga;
    }
    
    public void setDoEquIdNsga(BigDecimal doEquIdNsga) {
        this.doEquIdNsga = doEquIdNsga;
    }

    
    @Column(name="DO_EQU_ID_SGA", unique=true, precision=22, scale=0)
    public BigDecimal getDoEquIdSga() {
        return this.doEquIdSga;
    }
    
    public void setDoEquIdSga(BigDecimal doEquIdSga) {
        this.doEquIdSga = doEquIdSga;
    }

    
    @Column(name="DO_EQU_ID_SICA", precision=22, scale=0)
    public BigDecimal getDoEquIdSica() {
        return this.doEquIdSica;
    }
    
    public void setDoEquIdSica(BigDecimal doEquIdSica) {
        this.doEquIdSica = doEquIdSica;
    }

    
    @Column(name="DO_EQU_ID_EVA", precision=22, scale=0)
    public BigDecimal getDoEquIdEva() {
        return this.doEquIdEva;
    }
    
    public void setDoEquIdEva(BigDecimal doEquIdEva) {
        this.doEquIdEva = doEquIdEva;
    }

    
    @Column(name="DO_GENERO", nullable=false, length=2)
    public String getDoGenero() {
        return this.doGenero;
    }
    
    public void setDoGenero(String doGenero) {
        this.doGenero = doGenero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FECHA_CREACION", nullable=false, length=7)
    public Date getDoFechaCreacion() {
        return this.doFechaCreacion;
    }
    
    public void setDoFechaCreacion(Date doFechaCreacion) {
        this.doFechaCreacion = doFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FECHA_ACTUALIZACION", length=7)
    public Date getDoFechaActualizacion() {
        return this.doFechaActualizacion;
    }
    
    public void setDoFechaActualizacion(Date doFechaActualizacion) {
        this.doFechaActualizacion = doFechaActualizacion;
    }

    
    @Column(name="DO_ESTADO", nullable=false, length=1)
    public String getDoEstado() {
        return this.doEstado;
    }
    
    public void setDoEstado(String doEstado) {
        this.doEstado = doEstado;
    }

    
    @Column(name="DO_CORREO_PRI", length=120)
    public String getDoCorreoPri() {
        return this.doCorreoPri;
    }
    
    public void setDoCorreoPri(String doCorreoPri) {
        this.doCorreoPri = doCorreoPri;
    }

    
    @Column(name="DO_CORREO_SEC", length=120)
    public String getDoCorreoSec() {
        return this.doCorreoSec;
    }
    
    public void setDoCorreoSec(String doCorreoSec) {
        this.doCorreoSec = doCorreoSec;
    }

    
    @Column(name="DO_TELEFONO_DOM", length=30)
    public String getDoTelefonoDom() {
        return this.doTelefonoDom;
    }
    
    public void setDoTelefonoDom(String doTelefonoDom) {
        this.doTelefonoDom = doTelefonoDom;
    }

    
    @Column(name="DO_CELULAR_PRI", length=30)
    public String getDoCelularPri() {
        return this.doCelularPri;
    }
    
    public void setDoCelularPri(String doCelularPri) {
        this.doCelularPri = doCelularPri;
    }

    
    @Column(name="DO_CELULAR_SEC", length=30)
    public String getDoCelularSec() {
        return this.doCelularSec;
    }
    
    public void setDoCelularSec(String doCelularSec) {
        this.doCelularSec = doCelularSec;
    }

    
    @Column(name="DO_PROMETEO", nullable=false, length=1)
    public String getDoPrometeo() {
        return this.doPrometeo;
    }
    
    public void setDoPrometeo(String doPrometeo) {
        this.doPrometeo = doPrometeo;
    }

    
    @Column(name="DO_EQU_ID_CITTES", precision=22, scale=0)
    public BigDecimal getDoEquIdCittes() {
        return this.doEquIdCittes;
    }
    
    public void setDoEquIdCittes(BigDecimal doEquIdCittes) {
        this.doEquIdCittes = doEquIdCittes;
    }

    
    @Column(name="DO_EQU_ID_NSGA2", precision=22, scale=0)
    public BigDecimal getDoEquIdNsga2() {
        return this.doEquIdNsga2;
    }
    
    public void setDoEquIdNsga2(BigDecimal doEquIdNsga2) {
        this.doEquIdNsga2 = doEquIdNsga2;
    }

    
    @Column(name="DO_IDENTIFICACION_RRHH", length=15)
    public String getDoIdentificacionRrhh() {
        return this.doIdentificacionRrhh;
    }
    
    public void setDoIdentificacionRrhh(String doIdentificacionRrhh) {
        this.doIdentificacionRrhh = doIdentificacionRrhh;
    }

    
    @Column(name="DO_VALIDADO_RRHH", length=1)
    public String getDoValidadoRrhh() {
        return this.doValidadoRrhh;
    }
    
    public void setDoValidadoRrhh(String doValidadoRrhh) {
        this.doValidadoRrhh = doValidadoRrhh;
    }

    
    @Column(name="DO_EXTENSION", length=20)
    public String getDoExtension() {
        return this.doExtension;
    }
    
    public void setDoExtension(String doExtension) {
        this.doExtension = doExtension;
    }

    
    @Column(name="DO_TECNICO_DOCENTE", length=1)
    public Character getDoTecnicoDocente() {
        return this.doTecnicoDocente;
    }
    
    public void setDoTecnicoDocente(Character doTecnicoDocente) {
        this.doTecnicoDocente = doTecnicoDocente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FECHA_INGRESO", length=7)
    public Date getDoFechaIngreso() {
        return this.doFechaIngreso;
    }
    
    public void setDoFechaIngreso(Date doFechaIngreso) {
        this.doFechaIngreso = doFechaIngreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FECHA_SALIDA", length=7)
    public Date getDoFechaSalida() {
        return this.doFechaSalida;
    }
    
    public void setDoFechaSalida(Date doFechaSalida) {
        this.doFechaSalida = doFechaSalida;
    }

    
    @Column(name="USUARIO_APEX_CREA", length=50)
    public String getUsuarioApexCrea() {
        return this.usuarioApexCrea;
    }
    
    public void setUsuarioApexCrea(String usuarioApexCrea) {
        this.usuarioApexCrea = usuarioApexCrea;
    }

    
    @Column(name="USUARIO_APEX_ACTUALIZA", length=50)
    public String getUsuarioApexActualiza() {
        return this.usuarioApexActualiza;
    }
    
    public void setUsuarioApexActualiza(String usuarioApexActualiza) {
        this.usuarioApexActualiza = usuarioApexActualiza;
    }

    
    @Column(name="DO_CORREO_PERSONAL", length=80)
    public String getDoCorreoPersonal() {
        return this.doCorreoPersonal;
    }
    
    public void setDoCorreoPersonal(String doCorreoPersonal) {
        this.doCorreoPersonal = doCorreoPersonal;
    }

    
    @Column(name="DO_ES_ADMINISTRATIVO", length=1)
    public String getDoEsAdministrativo() {
        return this.doEsAdministrativo;
    }
    
    public void setDoEsAdministrativo(String doEsAdministrativo) {
        this.doEsAdministrativo = doEsAdministrativo;
    }

    
    @Column(name="DO_ID_TIPO_SANGRE", precision=22, scale=0)
    public BigDecimal getDoIdTipoSangre() {
        return this.doIdTipoSangre;
    }
    
    public void setDoIdTipoSangre(BigDecimal doIdTipoSangre) {
        this.doIdTipoSangre = doIdTipoSangre;
    }

    
    @Column(name="DO_EQU_ID_RR_HH", precision=22, scale=0)
    public BigDecimal getDoEquIdRrHh() {
        return this.doEquIdRrHh;
    }
    
    public void setDoEquIdRrHh(BigDecimal doEquIdRrHh) {
        this.doEquIdRrHh = doEquIdRrHh;
    }

    
    @Column(name="DO_IDENTIFICACION_NOMINA", length=25)
    public String getDoIdentificacionNomina() {
        return this.doIdentificacionNomina;
    }
    
    public void setDoIdentificacionNomina(String doIdentificacionNomina) {
        this.doIdentificacionNomina = doIdentificacionNomina;
    }

    
    @Column(name="DO_REPETIDO_NSGA", length=1)
    public String getDoRepetidoNsga() {
        return this.doRepetidoNsga;
    }
    
    public void setDoRepetidoNsga(String doRepetidoNsga) {
        this.doRepetidoNsga = doRepetidoNsga;
    }

    
    @Column(name="DO_OBSERVACIONES_REPETIDO", length=100)
    public String getDoObservacionesRepetido() {
        return this.doObservacionesRepetido;
    }
    
    public void setDoObservacionesRepetido(String doObservacionesRepetido) {
        this.doObservacionesRepetido = doObservacionesRepetido;
    }

    
    @Column(name="DO_EQUI_ID_NOMINA", precision=22, scale=0)
    public BigDecimal getDoEquiIdNomina() {
        return this.doEquiIdNomina;
    }
    
    public void setDoEquiIdNomina(BigDecimal doEquiIdNomina) {
        this.doEquiIdNomina = doEquiIdNomina;
    }

    
    @Column(name="DO_EQUI_ID_REGISTRO", precision=22, scale=0)
    public BigDecimal getDoEquiIdRegistro() {
        return this.doEquiIdRegistro;
    }
    
    public void setDoEquiIdRegistro(BigDecimal doEquiIdRegistro) {
        this.doEquiIdRegistro = doEquiIdRegistro;
    }

    
    @Column(name="DO_CANTON_NACIMIENTO", precision=22, scale=0)
    public BigDecimal getDoCantonNacimiento() {
        return this.doCantonNacimiento;
    }
    
    public void setDoCantonNacimiento(BigDecimal doCantonNacimiento) {
        this.doCantonNacimiento = doCantonNacimiento;
    }

    
    @Column(name="DO_PROVINCIA_NACIMIENTO", precision=22, scale=0)
    public BigDecimal getDoProvinciaNacimiento() {
        return this.doProvinciaNacimiento;
    }
    
    public void setDoProvinciaNacimiento(BigDecimal doProvinciaNacimiento) {
        this.doProvinciaNacimiento = doProvinciaNacimiento;
    }

    
    @Column(name="DO_TIPO_DISCAPACIDAD", precision=22, scale=0)
    public BigDecimal getDoTipoDiscapacidad() {
        return this.doTipoDiscapacidad;
    }
    
    public void setDoTipoDiscapacidad(BigDecimal doTipoDiscapacidad) {
        this.doTipoDiscapacidad = doTipoDiscapacidad;
    }

    
    @Column(name="DO_PORCENTAJE_DISCAPACIDAD", precision=22, scale=0)
    public BigDecimal getDoPorcentajeDiscapacidad() {
        return this.doPorcentajeDiscapacidad;
    }
    
    public void setDoPorcentajeDiscapacidad(BigDecimal doPorcentajeDiscapacidad) {
        this.doPorcentajeDiscapacidad = doPorcentajeDiscapacidad;
    }

    
    @Column(name="DO_NUMERO_CARNET_CONADIS", length=25)
    public String getDoNumeroCarnetConadis() {
        return this.doNumeroCarnetConadis;
    }
    
    public void setDoNumeroCarnetConadis(String doNumeroCarnetConadis) {
        this.doNumeroCarnetConadis = doNumeroCarnetConadis;
    }

    
    @Column(name="DO_OBSERVACION", length=250)
    public String getDoObservacion() {
        return this.doObservacion;
    }
    
    public void setDoObservacion(String doObservacion) {
        this.doObservacion = doObservacion;
    }

    
    @Column(name="DO_IDENTIFICACION_NSGA", length=15)
    public String getDoIdentificacionNsga() {
        return this.doIdentificacionNsga;
    }
    
    public void setDoIdentificacionNsga(String doIdentificacionNsga) {
        this.doIdentificacionNsga = doIdentificacionNsga;
    }

    
    @Column(name="DO_FOTO")
    public Blob getDoFoto() {
        return this.doFoto;
    }
    
    public void setDoFoto(Blob doFoto) {
        this.doFoto = doFoto;
    }

    
    @Column(name="DO_FOTO_MIMETYPE")
    public String getDoFotoMimetype() {
        return this.doFotoMimetype;
    }
    
    public void setDoFotoMimetype(String doFotoMimetype) {
        this.doFotoMimetype = doFotoMimetype;
    }

    
    @Column(name="DO_FOTO_FILENAME")
    public String getDoFotoFilename() {
        return this.doFotoFilename;
    }
    
    public void setDoFotoFilename(String doFotoFilename) {
        this.doFotoFilename = doFotoFilename;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FOTO_LAST_UPDATE", length=7)
    public Date getDoFotoLastUpdate() {
        return this.doFotoLastUpdate;
    }
    
    public void setDoFotoLastUpdate(Date doFotoLastUpdate) {
        this.doFotoLastUpdate = doFotoLastUpdate;
    }

    
    @Column(name="DO_EQU_ID_NSGA3", precision=22, scale=0)
    public BigDecimal getDoEquIdNsga3() {
        return this.doEquIdNsga3;
    }
    
    public void setDoEquIdNsga3(BigDecimal doEquIdNsga3) {
        this.doEquIdNsga3 = doEquIdNsga3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FECHA_INICIO_ADENDA", length=7)
    public Date getDoFechaInicioAdenda() {
        return this.doFechaInicioAdenda;
    }
    
    public void setDoFechaInicioAdenda(Date doFechaInicioAdenda) {
        this.doFechaInicioAdenda = doFechaInicioAdenda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FECHA_FIN_ADENDA", length=7)
    public Date getDoFechaFinAdenda() {
        return this.doFechaFinAdenda;
    }
    
    public void setDoFechaFinAdenda(Date doFechaFinAdenda) {
        this.doFechaFinAdenda = doFechaFinAdenda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DO_FECHA_VALIDACION_RRHH", length=7)
    public Date getDoFechaValidacionRrhh() {
        return this.doFechaValidacionRrhh;
    }
    
    public void setDoFechaValidacionRrhh(Date doFechaValidacionRrhh) {
        this.doFechaValidacionRrhh = doFechaValidacionRrhh;
    }

    
    @Column(name="DO_ESTADO_CIVIL", precision=22, scale=0)
    public BigDecimal getDoEstadoCivil() {
        return this.doEstadoCivil;
    }
    
    public void setDoEstadoCivil(BigDecimal doEstadoCivil) {
        this.doEstadoCivil = doEstadoCivil;
    }

    
    @Column(name="DO_CONTRATO_INDEFINIDO", length=1)
    public Character getDoContratoIndefinido() {
        return this.doContratoIndefinido;
    }
    
    public void setDoContratoIndefinido(Character doContratoIndefinido) {
        this.doContratoIndefinido = doContratoIndefinido;
    }

    
    @Column(name="DO_ESTADO_NOMINA", length=1)
    public Character getDoEstadoNomina() {
        return this.doEstadoNomina;
    }
    
    public void setDoEstadoNomina(Character doEstadoNomina) {
        this.doEstadoNomina = doEstadoNomina;
    }

    
    @Column(name="DO_ESTADO_RRHH", length=1)
    public Character getDoEstadoRrhh() {
        return this.doEstadoRrhh;
    }
    
    public void setDoEstadoRrhh(Character doEstadoRrhh) {
        this.doEstadoRrhh = doEstadoRrhh;
    }

    
    @Column(name="DO_CODIGO_UTPL", length=100)
    public String getDoCodigoUtpl() {
        return this.doCodigoUtpl;
    }
    
    public void setDoCodigoUtpl(String doCodigoUtpl) {
        this.doCodigoUtpl = doCodigoUtpl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDocente")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDocente")
    public Set<TdiOfertaDocentesNsga> getTdiOfertaDocentesNsgas() {
        return this.tdiOfertaDocentesNsgas;
    }
    
    public void setTdiOfertaDocentesNsgas(Set<TdiOfertaDocentesNsga> tdiOfertaDocentesNsgas) {
        this.tdiOfertaDocentesNsgas = tdiOfertaDocentesNsgas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDocente")
    public Set<TheActividadesEvaAvance> getTheActividadesEvaAvances() {
        return this.theActividadesEvaAvances;
    }
    
    public void setTheActividadesEvaAvances(Set<TheActividadesEvaAvance> theActividadesEvaAvances) {
        this.theActividadesEvaAvances = theActividadesEvaAvances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDocente")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiDocente")
    public Set<TevaMicrovideos> getTevaMicrovideoses() {
        return this.tevaMicrovideoses;
    }
    
    public void setTevaMicrovideoses(Set<TevaMicrovideos> tevaMicrovideoses) {
        this.tevaMicrovideoses = tevaMicrovideoses;
    }




}


