package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiExcepciones generated by hbm2java
 */
@Entity
@Table(name="TDI_EXCEPCIONES"
    ,schema="ESQ_SIEC"
)
public class TdiExcepciones  implements java.io.Serializable {


     private BigDecimal texId;
     private String texCodigoCe;
     private BigDecimal onsId;
     private BigDecimal texIdCursoEva;
     private String texTipo;
     private String texNombre;
     private String texDescripcion;
     private String texProceso;
     private BigDecimal texParalelo;
     private Character texVigencia;
     private Date texFechaCreacion;
     private String texUsuarioCrea;
     private Date texFechaActualizacion;
     private String texUsuarioActualiza;
     private BigDecimal doId;
     private BigDecimal peId;
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);

    public TdiExcepciones() {
    }

	
    public TdiExcepciones(BigDecimal texId) {
        this.texId = texId;
    }
    public TdiExcepciones(BigDecimal texId, String texCodigoCe, BigDecimal onsId, BigDecimal texIdCursoEva, String texTipo, String texNombre, String texDescripcion, String texProceso, BigDecimal texParalelo, Character texVigencia, Date texFechaCreacion, String texUsuarioCrea, Date texFechaActualizacion, String texUsuarioActualiza, BigDecimal doId, BigDecimal peId, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
       this.texId = texId;
       this.texCodigoCe = texCodigoCe;
       this.onsId = onsId;
       this.texIdCursoEva = texIdCursoEva;
       this.texTipo = texTipo;
       this.texNombre = texNombre;
       this.texDescripcion = texDescripcion;
       this.texProceso = texProceso;
       this.texParalelo = texParalelo;
       this.texVigencia = texVigencia;
       this.texFechaCreacion = texFechaCreacion;
       this.texUsuarioCrea = texUsuarioCrea;
       this.texFechaActualizacion = texFechaActualizacion;
       this.texUsuarioActualiza = texUsuarioActualiza;
       this.doId = doId;
       this.peId = peId;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }
   
     @Id 

    
    @Column(name="TEX_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getTexId() {
        return this.texId;
    }
    
    public void setTexId(BigDecimal texId) {
        this.texId = texId;
    }

    
    @Column(name="TEX_CODIGO_CE", length=25)
    public String getTexCodigoCe() {
        return this.texCodigoCe;
    }
    
    public void setTexCodigoCe(String texCodigoCe) {
        this.texCodigoCe = texCodigoCe;
    }

    
    @Column(name="ONS_ID", precision=22, scale=0)
    public BigDecimal getOnsId() {
        return this.onsId;
    }
    
    public void setOnsId(BigDecimal onsId) {
        this.onsId = onsId;
    }

    
    @Column(name="TEX_ID_CURSO_EVA", precision=22, scale=0)
    public BigDecimal getTexIdCursoEva() {
        return this.texIdCursoEva;
    }
    
    public void setTexIdCursoEva(BigDecimal texIdCursoEva) {
        this.texIdCursoEva = texIdCursoEva;
    }

    
    @Column(name="TEX_TIPO", length=100)
    public String getTexTipo() {
        return this.texTipo;
    }
    
    public void setTexTipo(String texTipo) {
        this.texTipo = texTipo;
    }

    
    @Column(name="TEX_NOMBRE", length=250)
    public String getTexNombre() {
        return this.texNombre;
    }
    
    public void setTexNombre(String texNombre) {
        this.texNombre = texNombre;
    }

    
    @Column(name="TEX_DESCRIPCION", length=250)
    public String getTexDescripcion() {
        return this.texDescripcion;
    }
    
    public void setTexDescripcion(String texDescripcion) {
        this.texDescripcion = texDescripcion;
    }

    
    @Column(name="TEX_PROCESO", length=250)
    public String getTexProceso() {
        return this.texProceso;
    }
    
    public void setTexProceso(String texProceso) {
        this.texProceso = texProceso;
    }

    
    @Column(name="TEX_PARALELO", precision=22, scale=0)
    public BigDecimal getTexParalelo() {
        return this.texParalelo;
    }
    
    public void setTexParalelo(BigDecimal texParalelo) {
        this.texParalelo = texParalelo;
    }

    
    @Column(name="TEX_VIGENCIA", length=1)
    public Character getTexVigencia() {
        return this.texVigencia;
    }
    
    public void setTexVigencia(Character texVigencia) {
        this.texVigencia = texVigencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TEX_FECHA_CREACION", length=7)
    public Date getTexFechaCreacion() {
        return this.texFechaCreacion;
    }
    
    public void setTexFechaCreacion(Date texFechaCreacion) {
        this.texFechaCreacion = texFechaCreacion;
    }

    
    @Column(name="TEX_USUARIO_CREA", length=100)
    public String getTexUsuarioCrea() {
        return this.texUsuarioCrea;
    }
    
    public void setTexUsuarioCrea(String texUsuarioCrea) {
        this.texUsuarioCrea = texUsuarioCrea;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TEX_FECHA_ACTUALIZACION", length=7)
    public Date getTexFechaActualizacion() {
        return this.texFechaActualizacion;
    }
    
    public void setTexFechaActualizacion(Date texFechaActualizacion) {
        this.texFechaActualizacion = texFechaActualizacion;
    }

    
    @Column(name="TEX_USUARIO_ACTUALIZA", length=100)
    public String getTexUsuarioActualiza() {
        return this.texUsuarioActualiza;
    }
    
    public void setTexUsuarioActualiza(String texUsuarioActualiza) {
        this.texUsuarioActualiza = texUsuarioActualiza;
    }

    
    @Column(name="DO_ID", precision=22, scale=0)
    public BigDecimal getDoId() {
        return this.doId;
    }
    
    public void setDoId(BigDecimal doId) {
        this.doId = doId;
    }

    
    @Column(name="PE_ID", precision=22, scale=0)
    public BigDecimal getPeId() {
        return this.peId;
    }
    
    public void setPeId(BigDecimal peId) {
        this.peId = peId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiExcepciones")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }




}


