package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiIndicador generated by hbm2java
 */
@Entity
@Table(name="TDI_INDICADOR"
    ,schema="ESQ_SIEC"
)
public class TdiIndicador  implements java.io.Serializable {


     private BigDecimal idId;
     private TdiCriteriosEvaluacion tdiCriteriosEvaluacion;
     private String idNombre;
     private String idDescripcion;
     private Date idFechaInicio;
     private Date idFechaFin;
     private String idVigencia;
     private String idFormulaGeneral;
     private String idObjetivo;
     private String idObservacionesGenerales;
     private String idCuantitativo;
     private BigDecimal idPeso;
     private String idFrecuencia;
     private String idNumeracion;
     private BigDecimal idPadre;
     private BigDecimal idOrdenGrupo;
     private String idNombreValorCumplimiento;
     private String idNombreValorNoCumplimient;
     private String idNombreValorProgramado;
     private BigDecimal scvId1;
     private BigDecimal scvId2;
     private BigDecimal idEstadoFase1Analisis;
     private BigDecimal idEstadoFase2BaseDatos;
     private BigDecimal idEstadoFase3Visualizacion;
     private BigDecimal idEstadoFase4Validacion;
     private Date idFechaCreacion;
     private String usuarioCreaApex;
     private Date idFechaUltAct;
     private String usuarioUltActApex;
     private String idGenerarAreaDocente;
     private String idGenerarDepDocente;
     private String idGenerarSeccionDocente;
     private String idGenerarAreaComponente;
     private String idGenerarDepComponente;
     private String idGenerarSeccionComponente;
     private String idGenerarAreaTitulacion;
     private String idGenerarTitulacion;
     private String idGenerarComponente;
     private String idCodigo;
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);
     private Set<TdiParametrosIndicador> tdiParametrosIndicadors = new HashSet<TdiParametrosIndicador>(0);
     private Set<TdiRangosSemaforo> tdiRangosSemaforos = new HashSet<TdiRangosSemaforo>(0);
     private Set<TevaMicrovideos> tevaMicrovideoses = new HashSet<TevaMicrovideos>(0);
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);

    public TdiIndicador() {
    }

	
    public TdiIndicador(BigDecimal idId, String idNombre, Date idFechaInicio, String idVigencia, String idCuantitativo) {
        this.idId = idId;
        this.idNombre = idNombre;
        this.idFechaInicio = idFechaInicio;
        this.idVigencia = idVigencia;
        this.idCuantitativo = idCuantitativo;
    }
    public TdiIndicador(BigDecimal idId, TdiCriteriosEvaluacion tdiCriteriosEvaluacion, String idNombre, String idDescripcion, Date idFechaInicio, Date idFechaFin, String idVigencia, String idFormulaGeneral, String idObjetivo, String idObservacionesGenerales, String idCuantitativo, BigDecimal idPeso, String idFrecuencia, String idNumeracion, BigDecimal idPadre, BigDecimal idOrdenGrupo, String idNombreValorCumplimiento, String idNombreValorNoCumplimient, String idNombreValorProgramado, BigDecimal scvId1, BigDecimal scvId2, BigDecimal idEstadoFase1Analisis, BigDecimal idEstadoFase2BaseDatos, BigDecimal idEstadoFase3Visualizacion, BigDecimal idEstadoFase4Validacion, Date idFechaCreacion, String usuarioCreaApex, Date idFechaUltAct, String usuarioUltActApex, String idGenerarAreaDocente, String idGenerarDepDocente, String idGenerarSeccionDocente, String idGenerarAreaComponente, String idGenerarDepComponente, String idGenerarSeccionComponente, String idGenerarAreaTitulacion, String idGenerarTitulacion, String idGenerarComponente, String idCodigo, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TdiParametrosIndicador> tdiParametrosIndicadors, Set<TdiRangosSemaforo> tdiRangosSemaforos, Set<TevaMicrovideos> tevaMicrovideoses, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
       this.idId = idId;
       this.tdiCriteriosEvaluacion = tdiCriteriosEvaluacion;
       this.idNombre = idNombre;
       this.idDescripcion = idDescripcion;
       this.idFechaInicio = idFechaInicio;
       this.idFechaFin = idFechaFin;
       this.idVigencia = idVigencia;
       this.idFormulaGeneral = idFormulaGeneral;
       this.idObjetivo = idObjetivo;
       this.idObservacionesGenerales = idObservacionesGenerales;
       this.idCuantitativo = idCuantitativo;
       this.idPeso = idPeso;
       this.idFrecuencia = idFrecuencia;
       this.idNumeracion = idNumeracion;
       this.idPadre = idPadre;
       this.idOrdenGrupo = idOrdenGrupo;
       this.idNombreValorCumplimiento = idNombreValorCumplimiento;
       this.idNombreValorNoCumplimient = idNombreValorNoCumplimient;
       this.idNombreValorProgramado = idNombreValorProgramado;
       this.scvId1 = scvId1;
       this.scvId2 = scvId2;
       this.idEstadoFase1Analisis = idEstadoFase1Analisis;
       this.idEstadoFase2BaseDatos = idEstadoFase2BaseDatos;
       this.idEstadoFase3Visualizacion = idEstadoFase3Visualizacion;
       this.idEstadoFase4Validacion = idEstadoFase4Validacion;
       this.idFechaCreacion = idFechaCreacion;
       this.usuarioCreaApex = usuarioCreaApex;
       this.idFechaUltAct = idFechaUltAct;
       this.usuarioUltActApex = usuarioUltActApex;
       this.idGenerarAreaDocente = idGenerarAreaDocente;
       this.idGenerarDepDocente = idGenerarDepDocente;
       this.idGenerarSeccionDocente = idGenerarSeccionDocente;
       this.idGenerarAreaComponente = idGenerarAreaComponente;
       this.idGenerarDepComponente = idGenerarDepComponente;
       this.idGenerarSeccionComponente = idGenerarSeccionComponente;
       this.idGenerarAreaTitulacion = idGenerarAreaTitulacion;
       this.idGenerarTitulacion = idGenerarTitulacion;
       this.idGenerarComponente = idGenerarComponente;
       this.idCodigo = idCodigo;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.tdiParametrosIndicadors = tdiParametrosIndicadors;
       this.tdiRangosSemaforos = tdiRangosSemaforos;
       this.tevaMicrovideoses = tevaMicrovideoses;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }
   
     @Id 

    
    @Column(name="ID_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdId() {
        return this.idId;
    }
    
    public void setIdId(BigDecimal idId) {
        this.idId = idId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CV_ID")
    public TdiCriteriosEvaluacion getTdiCriteriosEvaluacion() {
        return this.tdiCriteriosEvaluacion;
    }
    
    public void setTdiCriteriosEvaluacion(TdiCriteriosEvaluacion tdiCriteriosEvaluacion) {
        this.tdiCriteriosEvaluacion = tdiCriteriosEvaluacion;
    }

    
    @Column(name="ID_NOMBRE", nullable=false, length=100)
    public String getIdNombre() {
        return this.idNombre;
    }
    
    public void setIdNombre(String idNombre) {
        this.idNombre = idNombre;
    }

    
    @Column(name="ID_DESCRIPCION", length=4000)
    public String getIdDescripcion() {
        return this.idDescripcion;
    }
    
    public void setIdDescripcion(String idDescripcion) {
        this.idDescripcion = idDescripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ID_FECHA_INICIO", nullable=false, length=7)
    public Date getIdFechaInicio() {
        return this.idFechaInicio;
    }
    
    public void setIdFechaInicio(Date idFechaInicio) {
        this.idFechaInicio = idFechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ID_FECHA_FIN", length=7)
    public Date getIdFechaFin() {
        return this.idFechaFin;
    }
    
    public void setIdFechaFin(Date idFechaFin) {
        this.idFechaFin = idFechaFin;
    }

    
    @Column(name="ID_VIGENCIA", nullable=false, length=1)
    public String getIdVigencia() {
        return this.idVigencia;
    }
    
    public void setIdVigencia(String idVigencia) {
        this.idVigencia = idVigencia;
    }

    
    @Column(name="ID_FORMULA_GENERAL", length=4000)
    public String getIdFormulaGeneral() {
        return this.idFormulaGeneral;
    }
    
    public void setIdFormulaGeneral(String idFormulaGeneral) {
        this.idFormulaGeneral = idFormulaGeneral;
    }

    
    @Column(name="ID_OBJETIVO", length=4000)
    public String getIdObjetivo() {
        return this.idObjetivo;
    }
    
    public void setIdObjetivo(String idObjetivo) {
        this.idObjetivo = idObjetivo;
    }

    
    @Column(name="ID_OBSERVACIONES_GENERALES", length=4000)
    public String getIdObservacionesGenerales() {
        return this.idObservacionesGenerales;
    }
    
    public void setIdObservacionesGenerales(String idObservacionesGenerales) {
        this.idObservacionesGenerales = idObservacionesGenerales;
    }

    
    @Column(name="ID_CUANTITATIVO", nullable=false, length=1)
    public String getIdCuantitativo() {
        return this.idCuantitativo;
    }
    
    public void setIdCuantitativo(String idCuantitativo) {
        this.idCuantitativo = idCuantitativo;
    }

    
    @Column(name="ID_PESO", precision=22, scale=0)
    public BigDecimal getIdPeso() {
        return this.idPeso;
    }
    
    public void setIdPeso(BigDecimal idPeso) {
        this.idPeso = idPeso;
    }

    
    @Column(name="ID_FRECUENCIA", length=20)
    public String getIdFrecuencia() {
        return this.idFrecuencia;
    }
    
    public void setIdFrecuencia(String idFrecuencia) {
        this.idFrecuencia = idFrecuencia;
    }

    
    @Column(name="ID_NUMERACION", length=10)
    public String getIdNumeracion() {
        return this.idNumeracion;
    }
    
    public void setIdNumeracion(String idNumeracion) {
        this.idNumeracion = idNumeracion;
    }

    
    @Column(name="ID_PADRE", precision=22, scale=0)
    public BigDecimal getIdPadre() {
        return this.idPadre;
    }
    
    public void setIdPadre(BigDecimal idPadre) {
        this.idPadre = idPadre;
    }

    
    @Column(name="ID_ORDEN_GRUPO", precision=22, scale=0)
    public BigDecimal getIdOrdenGrupo() {
        return this.idOrdenGrupo;
    }
    
    public void setIdOrdenGrupo(BigDecimal idOrdenGrupo) {
        this.idOrdenGrupo = idOrdenGrupo;
    }

    
    @Column(name="ID_NOMBRE_VALOR_CUMPLIMIENTO", length=100)
    public String getIdNombreValorCumplimiento() {
        return this.idNombreValorCumplimiento;
    }
    
    public void setIdNombreValorCumplimiento(String idNombreValorCumplimiento) {
        this.idNombreValorCumplimiento = idNombreValorCumplimiento;
    }

    
    @Column(name="ID_NOMBRE_VALOR_NO_CUMPLIMIENT", length=100)
    public String getIdNombreValorNoCumplimient() {
        return this.idNombreValorNoCumplimient;
    }
    
    public void setIdNombreValorNoCumplimient(String idNombreValorNoCumplimient) {
        this.idNombreValorNoCumplimient = idNombreValorNoCumplimient;
    }

    
    @Column(name="ID_NOMBRE_VALOR_PROGRAMADO", length=100)
    public String getIdNombreValorProgramado() {
        return this.idNombreValorProgramado;
    }
    
    public void setIdNombreValorProgramado(String idNombreValorProgramado) {
        this.idNombreValorProgramado = idNombreValorProgramado;
    }

    
    @Column(name="SCV_ID_1", precision=22, scale=0)
    public BigDecimal getScvId1() {
        return this.scvId1;
    }
    
    public void setScvId1(BigDecimal scvId1) {
        this.scvId1 = scvId1;
    }

    
    @Column(name="SCV_ID_2", precision=22, scale=0)
    public BigDecimal getScvId2() {
        return this.scvId2;
    }
    
    public void setScvId2(BigDecimal scvId2) {
        this.scvId2 = scvId2;
    }

    
    @Column(name="ID_ESTADO_FASE1_ANALISIS", precision=22, scale=0)
    public BigDecimal getIdEstadoFase1Analisis() {
        return this.idEstadoFase1Analisis;
    }
    
    public void setIdEstadoFase1Analisis(BigDecimal idEstadoFase1Analisis) {
        this.idEstadoFase1Analisis = idEstadoFase1Analisis;
    }

    
    @Column(name="ID_ESTADO_FASE2_BASE_DATOS", precision=22, scale=0)
    public BigDecimal getIdEstadoFase2BaseDatos() {
        return this.idEstadoFase2BaseDatos;
    }
    
    public void setIdEstadoFase2BaseDatos(BigDecimal idEstadoFase2BaseDatos) {
        this.idEstadoFase2BaseDatos = idEstadoFase2BaseDatos;
    }

    
    @Column(name="ID_ESTADO_FASE3_VISUALIZACION", precision=22, scale=0)
    public BigDecimal getIdEstadoFase3Visualizacion() {
        return this.idEstadoFase3Visualizacion;
    }
    
    public void setIdEstadoFase3Visualizacion(BigDecimal idEstadoFase3Visualizacion) {
        this.idEstadoFase3Visualizacion = idEstadoFase3Visualizacion;
    }

    
    @Column(name="ID_ESTADO_FASE4_VALIDACION", precision=22, scale=0)
    public BigDecimal getIdEstadoFase4Validacion() {
        return this.idEstadoFase4Validacion;
    }
    
    public void setIdEstadoFase4Validacion(BigDecimal idEstadoFase4Validacion) {
        this.idEstadoFase4Validacion = idEstadoFase4Validacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ID_FECHA_CREACION", length=7)
    public Date getIdFechaCreacion() {
        return this.idFechaCreacion;
    }
    
    public void setIdFechaCreacion(Date idFechaCreacion) {
        this.idFechaCreacion = idFechaCreacion;
    }

    
    @Column(name="USUARIO_CREA_APEX", length=50)
    public String getUsuarioCreaApex() {
        return this.usuarioCreaApex;
    }
    
    public void setUsuarioCreaApex(String usuarioCreaApex) {
        this.usuarioCreaApex = usuarioCreaApex;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ID_FECHA_ULT_ACT", length=7)
    public Date getIdFechaUltAct() {
        return this.idFechaUltAct;
    }
    
    public void setIdFechaUltAct(Date idFechaUltAct) {
        this.idFechaUltAct = idFechaUltAct;
    }

    
    @Column(name="USUARIO_ULT_ACT_APEX", length=50)
    public String getUsuarioUltActApex() {
        return this.usuarioUltActApex;
    }
    
    public void setUsuarioUltActApex(String usuarioUltActApex) {
        this.usuarioUltActApex = usuarioUltActApex;
    }

    
    @Column(name="ID_GENERAR_AREA_DOCENTE", length=1)
    public String getIdGenerarAreaDocente() {
        return this.idGenerarAreaDocente;
    }
    
    public void setIdGenerarAreaDocente(String idGenerarAreaDocente) {
        this.idGenerarAreaDocente = idGenerarAreaDocente;
    }

    
    @Column(name="ID_GENERAR_DEP_DOCENTE", length=1)
    public String getIdGenerarDepDocente() {
        return this.idGenerarDepDocente;
    }
    
    public void setIdGenerarDepDocente(String idGenerarDepDocente) {
        this.idGenerarDepDocente = idGenerarDepDocente;
    }

    
    @Column(name="ID_GENERAR_SECCION_DOCENTE", length=1)
    public String getIdGenerarSeccionDocente() {
        return this.idGenerarSeccionDocente;
    }
    
    public void setIdGenerarSeccionDocente(String idGenerarSeccionDocente) {
        this.idGenerarSeccionDocente = idGenerarSeccionDocente;
    }

    
    @Column(name="ID_GENERAR_AREA_COMPONENTE", length=1)
    public String getIdGenerarAreaComponente() {
        return this.idGenerarAreaComponente;
    }
    
    public void setIdGenerarAreaComponente(String idGenerarAreaComponente) {
        this.idGenerarAreaComponente = idGenerarAreaComponente;
    }

    
    @Column(name="ID_GENERAR_DEP_COMPONENTE", length=1)
    public String getIdGenerarDepComponente() {
        return this.idGenerarDepComponente;
    }
    
    public void setIdGenerarDepComponente(String idGenerarDepComponente) {
        this.idGenerarDepComponente = idGenerarDepComponente;
    }

    
    @Column(name="ID_GENERAR_SECCION_COMPONENTE", length=1)
    public String getIdGenerarSeccionComponente() {
        return this.idGenerarSeccionComponente;
    }
    
    public void setIdGenerarSeccionComponente(String idGenerarSeccionComponente) {
        this.idGenerarSeccionComponente = idGenerarSeccionComponente;
    }

    
    @Column(name="ID_GENERAR_AREA_TITULACION", length=1)
    public String getIdGenerarAreaTitulacion() {
        return this.idGenerarAreaTitulacion;
    }
    
    public void setIdGenerarAreaTitulacion(String idGenerarAreaTitulacion) {
        this.idGenerarAreaTitulacion = idGenerarAreaTitulacion;
    }

    
    @Column(name="ID_GENERAR_TITULACION", length=1)
    public String getIdGenerarTitulacion() {
        return this.idGenerarTitulacion;
    }
    
    public void setIdGenerarTitulacion(String idGenerarTitulacion) {
        this.idGenerarTitulacion = idGenerarTitulacion;
    }

    
    @Column(name="ID_GENERAR_COMPONENTE", length=1)
    public String getIdGenerarComponente() {
        return this.idGenerarComponente;
    }
    
    public void setIdGenerarComponente(String idGenerarComponente) {
        this.idGenerarComponente = idGenerarComponente;
    }

    
    @Column(name="ID_CODIGO", length=30)
    public String getIdCodigo() {
        return this.idCodigo;
    }
    
    public void setIdCodigo(String idCodigo) {
        this.idCodigo = idCodigo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiIndicador")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiIndicador")
    public Set<TdiParametrosIndicador> getTdiParametrosIndicadors() {
        return this.tdiParametrosIndicadors;
    }
    
    public void setTdiParametrosIndicadors(Set<TdiParametrosIndicador> tdiParametrosIndicadors) {
        this.tdiParametrosIndicadors = tdiParametrosIndicadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiIndicador")
    public Set<TdiRangosSemaforo> getTdiRangosSemaforos() {
        return this.tdiRangosSemaforos;
    }
    
    public void setTdiRangosSemaforos(Set<TdiRangosSemaforo> tdiRangosSemaforos) {
        this.tdiRangosSemaforos = tdiRangosSemaforos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiIndicador")
    public Set<TevaMicrovideos> getTevaMicrovideoses() {
        return this.tevaMicrovideoses;
    }
    
    public void setTevaMicrovideoses(Set<TevaMicrovideos> tevaMicrovideoses) {
        this.tevaMicrovideoses = tevaMicrovideoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiIndicador")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }




}


