package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiNivelAcademico generated by hbm2java
 */
@Entity
@Table(name="TDI_NIVEL_ACADEMICO"
    ,schema="ESQ_SIEC"
)
public class TdiNivelAcademico  implements java.io.Serializable {


     private BigDecimal naId;
     private String naNombre;
     private BigDecimal naEquIdNsga;
     private String naEquNombreNsga;
     private BigDecimal naEquIdSga;
     private String naEquNombreSga;
     private BigDecimal naEquIdEva;
     private String naEquNombreEva;
     private Date naFechaCreacion;
     private Date naFechaActualizacion;
     private String naVigencia;
     private String naDefinicion;
     private BigDecimal naEquIdEc;
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);
     private Set<TheActividadesEvaAvance> theActividadesEvaAvances = new HashSet<TheActividadesEvaAvance>(0);
     private Set<TdiPeriodoDetalle> tdiPeriodoDetalles = new HashSet<TdiPeriodoDetalle>(0);

    public TdiNivelAcademico() {
    }

	
    public TdiNivelAcademico(BigDecimal naId, String naNombre, Date naFechaCreacion, String naVigencia) {
        this.naId = naId;
        this.naNombre = naNombre;
        this.naFechaCreacion = naFechaCreacion;
        this.naVigencia = naVigencia;
    }
    public TdiNivelAcademico(BigDecimal naId, String naNombre, BigDecimal naEquIdNsga, String naEquNombreNsga, BigDecimal naEquIdSga, String naEquNombreSga, BigDecimal naEquIdEva, String naEquNombreEva, Date naFechaCreacion, Date naFechaActualizacion, String naVigencia, String naDefinicion, BigDecimal naEquIdEc, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets, Set<TheActividadesEvaAvance> theActividadesEvaAvances, Set<TdiPeriodoDetalle> tdiPeriodoDetalles) {
       this.naId = naId;
       this.naNombre = naNombre;
       this.naEquIdNsga = naEquIdNsga;
       this.naEquNombreNsga = naEquNombreNsga;
       this.naEquIdSga = naEquIdSga;
       this.naEquNombreSga = naEquNombreSga;
       this.naEquIdEva = naEquIdEva;
       this.naEquNombreEva = naEquNombreEva;
       this.naFechaCreacion = naFechaCreacion;
       this.naFechaActualizacion = naFechaActualizacion;
       this.naVigencia = naVigencia;
       this.naDefinicion = naDefinicion;
       this.naEquIdEc = naEquIdEc;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
       this.theActividadesEvaAvances = theActividadesEvaAvances;
       this.tdiPeriodoDetalles = tdiPeriodoDetalles;
    }
   
     @Id 

    
    @Column(name="NA_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getNaId() {
        return this.naId;
    }
    
    public void setNaId(BigDecimal naId) {
        this.naId = naId;
    }

    
    @Column(name="NA_NOMBRE", nullable=false, length=100)
    public String getNaNombre() {
        return this.naNombre;
    }
    
    public void setNaNombre(String naNombre) {
        this.naNombre = naNombre;
    }

    
    @Column(name="NA_EQU_ID_NSGA", precision=22, scale=0)
    public BigDecimal getNaEquIdNsga() {
        return this.naEquIdNsga;
    }
    
    public void setNaEquIdNsga(BigDecimal naEquIdNsga) {
        this.naEquIdNsga = naEquIdNsga;
    }

    
    @Column(name="NA_EQU_NOMBRE_NSGA", length=100)
    public String getNaEquNombreNsga() {
        return this.naEquNombreNsga;
    }
    
    public void setNaEquNombreNsga(String naEquNombreNsga) {
        this.naEquNombreNsga = naEquNombreNsga;
    }

    
    @Column(name="NA_EQU_ID_SGA", precision=22, scale=0)
    public BigDecimal getNaEquIdSga() {
        return this.naEquIdSga;
    }
    
    public void setNaEquIdSga(BigDecimal naEquIdSga) {
        this.naEquIdSga = naEquIdSga;
    }

    
    @Column(name="NA_EQU_NOMBRE_SGA", length=100)
    public String getNaEquNombreSga() {
        return this.naEquNombreSga;
    }
    
    public void setNaEquNombreSga(String naEquNombreSga) {
        this.naEquNombreSga = naEquNombreSga;
    }

    
    @Column(name="NA_EQU_ID_EVA", precision=22, scale=0)
    public BigDecimal getNaEquIdEva() {
        return this.naEquIdEva;
    }
    
    public void setNaEquIdEva(BigDecimal naEquIdEva) {
        this.naEquIdEva = naEquIdEva;
    }

    
    @Column(name="NA_EQU_NOMBRE_EVA", length=100)
    public String getNaEquNombreEva() {
        return this.naEquNombreEva;
    }
    
    public void setNaEquNombreEva(String naEquNombreEva) {
        this.naEquNombreEva = naEquNombreEva;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NA_FECHA_CREACION", nullable=false, length=7)
    public Date getNaFechaCreacion() {
        return this.naFechaCreacion;
    }
    
    public void setNaFechaCreacion(Date naFechaCreacion) {
        this.naFechaCreacion = naFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NA_FECHA_ACTUALIZACION", length=7)
    public Date getNaFechaActualizacion() {
        return this.naFechaActualizacion;
    }
    
    public void setNaFechaActualizacion(Date naFechaActualizacion) {
        this.naFechaActualizacion = naFechaActualizacion;
    }

    
    @Column(name="NA_VIGENCIA", nullable=false, length=1)
    public String getNaVigencia() {
        return this.naVigencia;
    }
    
    public void setNaVigencia(String naVigencia) {
        this.naVigencia = naVigencia;
    }

    
    @Column(name="NA_DEFINICION", length=500)
    public String getNaDefinicion() {
        return this.naDefinicion;
    }
    
    public void setNaDefinicion(String naDefinicion) {
        this.naDefinicion = naDefinicion;
    }

    
    @Column(name="NA_EQU_ID_EC", precision=22, scale=0)
    public BigDecimal getNaEquIdEc() {
        return this.naEquIdEc;
    }
    
    public void setNaEquIdEc(BigDecimal naEquIdEc) {
        this.naEquIdEc = naEquIdEc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiNivelAcademico")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiNivelAcademico")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiNivelAcademico")
    public Set<TheActividadesEvaAvance> getTheActividadesEvaAvances() {
        return this.theActividadesEvaAvances;
    }
    
    public void setTheActividadesEvaAvances(Set<TheActividadesEvaAvance> theActividadesEvaAvances) {
        this.theActividadesEvaAvances = theActividadesEvaAvances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiNivelAcademico")
    public Set<TdiPeriodoDetalle> getTdiPeriodoDetalles() {
        return this.tdiPeriodoDetalles;
    }
    
    public void setTdiPeriodoDetalles(Set<TdiPeriodoDetalle> tdiPeriodoDetalles) {
        this.tdiPeriodoDetalles = tdiPeriodoDetalles;
    }




}


