package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TdiObservacionPersonalizada generated by hbm2java
 */
@Entity
@Table(name="TDI_OBSERVACION_PERSONALIZADA"
    ,schema="ESQ_SIEC"
)
public class TdiObservacionPersonalizada  implements java.io.Serializable {


     private BigDecimal opeId;
     private String opeCodigo;
     private String opeDescripcion;
     private String opeVigente;
     private String opeMensaje;
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);

    public TdiObservacionPersonalizada() {
    }

	
    public TdiObservacionPersonalizada(BigDecimal opeId, String opeCodigo, String opeDescripcion, String opeVigente) {
        this.opeId = opeId;
        this.opeCodigo = opeCodigo;
        this.opeDescripcion = opeDescripcion;
        this.opeVigente = opeVigente;
    }
    public TdiObservacionPersonalizada(BigDecimal opeId, String opeCodigo, String opeDescripcion, String opeVigente, String opeMensaje, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
       this.opeId = opeId;
       this.opeCodigo = opeCodigo;
       this.opeDescripcion = opeDescripcion;
       this.opeVigente = opeVigente;
       this.opeMensaje = opeMensaje;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }
   
     @Id 

    
    @Column(name="OPE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getOpeId() {
        return this.opeId;
    }
    
    public void setOpeId(BigDecimal opeId) {
        this.opeId = opeId;
    }

    
    @Column(name="OPE_CODIGO", nullable=false, length=30)
    public String getOpeCodigo() {
        return this.opeCodigo;
    }
    
    public void setOpeCodigo(String opeCodigo) {
        this.opeCodigo = opeCodigo;
    }

    
    @Column(name="OPE_DESCRIPCION", nullable=false, length=300)
    public String getOpeDescripcion() {
        return this.opeDescripcion;
    }
    
    public void setOpeDescripcion(String opeDescripcion) {
        this.opeDescripcion = opeDescripcion;
    }

    
    @Column(name="OPE_VIGENTE", nullable=false, length=1)
    public String getOpeVigente() {
        return this.opeVigente;
    }
    
    public void setOpeVigente(String opeVigente) {
        this.opeVigente = opeVigente;
    }

    
    @Column(name="OPE_MENSAJE", length=100)
    public String getOpeMensaje() {
        return this.opeMensaje;
    }
    
    public void setOpeMensaje(String opeMensaje) {
        this.opeMensaje = opeMensaje;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiObservacionPersonalizada")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }




}


