package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiOfertaDocentesNsga generated by hbm2java
 */
@Entity
@Table(name="TDI_OFERTA_DOCENTES_NSGA"
    ,schema="ESQ_SIEC"
)
public class TdiOfertaDocentesNsga  implements java.io.Serializable {


     private BigDecimal odnId;
     private TdiOfertaNsga tdiOfertaNsga;
     private TdiDocente tdiDocente;
     private BigDecimal ofdIdNsga;
     private Date odnFechaRegistroSiec;
     private Date odnFechaUltActSiec;
     private String odnExistePreDistributivo;
     private String odnProcesoEtl;
     private String odnVigente;

    public TdiOfertaDocentesNsga() {
    }

	
    public TdiOfertaDocentesNsga(BigDecimal odnId, TdiOfertaNsga tdiOfertaNsga, TdiDocente tdiDocente, BigDecimal ofdIdNsga, Date odnFechaRegistroSiec) {
        this.odnId = odnId;
        this.tdiOfertaNsga = tdiOfertaNsga;
        this.tdiDocente = tdiDocente;
        this.ofdIdNsga = ofdIdNsga;
        this.odnFechaRegistroSiec = odnFechaRegistroSiec;
    }
    public TdiOfertaDocentesNsga(BigDecimal odnId, TdiOfertaNsga tdiOfertaNsga, TdiDocente tdiDocente, BigDecimal ofdIdNsga, Date odnFechaRegistroSiec, Date odnFechaUltActSiec, String odnExistePreDistributivo, String odnProcesoEtl, String odnVigente) {
       this.odnId = odnId;
       this.tdiOfertaNsga = tdiOfertaNsga;
       this.tdiDocente = tdiDocente;
       this.ofdIdNsga = ofdIdNsga;
       this.odnFechaRegistroSiec = odnFechaRegistroSiec;
       this.odnFechaUltActSiec = odnFechaUltActSiec;
       this.odnExistePreDistributivo = odnExistePreDistributivo;
       this.odnProcesoEtl = odnProcesoEtl;
       this.odnVigente = odnVigente;
    }
   
     @Id 

    
    @Column(name="ODN_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getOdnId() {
        return this.odnId;
    }
    
    public void setOdnId(BigDecimal odnId) {
        this.odnId = odnId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ONS_ID", nullable=false)
    public TdiOfertaNsga getTdiOfertaNsga() {
        return this.tdiOfertaNsga;
    }
    
    public void setTdiOfertaNsga(TdiOfertaNsga tdiOfertaNsga) {
        this.tdiOfertaNsga = tdiOfertaNsga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DO_ID", nullable=false)
    public TdiDocente getTdiDocente() {
        return this.tdiDocente;
    }
    
    public void setTdiDocente(TdiDocente tdiDocente) {
        this.tdiDocente = tdiDocente;
    }

    
    @Column(name="OFD_ID_NSGA", nullable=false, precision=22, scale=0)
    public BigDecimal getOfdIdNsga() {
        return this.ofdIdNsga;
    }
    
    public void setOfdIdNsga(BigDecimal ofdIdNsga) {
        this.ofdIdNsga = ofdIdNsga;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ODN_FECHA_REGISTRO_SIEC", nullable=false, length=7)
    public Date getOdnFechaRegistroSiec() {
        return this.odnFechaRegistroSiec;
    }
    
    public void setOdnFechaRegistroSiec(Date odnFechaRegistroSiec) {
        this.odnFechaRegistroSiec = odnFechaRegistroSiec;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ODN_FECHA_ULT_ACT_SIEC", length=7)
    public Date getOdnFechaUltActSiec() {
        return this.odnFechaUltActSiec;
    }
    
    public void setOdnFechaUltActSiec(Date odnFechaUltActSiec) {
        this.odnFechaUltActSiec = odnFechaUltActSiec;
    }

    
    @Column(name="ODN_EXISTE_PRE_DISTRIBUTIVO", length=1)
    public String getOdnExistePreDistributivo() {
        return this.odnExistePreDistributivo;
    }
    
    public void setOdnExistePreDistributivo(String odnExistePreDistributivo) {
        this.odnExistePreDistributivo = odnExistePreDistributivo;
    }

    
    @Column(name="ODN_PROCESO_ETL", length=50)
    public String getOdnProcesoEtl() {
        return this.odnProcesoEtl;
    }
    
    public void setOdnProcesoEtl(String odnProcesoEtl) {
        this.odnProcesoEtl = odnProcesoEtl;
    }

    
    @Column(name="ODN_VIGENTE", length=1)
    public String getOdnVigente() {
        return this.odnVigente;
    }
    
    public void setOdnVigente(String odnVigente) {
        this.odnVigente = odnVigente;
    }




}


