package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiPeriodoDetalle generated by hbm2java
 */
@Entity
@Table(name="TDI_PERIODO_DETALLE"
    ,schema="ESQ_SIEC"
)
public class TdiPeriodoDetalle  implements java.io.Serializable {


     private BigDecimal ptId;
     private TdiModalidad tdiModalidad;
     private TdiNivelAcademico tdiNivelAcademico;
     private TdiPeriodo tdiPeriodo;
     private TdsUsuario tdsUsuario;
     private String ptFrecuencia;
     private BigDecimal ptNumeracion;
     private Date ptFechaInicio;
     private Date ptFechaFin;
     private Date ptFechaCreacion;
     private Date ptFechaActualizacion;
     private String ptObservacion;
     private Set<TdiParametrosIndicador> tdiParametrosIndicadors = new HashSet<TdiParametrosIndicador>(0);
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);
     private Set<TheActividadesEvaAvance> theActividadesEvaAvances = new HashSet<TheActividadesEvaAvance>(0);

    public TdiPeriodoDetalle() {
    }

	
    public TdiPeriodoDetalle(BigDecimal ptId) {
        this.ptId = ptId;
    }
    public TdiPeriodoDetalle(BigDecimal ptId, TdiModalidad tdiModalidad, TdiNivelAcademico tdiNivelAcademico, TdiPeriodo tdiPeriodo, TdsUsuario tdsUsuario, String ptFrecuencia, BigDecimal ptNumeracion, Date ptFechaInicio, Date ptFechaFin, Date ptFechaCreacion, Date ptFechaActualizacion, String ptObservacion, Set<TdiParametrosIndicador> tdiParametrosIndicadors, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TheActividadesEvaAvance> theActividadesEvaAvances) {
       this.ptId = ptId;
       this.tdiModalidad = tdiModalidad;
       this.tdiNivelAcademico = tdiNivelAcademico;
       this.tdiPeriodo = tdiPeriodo;
       this.tdsUsuario = tdsUsuario;
       this.ptFrecuencia = ptFrecuencia;
       this.ptNumeracion = ptNumeracion;
       this.ptFechaInicio = ptFechaInicio;
       this.ptFechaFin = ptFechaFin;
       this.ptFechaCreacion = ptFechaCreacion;
       this.ptFechaActualizacion = ptFechaActualizacion;
       this.ptObservacion = ptObservacion;
       this.tdiParametrosIndicadors = tdiParametrosIndicadors;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.theActividadesEvaAvances = theActividadesEvaAvances;
    }
   
     @Id 

    
    @Column(name="PT_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPtId() {
        return this.ptId;
    }
    
    public void setPtId(BigDecimal ptId) {
        this.ptId = ptId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MO_ID")
    public TdiModalidad getTdiModalidad() {
        return this.tdiModalidad;
    }
    
    public void setTdiModalidad(TdiModalidad tdiModalidad) {
        this.tdiModalidad = tdiModalidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NA_ID")
    public TdiNivelAcademico getTdiNivelAcademico() {
        return this.tdiNivelAcademico;
    }
    
    public void setTdiNivelAcademico(TdiNivelAcademico tdiNivelAcademico) {
        this.tdiNivelAcademico = tdiNivelAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PE_ID")
    public TdiPeriodo getTdiPeriodo() {
        return this.tdiPeriodo;
    }
    
    public void setTdiPeriodo(TdiPeriodo tdiPeriodo) {
        this.tdiPeriodo = tdiPeriodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="US_ID")
    public TdsUsuario getTdsUsuario() {
        return this.tdsUsuario;
    }
    
    public void setTdsUsuario(TdsUsuario tdsUsuario) {
        this.tdsUsuario = tdsUsuario;
    }

    
    @Column(name="PT_FRECUENCIA", length=5)
    public String getPtFrecuencia() {
        return this.ptFrecuencia;
    }
    
    public void setPtFrecuencia(String ptFrecuencia) {
        this.ptFrecuencia = ptFrecuencia;
    }

    
    @Column(name="PT_NUMERACION", precision=22, scale=0)
    public BigDecimal getPtNumeracion() {
        return this.ptNumeracion;
    }
    
    public void setPtNumeracion(BigDecimal ptNumeracion) {
        this.ptNumeracion = ptNumeracion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PT_FECHA_INICIO", length=7)
    public Date getPtFechaInicio() {
        return this.ptFechaInicio;
    }
    
    public void setPtFechaInicio(Date ptFechaInicio) {
        this.ptFechaInicio = ptFechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PT_FECHA_FIN", length=7)
    public Date getPtFechaFin() {
        return this.ptFechaFin;
    }
    
    public void setPtFechaFin(Date ptFechaFin) {
        this.ptFechaFin = ptFechaFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PT_FECHA_CREACION", length=7)
    public Date getPtFechaCreacion() {
        return this.ptFechaCreacion;
    }
    
    public void setPtFechaCreacion(Date ptFechaCreacion) {
        this.ptFechaCreacion = ptFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PT_FECHA_ACTUALIZACION", length=7)
    public Date getPtFechaActualizacion() {
        return this.ptFechaActualizacion;
    }
    
    public void setPtFechaActualizacion(Date ptFechaActualizacion) {
        this.ptFechaActualizacion = ptFechaActualizacion;
    }

    
    @Column(name="PT_OBSERVACION", length=150)
    public String getPtObservacion() {
        return this.ptObservacion;
    }
    
    public void setPtObservacion(String ptObservacion) {
        this.ptObservacion = ptObservacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiPeriodoDetalle")
    public Set<TdiParametrosIndicador> getTdiParametrosIndicadors() {
        return this.tdiParametrosIndicadors;
    }
    
    public void setTdiParametrosIndicadors(Set<TdiParametrosIndicador> tdiParametrosIndicadors) {
        this.tdiParametrosIndicadors = tdiParametrosIndicadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiPeriodoDetalle")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiPeriodoDetalle")
    public Set<TheActividadesEvaAvance> getTheActividadesEvaAvances() {
        return this.theActividadesEvaAvances;
    }
    
    public void setTheActividadesEvaAvances(Set<TheActividadesEvaAvance> theActividadesEvaAvances) {
        this.theActividadesEvaAvances = theActividadesEvaAvances;
    }




}


