package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiParametrosIndicador generated by hbm2java
 */
@Entity
@Table(name="TDI_PARAMETROS_INDICADOR"
    ,schema="ESQ_SIEC"
)
public class TdiParametrosIndicador  implements java.io.Serializable {


     private BigDecimal piId;
     private TdiIndicador tdiIndicador;
     private TdiPeriodoDetalle tdiPeriodoDetalle;
     private BigDecimal piValorObjetivo;
     private BigDecimal piValorCalificacion;
     private Date piFechaInicioCumplimiento;
     private Date piFechaFinCumplimiento;
     private BigDecimal piValorObjetivoSeguimiento;
     private Date piFechaInicioSeguimiento;
     private Date piFechaFinSeguimiento;
     private Date piFechaCreacion;
     private Date piFechaActualizacion;
     private String piObservacion;
     private Set<TdiDetParametrosIndicador> tdiDetParametrosIndicadors = new HashSet<TdiDetParametrosIndicador>(0);
     private Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs = new HashSet<TheActividadesDocEvaCab>(0);
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);

    public TdiParametrosIndicador() {
    }

	
    public TdiParametrosIndicador(BigDecimal piId, TdiIndicador tdiIndicador) {
        this.piId = piId;
        this.tdiIndicador = tdiIndicador;
    }
    public TdiParametrosIndicador(BigDecimal piId, TdiIndicador tdiIndicador, TdiPeriodoDetalle tdiPeriodoDetalle, BigDecimal piValorObjetivo, BigDecimal piValorCalificacion, Date piFechaInicioCumplimiento, Date piFechaFinCumplimiento, BigDecimal piValorObjetivoSeguimiento, Date piFechaInicioSeguimiento, Date piFechaFinSeguimiento, Date piFechaCreacion, Date piFechaActualizacion, String piObservacion, Set<TdiDetParametrosIndicador> tdiDetParametrosIndicadors, Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
       this.piId = piId;
       this.tdiIndicador = tdiIndicador;
       this.tdiPeriodoDetalle = tdiPeriodoDetalle;
       this.piValorObjetivo = piValorObjetivo;
       this.piValorCalificacion = piValorCalificacion;
       this.piFechaInicioCumplimiento = piFechaInicioCumplimiento;
       this.piFechaFinCumplimiento = piFechaFinCumplimiento;
       this.piValorObjetivoSeguimiento = piValorObjetivoSeguimiento;
       this.piFechaInicioSeguimiento = piFechaInicioSeguimiento;
       this.piFechaFinSeguimiento = piFechaFinSeguimiento;
       this.piFechaCreacion = piFechaCreacion;
       this.piFechaActualizacion = piFechaActualizacion;
       this.piObservacion = piObservacion;
       this.tdiDetParametrosIndicadors = tdiDetParametrosIndicadors;
       this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }
   
     @Id 

    
    @Column(name="PI_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPiId() {
        return this.piId;
    }
    
    public void setPiId(BigDecimal piId) {
        this.piId = piId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ID", nullable=false)
    public TdiIndicador getTdiIndicador() {
        return this.tdiIndicador;
    }
    
    public void setTdiIndicador(TdiIndicador tdiIndicador) {
        this.tdiIndicador = tdiIndicador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PT_ID")
    public TdiPeriodoDetalle getTdiPeriodoDetalle() {
        return this.tdiPeriodoDetalle;
    }
    
    public void setTdiPeriodoDetalle(TdiPeriodoDetalle tdiPeriodoDetalle) {
        this.tdiPeriodoDetalle = tdiPeriodoDetalle;
    }

    
    @Column(name="PI_VALOR_OBJETIVO", precision=22, scale=0)
    public BigDecimal getPiValorObjetivo() {
        return this.piValorObjetivo;
    }
    
    public void setPiValorObjetivo(BigDecimal piValorObjetivo) {
        this.piValorObjetivo = piValorObjetivo;
    }

    
    @Column(name="PI_VALOR_CALIFICACION", precision=22, scale=0)
    public BigDecimal getPiValorCalificacion() {
        return this.piValorCalificacion;
    }
    
    public void setPiValorCalificacion(BigDecimal piValorCalificacion) {
        this.piValorCalificacion = piValorCalificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PI_FECHA_INICIO_CUMPLIMIENTO", length=7)
    public Date getPiFechaInicioCumplimiento() {
        return this.piFechaInicioCumplimiento;
    }
    
    public void setPiFechaInicioCumplimiento(Date piFechaInicioCumplimiento) {
        this.piFechaInicioCumplimiento = piFechaInicioCumplimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PI_FECHA_FIN_CUMPLIMIENTO", length=7)
    public Date getPiFechaFinCumplimiento() {
        return this.piFechaFinCumplimiento;
    }
    
    public void setPiFechaFinCumplimiento(Date piFechaFinCumplimiento) {
        this.piFechaFinCumplimiento = piFechaFinCumplimiento;
    }

    
    @Column(name="PI_VALOR_OBJETIVO_SEGUIMIENTO", precision=22, scale=0)
    public BigDecimal getPiValorObjetivoSeguimiento() {
        return this.piValorObjetivoSeguimiento;
    }
    
    public void setPiValorObjetivoSeguimiento(BigDecimal piValorObjetivoSeguimiento) {
        this.piValorObjetivoSeguimiento = piValorObjetivoSeguimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PI_FECHA_INICIO_SEGUIMIENTO", length=7)
    public Date getPiFechaInicioSeguimiento() {
        return this.piFechaInicioSeguimiento;
    }
    
    public void setPiFechaInicioSeguimiento(Date piFechaInicioSeguimiento) {
        this.piFechaInicioSeguimiento = piFechaInicioSeguimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PI_FECHA_FIN_SEGUIMIENTO", length=7)
    public Date getPiFechaFinSeguimiento() {
        return this.piFechaFinSeguimiento;
    }
    
    public void setPiFechaFinSeguimiento(Date piFechaFinSeguimiento) {
        this.piFechaFinSeguimiento = piFechaFinSeguimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PI_FECHA_CREACION", length=7)
    public Date getPiFechaCreacion() {
        return this.piFechaCreacion;
    }
    
    public void setPiFechaCreacion(Date piFechaCreacion) {
        this.piFechaCreacion = piFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PI_FECHA_ACTUALIZACION", length=7)
    public Date getPiFechaActualizacion() {
        return this.piFechaActualizacion;
    }
    
    public void setPiFechaActualizacion(Date piFechaActualizacion) {
        this.piFechaActualizacion = piFechaActualizacion;
    }

    
    @Column(name="PI_OBSERVACION", length=250)
    public String getPiObservacion() {
        return this.piObservacion;
    }
    
    public void setPiObservacion(String piObservacion) {
        this.piObservacion = piObservacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiParametrosIndicador")
    public Set<TdiDetParametrosIndicador> getTdiDetParametrosIndicadors() {
        return this.tdiDetParametrosIndicadors;
    }
    
    public void setTdiDetParametrosIndicadors(Set<TdiDetParametrosIndicador> tdiDetParametrosIndicadors) {
        this.tdiDetParametrosIndicadors = tdiDetParametrosIndicadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiParametrosIndicador")
    public Set<TheActividadesDocEvaCab> getTheActividadesDocEvaCabs() {
        return this.theActividadesDocEvaCabs;
    }
    
    public void setTheActividadesDocEvaCabs(Set<TheActividadesDocEvaCab> theActividadesDocEvaCabs) {
        this.theActividadesDocEvaCabs = theActividadesDocEvaCabs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdiParametrosIndicador")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }




}


