package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdiRangosSemaforo generated by hbm2java
 */
@Entity
@Table(name="TDI_RANGOS_SEMAFORO"
    ,schema="ESQ_SIEC"
)
public class TdiRangosSemaforo  implements java.io.Serializable {


     private BigDecimal rseId;
     private TdiIndicador tdiIndicador;
     private TdiPeriodo tdiPeriodo;
     private String rseColor;
     private String rseCodigoColor;
     private String rseSignificadoColor;
     private BigDecimal rseRangoInicial;
     private BigDecimal rseRangoFinal;
     private String rseVigente;
     private Date rseFechaCreacion;

    public TdiRangosSemaforo() {
    }

	
    public TdiRangosSemaforo(BigDecimal rseId, TdiIndicador tdiIndicador, TdiPeriodo tdiPeriodo, String rseColor, String rseSignificadoColor, BigDecimal rseRangoInicial, BigDecimal rseRangoFinal, String rseVigente, Date rseFechaCreacion) {
        this.rseId = rseId;
        this.tdiIndicador = tdiIndicador;
        this.tdiPeriodo = tdiPeriodo;
        this.rseColor = rseColor;
        this.rseSignificadoColor = rseSignificadoColor;
        this.rseRangoInicial = rseRangoInicial;
        this.rseRangoFinal = rseRangoFinal;
        this.rseVigente = rseVigente;
        this.rseFechaCreacion = rseFechaCreacion;
    }
    public TdiRangosSemaforo(BigDecimal rseId, TdiIndicador tdiIndicador, TdiPeriodo tdiPeriodo, String rseColor, String rseCodigoColor, String rseSignificadoColor, BigDecimal rseRangoInicial, BigDecimal rseRangoFinal, String rseVigente, Date rseFechaCreacion) {
       this.rseId = rseId;
       this.tdiIndicador = tdiIndicador;
       this.tdiPeriodo = tdiPeriodo;
       this.rseColor = rseColor;
       this.rseCodigoColor = rseCodigoColor;
       this.rseSignificadoColor = rseSignificadoColor;
       this.rseRangoInicial = rseRangoInicial;
       this.rseRangoFinal = rseRangoFinal;
       this.rseVigente = rseVigente;
       this.rseFechaCreacion = rseFechaCreacion;
    }
   
     @Id 

    
    @Column(name="RSE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getRseId() {
        return this.rseId;
    }
    
    public void setRseId(BigDecimal rseId) {
        this.rseId = rseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ID", nullable=false)
    public TdiIndicador getTdiIndicador() {
        return this.tdiIndicador;
    }
    
    public void setTdiIndicador(TdiIndicador tdiIndicador) {
        this.tdiIndicador = tdiIndicador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PE_ID_OFICIAL", nullable=false)
    public TdiPeriodo getTdiPeriodo() {
        return this.tdiPeriodo;
    }
    
    public void setTdiPeriodo(TdiPeriodo tdiPeriodo) {
        this.tdiPeriodo = tdiPeriodo;
    }

    
    @Column(name="RSE_COLOR", nullable=false, length=30)
    public String getRseColor() {
        return this.rseColor;
    }
    
    public void setRseColor(String rseColor) {
        this.rseColor = rseColor;
    }

    
    @Column(name="RSE_CODIGO_COLOR", length=15)
    public String getRseCodigoColor() {
        return this.rseCodigoColor;
    }
    
    public void setRseCodigoColor(String rseCodigoColor) {
        this.rseCodigoColor = rseCodigoColor;
    }

    
    @Column(name="RSE_SIGNIFICADO_COLOR", nullable=false, length=30)
    public String getRseSignificadoColor() {
        return this.rseSignificadoColor;
    }
    
    public void setRseSignificadoColor(String rseSignificadoColor) {
        this.rseSignificadoColor = rseSignificadoColor;
    }

    
    @Column(name="RSE_RANGO_INICIAL", nullable=false, precision=22, scale=0)
    public BigDecimal getRseRangoInicial() {
        return this.rseRangoInicial;
    }
    
    public void setRseRangoInicial(BigDecimal rseRangoInicial) {
        this.rseRangoInicial = rseRangoInicial;
    }

    
    @Column(name="RSE_RANGO_FINAL", nullable=false, precision=22, scale=0)
    public BigDecimal getRseRangoFinal() {
        return this.rseRangoFinal;
    }
    
    public void setRseRangoFinal(BigDecimal rseRangoFinal) {
        this.rseRangoFinal = rseRangoFinal;
    }

    
    @Column(name="RSE_VIGENTE", nullable=false, length=1)
    public String getRseVigente() {
        return this.rseVigente;
    }
    
    public void setRseVigente(String rseVigente) {
        this.rseVigente = rseVigente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RSE_FECHA_CREACION", nullable=false, length=7)
    public Date getRseFechaCreacion() {
        return this.rseFechaCreacion;
    }
    
    public void setRseFechaCreacion(Date rseFechaCreacion) {
        this.rseFechaCreacion = rseFechaCreacion;
    }




}


