package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdsFiltrosUgda generated by hbm2java
 */
@Entity
@Table(name="TDS_FILTROS_UGDA"
    ,schema="ESQ_SIEC"
)
public class TdsFiltrosUgda  implements java.io.Serializable {


     private BigDecimal filId;
     private BigDecimal filCodigo;
     private String filModulo;
     private String filAplicacion;
     private String filDescripcion;
     private String filVigencia;
     private Date filFechaInicioVig;
     private Date filFechaFinVig;

    public TdsFiltrosUgda() {
    }

	
    public TdsFiltrosUgda(BigDecimal filId, String filModulo, String filAplicacion, String filVigencia, Date filFechaInicioVig) {
        this.filId = filId;
        this.filModulo = filModulo;
        this.filAplicacion = filAplicacion;
        this.filVigencia = filVigencia;
        this.filFechaInicioVig = filFechaInicioVig;
    }
    public TdsFiltrosUgda(BigDecimal filId, BigDecimal filCodigo, String filModulo, String filAplicacion, String filDescripcion, String filVigencia, Date filFechaInicioVig, Date filFechaFinVig) {
       this.filId = filId;
       this.filCodigo = filCodigo;
       this.filModulo = filModulo;
       this.filAplicacion = filAplicacion;
       this.filDescripcion = filDescripcion;
       this.filVigencia = filVigencia;
       this.filFechaInicioVig = filFechaInicioVig;
       this.filFechaFinVig = filFechaFinVig;
    }
   
     @Id 

    
    @Column(name="FIL_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getFilId() {
        return this.filId;
    }
    
    public void setFilId(BigDecimal filId) {
        this.filId = filId;
    }

    
    @Column(name="FIL_CODIGO", precision=22, scale=0)
    public BigDecimal getFilCodigo() {
        return this.filCodigo;
    }
    
    public void setFilCodigo(BigDecimal filCodigo) {
        this.filCodigo = filCodigo;
    }

    
    @Column(name="FIL_MODULO", nullable=false, length=50)
    public String getFilModulo() {
        return this.filModulo;
    }
    
    public void setFilModulo(String filModulo) {
        this.filModulo = filModulo;
    }

    
    @Column(name="FIL_APLICACION", nullable=false, length=100)
    public String getFilAplicacion() {
        return this.filAplicacion;
    }
    
    public void setFilAplicacion(String filAplicacion) {
        this.filAplicacion = filAplicacion;
    }

    
    @Column(name="FIL_DESCRIPCION", length=200)
    public String getFilDescripcion() {
        return this.filDescripcion;
    }
    
    public void setFilDescripcion(String filDescripcion) {
        this.filDescripcion = filDescripcion;
    }

    
    @Column(name="FIL_VIGENCIA", nullable=false, length=1)
    public String getFilVigencia() {
        return this.filVigencia;
    }
    
    public void setFilVigencia(String filVigencia) {
        this.filVigencia = filVigencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FIL_FECHA_INICIO_VIG", nullable=false, length=7)
    public Date getFilFechaInicioVig() {
        return this.filFechaInicioVig;
    }
    
    public void setFilFechaInicioVig(Date filFechaInicioVig) {
        this.filFechaInicioVig = filFechaInicioVig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FIL_FECHA_FIN_VIG", length=7)
    public Date getFilFechaFinVig() {
        return this.filFechaFinVig;
    }
    
    public void setFilFechaFinVig(Date filFechaFinVig) {
        this.filFechaFinVig = filFechaFinVig;
    }




}


