package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TdsRol generated by hbm2java
 */
@Entity
@Table(name="TDS_ROL"
    ,schema="ESQ_SIEC"
    , uniqueConstraints = @UniqueConstraint(columnNames="RO_CODIGO") 
)
public class TdsRol  implements java.io.Serializable {


     private BigDecimal roId;
     private String roNombre;
     private Date roFechaInicioVig;
     private Date roFechaFinVig;
     private String roVigente;
     private String roCodigo;
     private String roActivoApex;
     private Date roFechaCreacion;
     private Date roFechaUltActualizacion;
     private String roDescripcion;
     private Set<TdsRolUsuarioUgda> tdsRolUsuarioUgdas = new HashSet<TdsRolUsuarioUgda>(0);
     private Set<TdsRolUsuario> tdsRolUsuarios = new HashSet<TdsRolUsuario>(0);

    public TdsRol() {
    }

	
    public TdsRol(BigDecimal roId, String roNombre, Date roFechaInicioVig, String roVigente, String roActivoApex, Date roFechaCreacion, Date roFechaUltActualizacion) {
        this.roId = roId;
        this.roNombre = roNombre;
        this.roFechaInicioVig = roFechaInicioVig;
        this.roVigente = roVigente;
        this.roActivoApex = roActivoApex;
        this.roFechaCreacion = roFechaCreacion;
        this.roFechaUltActualizacion = roFechaUltActualizacion;
    }
    public TdsRol(BigDecimal roId, String roNombre, Date roFechaInicioVig, Date roFechaFinVig, String roVigente, String roCodigo, String roActivoApex, Date roFechaCreacion, Date roFechaUltActualizacion, String roDescripcion, Set<TdsRolUsuarioUgda> tdsRolUsuarioUgdas, Set<TdsRolUsuario> tdsRolUsuarios) {
       this.roId = roId;
       this.roNombre = roNombre;
       this.roFechaInicioVig = roFechaInicioVig;
       this.roFechaFinVig = roFechaFinVig;
       this.roVigente = roVigente;
       this.roCodigo = roCodigo;
       this.roActivoApex = roActivoApex;
       this.roFechaCreacion = roFechaCreacion;
       this.roFechaUltActualizacion = roFechaUltActualizacion;
       this.roDescripcion = roDescripcion;
       this.tdsRolUsuarioUgdas = tdsRolUsuarioUgdas;
       this.tdsRolUsuarios = tdsRolUsuarios;
    }
   
     @Id 

    
    @Column(name="RO_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getRoId() {
        return this.roId;
    }
    
    public void setRoId(BigDecimal roId) {
        this.roId = roId;
    }

    
    @Column(name="RO_NOMBRE", nullable=false, length=50)
    public String getRoNombre() {
        return this.roNombre;
    }
    
    public void setRoNombre(String roNombre) {
        this.roNombre = roNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RO_FECHA_INICIO_VIG", nullable=false, length=7)
    public Date getRoFechaInicioVig() {
        return this.roFechaInicioVig;
    }
    
    public void setRoFechaInicioVig(Date roFechaInicioVig) {
        this.roFechaInicioVig = roFechaInicioVig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RO_FECHA_FIN_VIG", length=7)
    public Date getRoFechaFinVig() {
        return this.roFechaFinVig;
    }
    
    public void setRoFechaFinVig(Date roFechaFinVig) {
        this.roFechaFinVig = roFechaFinVig;
    }

    
    @Column(name="RO_VIGENTE", nullable=false, length=1)
    public String getRoVigente() {
        return this.roVigente;
    }
    
    public void setRoVigente(String roVigente) {
        this.roVigente = roVigente;
    }

    
    @Column(name="RO_CODIGO", unique=true, length=30)
    public String getRoCodigo() {
        return this.roCodigo;
    }
    
    public void setRoCodigo(String roCodigo) {
        this.roCodigo = roCodigo;
    }

    
    @Column(name="RO_ACTIVO_APEX", nullable=false, length=1)
    public String getRoActivoApex() {
        return this.roActivoApex;
    }
    
    public void setRoActivoApex(String roActivoApex) {
        this.roActivoApex = roActivoApex;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RO_FECHA_CREACION", nullable=false, length=7)
    public Date getRoFechaCreacion() {
        return this.roFechaCreacion;
    }
    
    public void setRoFechaCreacion(Date roFechaCreacion) {
        this.roFechaCreacion = roFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RO_FECHA_ULT_ACTUALIZACION", nullable=false, length=7)
    public Date getRoFechaUltActualizacion() {
        return this.roFechaUltActualizacion;
    }
    
    public void setRoFechaUltActualizacion(Date roFechaUltActualizacion) {
        this.roFechaUltActualizacion = roFechaUltActualizacion;
    }

    
    @Column(name="RO_DESCRIPCION", length=300)
    public String getRoDescripcion() {
        return this.roDescripcion;
    }
    
    public void setRoDescripcion(String roDescripcion) {
        this.roDescripcion = roDescripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdsRol")
    public Set<TdsRolUsuarioUgda> getTdsRolUsuarioUgdas() {
        return this.tdsRolUsuarioUgdas;
    }
    
    public void setTdsRolUsuarioUgdas(Set<TdsRolUsuarioUgda> tdsRolUsuarioUgdas) {
        this.tdsRolUsuarioUgdas = tdsRolUsuarioUgdas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdsRol")
    public Set<TdsRolUsuario> getTdsRolUsuarios() {
        return this.tdsRolUsuarios;
    }
    
    public void setTdsRolUsuarios(Set<TdsRolUsuario> tdsRolUsuarios) {
        this.tdsRolUsuarios = tdsRolUsuarios;
    }




}


