package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TdsRegistroAccesosUgda generated by hbm2java
 */
@Entity
@Table(name="TDS_REGISTRO_ACCESOS_UGDA"
    ,schema="ESQ_SIEC"
)
public class TdsRegistroAccesosUgda  implements java.io.Serializable {


     private BigDecimal racId;
     private BigDecimal usId;
     private String racModulo;
     private String racFechaIngreso;
     private String racTipoApp;

    public TdsRegistroAccesosUgda() {
    }

    public TdsRegistroAccesosUgda(BigDecimal racId, BigDecimal usId, String racModulo, String racFechaIngreso, String racTipoApp) {
       this.racId = racId;
       this.usId = usId;
       this.racModulo = racModulo;
       this.racFechaIngreso = racFechaIngreso;
       this.racTipoApp = racTipoApp;
    }
   
     @Id 

    
    @Column(name="RAC_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getRacId() {
        return this.racId;
    }
    
    public void setRacId(BigDecimal racId) {
        this.racId = racId;
    }

    
    @Column(name="US_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUsId() {
        return this.usId;
    }
    
    public void setUsId(BigDecimal usId) {
        this.usId = usId;
    }

    
    @Column(name="RAC_MODULO", nullable=false, length=1000)
    public String getRacModulo() {
        return this.racModulo;
    }
    
    public void setRacModulo(String racModulo) {
        this.racModulo = racModulo;
    }

    
    @Column(name="RAC_FECHA_INGRESO", nullable=false, length=25)
    public String getRacFechaIngreso() {
        return this.racFechaIngreso;
    }
    
    public void setRacFechaIngreso(String racFechaIngreso) {
        this.racFechaIngreso = racFechaIngreso;
    }

    
    @Column(name="RAC_TIPO_APP", nullable=false, length=50)
    public String getRacTipoApp() {
        return this.racTipoApp;
    }
    
    public void setRacTipoApp(String racTipoApp) {
        this.racTipoApp = racTipoApp;
    }




}


