package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TdsRolUsuarioUgda generated by hbm2java
 */
@Entity
@Table(name="TDS_ROL_USUARIO_UGDA"
    ,schema="ESQ_SIEC"
)
public class TdsRolUsuarioUgda  implements java.io.Serializable {


     private BigDecimal ruuId;
     private TdsRol tdsRol;
     private TdsUsuarioUgda tdsUsuarioUgda;
     private Date ruuFechaInicioVig;
     private String ruuVigente;

    public TdsRolUsuarioUgda() {
    }

    public TdsRolUsuarioUgda(BigDecimal ruuId, TdsRol tdsRol, TdsUsuarioUgda tdsUsuarioUgda, Date ruuFechaInicioVig, String ruuVigente) {
       this.ruuId = ruuId;
       this.tdsRol = tdsRol;
       this.tdsUsuarioUgda = tdsUsuarioUgda;
       this.ruuFechaInicioVig = ruuFechaInicioVig;
       this.ruuVigente = ruuVigente;
    }
   
     @Id 

    
    @Column(name="RUU_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getRuuId() {
        return this.ruuId;
    }
    
    public void setRuuId(BigDecimal ruuId) {
        this.ruuId = ruuId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RO_ID", nullable=false)
    public TdsRol getTdsRol() {
        return this.tdsRol;
    }
    
    public void setTdsRol(TdsRol tdsRol) {
        this.tdsRol = tdsRol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="US_ID", nullable=false)
    public TdsUsuarioUgda getTdsUsuarioUgda() {
        return this.tdsUsuarioUgda;
    }
    
    public void setTdsUsuarioUgda(TdsUsuarioUgda tdsUsuarioUgda) {
        this.tdsUsuarioUgda = tdsUsuarioUgda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RUU_FECHA_INICIO_VIG", nullable=false, length=7)
    public Date getRuuFechaInicioVig() {
        return this.ruuFechaInicioVig;
    }
    
    public void setRuuFechaInicioVig(Date ruuFechaInicioVig) {
        this.ruuFechaInicioVig = ruuFechaInicioVig;
    }

    
    @Column(name="RUU_VIGENTE", nullable=false, length=1)
    public String getRuuVigente() {
        return this.ruuVigente;
    }
    
    public void setRuuVigente(String ruuVigente) {
        this.ruuVigente = ruuVigente;
    }




}


