package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TdsUsuario generated by hbm2java
 */
@Entity
@Table(name="TDS_USUARIO"
    ,schema="ESQ_SIEC"
    , uniqueConstraints = @UniqueConstraint(columnNames="US_USERNAME") 
)
public class TdsUsuario  implements java.io.Serializable {


     private BigDecimal usId;
     private String usNombre;
     private Date usFechaInicioVig;
     private Date usFechaFinVig;
     private String usVigencia;
     private String usUsername;
     private String usPassword;
     private String usBloqueado;
     private Date usFechaCreacion;
     private Date usFechaUltActualizacion;
     private String usuarioApexCrea;
     private String usuarioApexUltActualizacion;
     private String usObservaciones;
     private String usCambiarClavePrimeraVez;
     private BigDecimal usHabilitado;
     private String usCorreo;
     private BigDecimal usTipoUsuario;
     private String usIdentificacion;
     private String usSolicitadoPor;
     private Set<TdiPeriodo> tdiPeriodos = new HashSet<TdiPeriodo>(0);
     private Set<TdsRolUsuario> tdsRolUsuarios = new HashSet<TdsRolUsuario>(0);
     private Set<TdiDocente> tdiDocentes = new HashSet<TdiDocente>(0);
     private Set<TdiPeriodoDetalle> tdiPeriodoDetalles = new HashSet<TdiPeriodoDetalle>(0);

    public TdsUsuario() {
    }

	
    public TdsUsuario(BigDecimal usId, String usNombre, Date usFechaInicioVig, String usVigencia, String usUsername, String usBloqueado) {
        this.usId = usId;
        this.usNombre = usNombre;
        this.usFechaInicioVig = usFechaInicioVig;
        this.usVigencia = usVigencia;
        this.usUsername = usUsername;
        this.usBloqueado = usBloqueado;
    }
    public TdsUsuario(BigDecimal usId, String usNombre, Date usFechaInicioVig, Date usFechaFinVig, String usVigencia, String usUsername, String usPassword, String usBloqueado, Date usFechaCreacion, Date usFechaUltActualizacion, String usuarioApexCrea, String usuarioApexUltActualizacion, String usObservaciones, String usCambiarClavePrimeraVez, BigDecimal usHabilitado, String usCorreo, BigDecimal usTipoUsuario, String usIdentificacion, String usSolicitadoPor, Set<TdiPeriodo> tdiPeriodos, Set<TdsRolUsuario> tdsRolUsuarios, Set<TdiDocente> tdiDocentes, Set<TdiPeriodoDetalle> tdiPeriodoDetalles) {
       this.usId = usId;
       this.usNombre = usNombre;
       this.usFechaInicioVig = usFechaInicioVig;
       this.usFechaFinVig = usFechaFinVig;
       this.usVigencia = usVigencia;
       this.usUsername = usUsername;
       this.usPassword = usPassword;
       this.usBloqueado = usBloqueado;
       this.usFechaCreacion = usFechaCreacion;
       this.usFechaUltActualizacion = usFechaUltActualizacion;
       this.usuarioApexCrea = usuarioApexCrea;
       this.usuarioApexUltActualizacion = usuarioApexUltActualizacion;
       this.usObservaciones = usObservaciones;
       this.usCambiarClavePrimeraVez = usCambiarClavePrimeraVez;
       this.usHabilitado = usHabilitado;
       this.usCorreo = usCorreo;
       this.usTipoUsuario = usTipoUsuario;
       this.usIdentificacion = usIdentificacion;
       this.usSolicitadoPor = usSolicitadoPor;
       this.tdiPeriodos = tdiPeriodos;
       this.tdsRolUsuarios = tdsRolUsuarios;
       this.tdiDocentes = tdiDocentes;
       this.tdiPeriodoDetalles = tdiPeriodoDetalles;
    }
   
     @Id 

    
    @Column(name="US_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getUsId() {
        return this.usId;
    }
    
    public void setUsId(BigDecimal usId) {
        this.usId = usId;
    }

    
    @Column(name="US_NOMBRE", nullable=false, length=100)
    public String getUsNombre() {
        return this.usNombre;
    }
    
    public void setUsNombre(String usNombre) {
        this.usNombre = usNombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="US_FECHA_INICIO_VIG", nullable=false, length=7)
    public Date getUsFechaInicioVig() {
        return this.usFechaInicioVig;
    }
    
    public void setUsFechaInicioVig(Date usFechaInicioVig) {
        this.usFechaInicioVig = usFechaInicioVig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="US_FECHA_FIN_VIG", length=7)
    public Date getUsFechaFinVig() {
        return this.usFechaFinVig;
    }
    
    public void setUsFechaFinVig(Date usFechaFinVig) {
        this.usFechaFinVig = usFechaFinVig;
    }

    
    @Column(name="US_VIGENCIA", nullable=false, length=1)
    public String getUsVigencia() {
        return this.usVigencia;
    }
    
    public void setUsVigencia(String usVigencia) {
        this.usVigencia = usVigencia;
    }

    
    @Column(name="US_USERNAME", unique=true, nullable=false, length=30)
    public String getUsUsername() {
        return this.usUsername;
    }
    
    public void setUsUsername(String usUsername) {
        this.usUsername = usUsername;
    }

    
    @Column(name="US_PASSWORD", length=40)
    public String getUsPassword() {
        return this.usPassword;
    }
    
    public void setUsPassword(String usPassword) {
        this.usPassword = usPassword;
    }

    
    @Column(name="US_BLOQUEADO", nullable=false, length=4)
    public String getUsBloqueado() {
        return this.usBloqueado;
    }
    
    public void setUsBloqueado(String usBloqueado) {
        this.usBloqueado = usBloqueado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="US_FECHA_CREACION", length=7)
    public Date getUsFechaCreacion() {
        return this.usFechaCreacion;
    }
    
    public void setUsFechaCreacion(Date usFechaCreacion) {
        this.usFechaCreacion = usFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="US_FECHA_ULT_ACTUALIZACION", length=7)
    public Date getUsFechaUltActualizacion() {
        return this.usFechaUltActualizacion;
    }
    
    public void setUsFechaUltActualizacion(Date usFechaUltActualizacion) {
        this.usFechaUltActualizacion = usFechaUltActualizacion;
    }

    
    @Column(name="USUARIO_APEX_CREA", length=35)
    public String getUsuarioApexCrea() {
        return this.usuarioApexCrea;
    }
    
    public void setUsuarioApexCrea(String usuarioApexCrea) {
        this.usuarioApexCrea = usuarioApexCrea;
    }

    
    @Column(name="USUARIO_APEX_ULT_ACTUALIZACION", length=35)
    public String getUsuarioApexUltActualizacion() {
        return this.usuarioApexUltActualizacion;
    }
    
    public void setUsuarioApexUltActualizacion(String usuarioApexUltActualizacion) {
        this.usuarioApexUltActualizacion = usuarioApexUltActualizacion;
    }

    
    @Column(name="US_OBSERVACIONES", length=350)
    public String getUsObservaciones() {
        return this.usObservaciones;
    }
    
    public void setUsObservaciones(String usObservaciones) {
        this.usObservaciones = usObservaciones;
    }

    
    @Column(name="US_CAMBIAR_CLAVE_PRIMERA_VEZ", length=1)
    public String getUsCambiarClavePrimeraVez() {
        return this.usCambiarClavePrimeraVez;
    }
    
    public void setUsCambiarClavePrimeraVez(String usCambiarClavePrimeraVez) {
        this.usCambiarClavePrimeraVez = usCambiarClavePrimeraVez;
    }

    
    @Column(name="US_HABILITADO", precision=22, scale=0)
    public BigDecimal getUsHabilitado() {
        return this.usHabilitado;
    }
    
    public void setUsHabilitado(BigDecimal usHabilitado) {
        this.usHabilitado = usHabilitado;
    }

    
    @Column(name="US_CORREO", length=50)
    public String getUsCorreo() {
        return this.usCorreo;
    }
    
    public void setUsCorreo(String usCorreo) {
        this.usCorreo = usCorreo;
    }

    
    @Column(name="US_TIPO_USUARIO", precision=22, scale=0)
    public BigDecimal getUsTipoUsuario() {
        return this.usTipoUsuario;
    }
    
    public void setUsTipoUsuario(BigDecimal usTipoUsuario) {
        this.usTipoUsuario = usTipoUsuario;
    }

    
    @Column(name="US_IDENTIFICACION", length=30)
    public String getUsIdentificacion() {
        return this.usIdentificacion;
    }
    
    public void setUsIdentificacion(String usIdentificacion) {
        this.usIdentificacion = usIdentificacion;
    }

    
    @Column(name="US_SOLICITADO_POR", length=100)
    public String getUsSolicitadoPor() {
        return this.usSolicitadoPor;
    }
    
    public void setUsSolicitadoPor(String usSolicitadoPor) {
        this.usSolicitadoPor = usSolicitadoPor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdsUsuario")
    public Set<TdiPeriodo> getTdiPeriodos() {
        return this.tdiPeriodos;
    }
    
    public void setTdiPeriodos(Set<TdiPeriodo> tdiPeriodos) {
        this.tdiPeriodos = tdiPeriodos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdsUsuario")
    public Set<TdsRolUsuario> getTdsRolUsuarios() {
        return this.tdsRolUsuarios;
    }
    
    public void setTdsRolUsuarios(Set<TdsRolUsuario> tdsRolUsuarios) {
        this.tdsRolUsuarios = tdsRolUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdsUsuario")
    public Set<TdiDocente> getTdiDocentes() {
        return this.tdiDocentes;
    }
    
    public void setTdiDocentes(Set<TdiDocente> tdiDocentes) {
        this.tdiDocentes = tdiDocentes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdsUsuario")
    public Set<TdiPeriodoDetalle> getTdiPeriodoDetalles() {
        return this.tdiPeriodoDetalles;
    }
    
    public void setTdiPeriodoDetalles(Set<TdiPeriodoDetalle> tdiPeriodoDetalles) {
        this.tdiPeriodoDetalles = tdiPeriodoDetalles;
    }




}


