package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TevaMicrovideos generated by hbm2java
 */
@Entity
@Table(name="TEVA_MICROVIDEOS"
    ,schema="ESQ_SIEC"
)
public class TevaMicrovideos  implements java.io.Serializable {


     private BigDecimal mivId;
     private TdiComponenteEducativo tdiComponenteEducativo;
     private TdiOfertaNsga tdiOfertaNsga;
     private TdiDocente tdiDocente;
     private TdiIndicador tdiIndicador;
     private TdiPeriodo tdiPeriodo;
     private TdiGlosario tdiGlosario;
     private BigDecimal mivCursoEvaId;
     private String mivNombre;
     private String mivContenido;
     private Date mivFechaModificacionEva;
     private BigDecimal mivLabelIdEva;
     private Date mivFechaCreacionSiec;
     private String mivUsuarioCreacionSiec;
     private Date mivFechaUltActSiec;
     private String mivUsuarioActSiec;
     private BigDecimal mivSeccionEvaId;
     private BigDecimal mivNumeroSeccionEva;
     private BigDecimal mivNumeracionMicrovideo;
     private BigDecimal mivIdRsaPost;
     private BigDecimal piIdSemana;
     private String mivEsPrimerCiclo;
     private String mivEsFormacionBasica;
     private BigDecimal minNumSemanaFinal;
     private BigDecimal mivVisible;
     private Date mivFechaCreacionEva;
     private BigDecimal mivSemanaCreacion;
     private BigDecimal mivIdLessonPage;
     private BigDecimal mivCantVideos;
     private String mivUrlMicrovideo;
     private Date mivFechaEnrolamientoEva;
     private Character mivVigente;
     private BigDecimal mivIdPage;
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);

    public TevaMicrovideos() {
    }

	
    public TevaMicrovideos(BigDecimal mivId, TdiComponenteEducativo tdiComponenteEducativo, TdiOfertaNsga tdiOfertaNsga, TdiDocente tdiDocente, TdiPeriodo tdiPeriodo, TdiGlosario tdiGlosario, BigDecimal mivCursoEvaId, String mivContenido, Date mivFechaModificacionEva, Date mivFechaCreacionSiec, String mivUsuarioCreacionSiec) {
        this.mivId = mivId;
        this.tdiComponenteEducativo = tdiComponenteEducativo;
        this.tdiOfertaNsga = tdiOfertaNsga;
        this.tdiDocente = tdiDocente;
        this.tdiPeriodo = tdiPeriodo;
        this.tdiGlosario = tdiGlosario;
        this.mivCursoEvaId = mivCursoEvaId;
        this.mivContenido = mivContenido;
        this.mivFechaModificacionEva = mivFechaModificacionEva;
        this.mivFechaCreacionSiec = mivFechaCreacionSiec;
        this.mivUsuarioCreacionSiec = mivUsuarioCreacionSiec;
    }
    public TevaMicrovideos(BigDecimal mivId, TdiComponenteEducativo tdiComponenteEducativo, TdiOfertaNsga tdiOfertaNsga, TdiDocente tdiDocente, TdiIndicador tdiIndicador, TdiPeriodo tdiPeriodo, TdiGlosario tdiGlosario, BigDecimal mivCursoEvaId, String mivNombre, String mivContenido, Date mivFechaModificacionEva, BigDecimal mivLabelIdEva, Date mivFechaCreacionSiec, String mivUsuarioCreacionSiec, Date mivFechaUltActSiec, String mivUsuarioActSiec, BigDecimal mivSeccionEvaId, BigDecimal mivNumeroSeccionEva, BigDecimal mivNumeracionMicrovideo, BigDecimal mivIdRsaPost, BigDecimal piIdSemana, String mivEsPrimerCiclo, String mivEsFormacionBasica, BigDecimal minNumSemanaFinal, BigDecimal mivVisible, Date mivFechaCreacionEva, BigDecimal mivSemanaCreacion, BigDecimal mivIdLessonPage, BigDecimal mivCantVideos, String mivUrlMicrovideo, Date mivFechaEnrolamientoEva, Character mivVigente, BigDecimal mivIdPage, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
       this.mivId = mivId;
       this.tdiComponenteEducativo = tdiComponenteEducativo;
       this.tdiOfertaNsga = tdiOfertaNsga;
       this.tdiDocente = tdiDocente;
       this.tdiIndicador = tdiIndicador;
       this.tdiPeriodo = tdiPeriodo;
       this.tdiGlosario = tdiGlosario;
       this.mivCursoEvaId = mivCursoEvaId;
       this.mivNombre = mivNombre;
       this.mivContenido = mivContenido;
       this.mivFechaModificacionEva = mivFechaModificacionEva;
       this.mivLabelIdEva = mivLabelIdEva;
       this.mivFechaCreacionSiec = mivFechaCreacionSiec;
       this.mivUsuarioCreacionSiec = mivUsuarioCreacionSiec;
       this.mivFechaUltActSiec = mivFechaUltActSiec;
       this.mivUsuarioActSiec = mivUsuarioActSiec;
       this.mivSeccionEvaId = mivSeccionEvaId;
       this.mivNumeroSeccionEva = mivNumeroSeccionEva;
       this.mivNumeracionMicrovideo = mivNumeracionMicrovideo;
       this.mivIdRsaPost = mivIdRsaPost;
       this.piIdSemana = piIdSemana;
       this.mivEsPrimerCiclo = mivEsPrimerCiclo;
       this.mivEsFormacionBasica = mivEsFormacionBasica;
       this.minNumSemanaFinal = minNumSemanaFinal;
       this.mivVisible = mivVisible;
       this.mivFechaCreacionEva = mivFechaCreacionEva;
       this.mivSemanaCreacion = mivSemanaCreacion;
       this.mivIdLessonPage = mivIdLessonPage;
       this.mivCantVideos = mivCantVideos;
       this.mivUrlMicrovideo = mivUrlMicrovideo;
       this.mivFechaEnrolamientoEva = mivFechaEnrolamientoEva;
       this.mivVigente = mivVigente;
       this.mivIdPage = mivIdPage;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }
   
     @Id 

    
    @Column(name="MIV_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getMivId() {
        return this.mivId;
    }
    
    public void setMivId(BigDecimal mivId) {
        this.mivId = mivId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CE_ID", nullable=false)
    public TdiComponenteEducativo getTdiComponenteEducativo() {
        return this.tdiComponenteEducativo;
    }
    
    public void setTdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo) {
        this.tdiComponenteEducativo = tdiComponenteEducativo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ONS_ID", nullable=false)
    public TdiOfertaNsga getTdiOfertaNsga() {
        return this.tdiOfertaNsga;
    }
    
    public void setTdiOfertaNsga(TdiOfertaNsga tdiOfertaNsga) {
        this.tdiOfertaNsga = tdiOfertaNsga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DO_ID", nullable=false)
    public TdiDocente getTdiDocente() {
        return this.tdiDocente;
    }
    
    public void setTdiDocente(TdiDocente tdiDocente) {
        this.tdiDocente = tdiDocente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ID")
    public TdiIndicador getTdiIndicador() {
        return this.tdiIndicador;
    }
    
    public void setTdiIndicador(TdiIndicador tdiIndicador) {
        this.tdiIndicador = tdiIndicador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PE_ID", nullable=false)
    public TdiPeriodo getTdiPeriodo() {
        return this.tdiPeriodo;
    }
    
    public void setTdiPeriodo(TdiPeriodo tdiPeriodo) {
        this.tdiPeriodo = tdiPeriodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MIV_PARALELO_ID", nullable=false)
    public TdiGlosario getTdiGlosario() {
        return this.tdiGlosario;
    }
    
    public void setTdiGlosario(TdiGlosario tdiGlosario) {
        this.tdiGlosario = tdiGlosario;
    }

    
    @Column(name="MIV_CURSO_EVA_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getMivCursoEvaId() {
        return this.mivCursoEvaId;
    }
    
    public void setMivCursoEvaId(BigDecimal mivCursoEvaId) {
        this.mivCursoEvaId = mivCursoEvaId;
    }

    
    @Column(name="MIV_NOMBRE", length=3999)
    public String getMivNombre() {
        return this.mivNombre;
    }
    
    public void setMivNombre(String mivNombre) {
        this.mivNombre = mivNombre;
    }

    
    @Column(name="MIV_CONTENIDO", nullable=false, length=3999)
    public String getMivContenido() {
        return this.mivContenido;
    }
    
    public void setMivContenido(String mivContenido) {
        this.mivContenido = mivContenido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MIV_FECHA_MODIFICACION_EVA", nullable=false, length=7)
    public Date getMivFechaModificacionEva() {
        return this.mivFechaModificacionEva;
    }
    
    public void setMivFechaModificacionEva(Date mivFechaModificacionEva) {
        this.mivFechaModificacionEva = mivFechaModificacionEva;
    }

    
    @Column(name="MIV_LABEL_ID_EVA", precision=22, scale=0)
    public BigDecimal getMivLabelIdEva() {
        return this.mivLabelIdEva;
    }
    
    public void setMivLabelIdEva(BigDecimal mivLabelIdEva) {
        this.mivLabelIdEva = mivLabelIdEva;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MIV_FECHA_CREACION_SIEC", nullable=false, length=7)
    public Date getMivFechaCreacionSiec() {
        return this.mivFechaCreacionSiec;
    }
    
    public void setMivFechaCreacionSiec(Date mivFechaCreacionSiec) {
        this.mivFechaCreacionSiec = mivFechaCreacionSiec;
    }

    
    @Column(name="MIV_USUARIO_CREACION_SIEC", nullable=false, length=35)
    public String getMivUsuarioCreacionSiec() {
        return this.mivUsuarioCreacionSiec;
    }
    
    public void setMivUsuarioCreacionSiec(String mivUsuarioCreacionSiec) {
        this.mivUsuarioCreacionSiec = mivUsuarioCreacionSiec;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MIV_FECHA_ULT_ACT_SIEC", length=7)
    public Date getMivFechaUltActSiec() {
        return this.mivFechaUltActSiec;
    }
    
    public void setMivFechaUltActSiec(Date mivFechaUltActSiec) {
        this.mivFechaUltActSiec = mivFechaUltActSiec;
    }

    
    @Column(name="MIV_USUARIO_ACT_SIEC", length=35)
    public String getMivUsuarioActSiec() {
        return this.mivUsuarioActSiec;
    }
    
    public void setMivUsuarioActSiec(String mivUsuarioActSiec) {
        this.mivUsuarioActSiec = mivUsuarioActSiec;
    }

    
    @Column(name="MIV_SECCION_EVA_ID", precision=22, scale=0)
    public BigDecimal getMivSeccionEvaId() {
        return this.mivSeccionEvaId;
    }
    
    public void setMivSeccionEvaId(BigDecimal mivSeccionEvaId) {
        this.mivSeccionEvaId = mivSeccionEvaId;
    }

    
    @Column(name="MIV_NUMERO_SECCION_EVA", precision=22, scale=0)
    public BigDecimal getMivNumeroSeccionEva() {
        return this.mivNumeroSeccionEva;
    }
    
    public void setMivNumeroSeccionEva(BigDecimal mivNumeroSeccionEva) {
        this.mivNumeroSeccionEva = mivNumeroSeccionEva;
    }

    
    @Column(name="MIV_NUMERACION_MICROVIDEO", precision=22, scale=0)
    public BigDecimal getMivNumeracionMicrovideo() {
        return this.mivNumeracionMicrovideo;
    }
    
    public void setMivNumeracionMicrovideo(BigDecimal mivNumeracionMicrovideo) {
        this.mivNumeracionMicrovideo = mivNumeracionMicrovideo;
    }

    
    @Column(name="MIV_ID_RSA_POST", precision=22, scale=0)
    public BigDecimal getMivIdRsaPost() {
        return this.mivIdRsaPost;
    }
    
    public void setMivIdRsaPost(BigDecimal mivIdRsaPost) {
        this.mivIdRsaPost = mivIdRsaPost;
    }

    
    @Column(name="PI_ID_SEMANA", precision=22, scale=0)
    public BigDecimal getPiIdSemana() {
        return this.piIdSemana;
    }
    
    public void setPiIdSemana(BigDecimal piIdSemana) {
        this.piIdSemana = piIdSemana;
    }

    
    @Column(name="MIV_ES_PRIMER_CICLO", length=1)
    public String getMivEsPrimerCiclo() {
        return this.mivEsPrimerCiclo;
    }
    
    public void setMivEsPrimerCiclo(String mivEsPrimerCiclo) {
        this.mivEsPrimerCiclo = mivEsPrimerCiclo;
    }

    
    @Column(name="MIV_ES_FORMACION_BASICA", length=1)
    public String getMivEsFormacionBasica() {
        return this.mivEsFormacionBasica;
    }
    
    public void setMivEsFormacionBasica(String mivEsFormacionBasica) {
        this.mivEsFormacionBasica = mivEsFormacionBasica;
    }

    
    @Column(name="MIN_NUM_SEMANA_FINAL", precision=22, scale=0)
    public BigDecimal getMinNumSemanaFinal() {
        return this.minNumSemanaFinal;
    }
    
    public void setMinNumSemanaFinal(BigDecimal minNumSemanaFinal) {
        this.minNumSemanaFinal = minNumSemanaFinal;
    }

    
    @Column(name="MIV_VISIBLE", precision=22, scale=0)
    public BigDecimal getMivVisible() {
        return this.mivVisible;
    }
    
    public void setMivVisible(BigDecimal mivVisible) {
        this.mivVisible = mivVisible;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MIV_FECHA_CREACION_EVA", length=7)
    public Date getMivFechaCreacionEva() {
        return this.mivFechaCreacionEva;
    }
    
    public void setMivFechaCreacionEva(Date mivFechaCreacionEva) {
        this.mivFechaCreacionEva = mivFechaCreacionEva;
    }

    
    @Column(name="MIV_SEMANA_CREACION", precision=22, scale=0)
    public BigDecimal getMivSemanaCreacion() {
        return this.mivSemanaCreacion;
    }
    
    public void setMivSemanaCreacion(BigDecimal mivSemanaCreacion) {
        this.mivSemanaCreacion = mivSemanaCreacion;
    }

    
    @Column(name="MIV_ID_LESSON_PAGE", precision=22, scale=0)
    public BigDecimal getMivIdLessonPage() {
        return this.mivIdLessonPage;
    }
    
    public void setMivIdLessonPage(BigDecimal mivIdLessonPage) {
        this.mivIdLessonPage = mivIdLessonPage;
    }

    
    @Column(name="MIV_CANT_VIDEOS", precision=22, scale=0)
    public BigDecimal getMivCantVideos() {
        return this.mivCantVideos;
    }
    
    public void setMivCantVideos(BigDecimal mivCantVideos) {
        this.mivCantVideos = mivCantVideos;
    }

    
    @Column(name="MIV_URL_MICROVIDEO", length=1000)
    public String getMivUrlMicrovideo() {
        return this.mivUrlMicrovideo;
    }
    
    public void setMivUrlMicrovideo(String mivUrlMicrovideo) {
        this.mivUrlMicrovideo = mivUrlMicrovideo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MIV_FECHA_ENROLAMIENTO_EVA", length=7)
    public Date getMivFechaEnrolamientoEva() {
        return this.mivFechaEnrolamientoEva;
    }
    
    public void setMivFechaEnrolamientoEva(Date mivFechaEnrolamientoEva) {
        this.mivFechaEnrolamientoEva = mivFechaEnrolamientoEva;
    }

    
    @Column(name="MIV_VIGENTE", length=1)
    public Character getMivVigente() {
        return this.mivVigente;
    }
    
    public void setMivVigente(Character mivVigente) {
        this.mivVigente = mivVigente;
    }

    
    @Column(name="MIV_ID_PAGE", precision=22, scale=0)
    public BigDecimal getMivIdPage() {
        return this.mivIdPage;
    }
    
    public void setMivIdPage(BigDecimal mivIdPage) {
        this.mivIdPage = mivIdPage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tevaMicrovideos")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }




}


