package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TheActividadesDocEvaDet generated by hbm2java
 */
@Entity
@Table(name="THE_ACTIVIDADES_DOC_EVA_DET"
    ,schema="ESQ_SIEC"
)
public class TheActividadesDocEvaDet  implements java.io.Serializable {


     private BigDecimal aedId;
     private TdiComponenteEducativo tdiComponenteEducativo;
     private TdiOfertaNsga tdiOfertaNsga;
     private TdiArea tdiArea;
     private TdiDepartamento tdiDepartamento;
     private TdiDocente tdiDocente;
     private TdiIndicador tdiIndicador;
     private TdiModalidad tdiModalidad;
     private TdiNivelAcademico tdiNivelAcademico;
     private TdiPeriodo tdiPeriodo;
     private TdiSeccionDepartamental tdiSeccionDepartamental;
     private TdiGlosario tdiGlosario;
     private TevaMicrovideos tevaMicrovideos;
     private TdiObservacionPersonalizada tdiObservacionPersonalizada;
     private TdiParametrosIndicador tdiParametrosIndicador;
     private TheActividadesDocEvaCab theActividadesDocEvaCab;
     private BigDecimal aedNumeracionActividad;
     private Date aedFechaActividad;
     private BigDecimal aedCantidad;
     private BigDecimal aedCumplimiento;
     private BigDecimal aedSeguimiento;
     private BigDecimal aedSobrantes;
     private BigDecimal aedCalificacion;
     private String aedOfertadaParaPrimerCiclo;
     private String aedOfertadaComoFb;
     private String aedOfertadaComoPracticum;
     private Date aedFechaCreacionSiec;
     private String aedUsuarioCreaSiec;
     private String aedUsuarioActualizacionSiec;
     private Date aedFechaActualizacionSiec;
     private BigDecimal aedNumSmnEva;
     private BigDecimal aedNumSeccionEva;
     private BigDecimal aedIdCursoEva;
     private BigDecimal aedBimestreEva3;
     private String aedInteractuaConEstudiantes;
     private BigDecimal aedTotalPostDocente;
     private Date aedFechaPrimerPostEstudian;
     private BigDecimal aedTotalPostEstudiantes;
     private BigDecimal aedNoCumplimiento;
     private BigDecimal cevId;
     private BigDecimal aevId;
     private String aedVigente;
     private BigDecimal fevId;
     private BigDecimal piIdSem0;
     private Date aedFechaEnrolamiento;
     private BigDecimal dpiId;
     private BigDecimal aedJustificacionId;

    public TheActividadesDocEvaDet() {
    }

	
    public TheActividadesDocEvaDet(BigDecimal aedId, TdiComponenteEducativo tdiComponenteEducativo, TdiOfertaNsga tdiOfertaNsga, TdiArea tdiArea, TdiDepartamento tdiDepartamento, TdiDocente tdiDocente, TdiIndicador tdiIndicador, TdiModalidad tdiModalidad, TdiNivelAcademico tdiNivelAcademico, TdiPeriodo tdiPeriodo, TdiSeccionDepartamental tdiSeccionDepartamental, TdiGlosario tdiGlosario, TdiParametrosIndicador tdiParametrosIndicador, TheActividadesDocEvaCab theActividadesDocEvaCab, BigDecimal aedCantidad, BigDecimal aedCumplimiento, BigDecimal aedSeguimiento, BigDecimal aedSobrantes, BigDecimal aedCalificacion, Date aedFechaCreacionSiec, String aedUsuarioCreaSiec, String aedInteractuaConEstudiantes, BigDecimal aedTotalPostDocente, BigDecimal aedTotalPostEstudiantes) {
        this.aedId = aedId;
        this.tdiComponenteEducativo = tdiComponenteEducativo;
        this.tdiOfertaNsga = tdiOfertaNsga;
        this.tdiArea = tdiArea;
        this.tdiDepartamento = tdiDepartamento;
        this.tdiDocente = tdiDocente;
        this.tdiIndicador = tdiIndicador;
        this.tdiModalidad = tdiModalidad;
        this.tdiNivelAcademico = tdiNivelAcademico;
        this.tdiPeriodo = tdiPeriodo;
        this.tdiSeccionDepartamental = tdiSeccionDepartamental;
        this.tdiGlosario = tdiGlosario;
        this.tdiParametrosIndicador = tdiParametrosIndicador;
        this.theActividadesDocEvaCab = theActividadesDocEvaCab;
        this.aedCantidad = aedCantidad;
        this.aedCumplimiento = aedCumplimiento;
        this.aedSeguimiento = aedSeguimiento;
        this.aedSobrantes = aedSobrantes;
        this.aedCalificacion = aedCalificacion;
        this.aedFechaCreacionSiec = aedFechaCreacionSiec;
        this.aedUsuarioCreaSiec = aedUsuarioCreaSiec;
        this.aedInteractuaConEstudiantes = aedInteractuaConEstudiantes;
        this.aedTotalPostDocente = aedTotalPostDocente;
        this.aedTotalPostEstudiantes = aedTotalPostEstudiantes;
    }
    public TheActividadesDocEvaDet(BigDecimal aedId, TdiComponenteEducativo tdiComponenteEducativo, TdiOfertaNsga tdiOfertaNsga, TdiArea tdiArea, TdiDepartamento tdiDepartamento, TdiDocente tdiDocente, TdiIndicador tdiIndicador, TdiModalidad tdiModalidad, TdiNivelAcademico tdiNivelAcademico, TdiPeriodo tdiPeriodo, TdiSeccionDepartamental tdiSeccionDepartamental, TdiGlosario tdiGlosario, TevaMicrovideos tevaMicrovideos, TdiObservacionPersonalizada tdiObservacionPersonalizada, TdiParametrosIndicador tdiParametrosIndicador, TheActividadesDocEvaCab theActividadesDocEvaCab, BigDecimal aedNumeracionActividad, Date aedFechaActividad, BigDecimal aedCantidad, BigDecimal aedCumplimiento, BigDecimal aedSeguimiento, BigDecimal aedSobrantes, BigDecimal aedCalificacion, String aedOfertadaParaPrimerCiclo, String aedOfertadaComoFb, String aedOfertadaComoPracticum, Date aedFechaCreacionSiec, String aedUsuarioCreaSiec, String aedUsuarioActualizacionSiec, Date aedFechaActualizacionSiec, BigDecimal aedNumSmnEva, BigDecimal aedNumSeccionEva, BigDecimal aedIdCursoEva, BigDecimal aedBimestreEva3, String aedInteractuaConEstudiantes, BigDecimal aedTotalPostDocente, Date aedFechaPrimerPostEstudian, BigDecimal aedTotalPostEstudiantes, BigDecimal aedNoCumplimiento, BigDecimal cevId, BigDecimal aevId, String aedVigente, BigDecimal fevId, BigDecimal piIdSem0, Date aedFechaEnrolamiento, BigDecimal dpiId, BigDecimal aedJustificacionId) {
       this.aedId = aedId;
       this.tdiComponenteEducativo = tdiComponenteEducativo;
       this.tdiOfertaNsga = tdiOfertaNsga;
       this.tdiArea = tdiArea;
       this.tdiDepartamento = tdiDepartamento;
       this.tdiDocente = tdiDocente;
       this.tdiIndicador = tdiIndicador;
       this.tdiModalidad = tdiModalidad;
       this.tdiNivelAcademico = tdiNivelAcademico;
       this.tdiPeriodo = tdiPeriodo;
       this.tdiSeccionDepartamental = tdiSeccionDepartamental;
       this.tdiGlosario = tdiGlosario;
       this.tevaMicrovideos = tevaMicrovideos;
       this.tdiObservacionPersonalizada = tdiObservacionPersonalizada;
       this.tdiParametrosIndicador = tdiParametrosIndicador;
       this.theActividadesDocEvaCab = theActividadesDocEvaCab;
       this.aedNumeracionActividad = aedNumeracionActividad;
       this.aedFechaActividad = aedFechaActividad;
       this.aedCantidad = aedCantidad;
       this.aedCumplimiento = aedCumplimiento;
       this.aedSeguimiento = aedSeguimiento;
       this.aedSobrantes = aedSobrantes;
       this.aedCalificacion = aedCalificacion;
       this.aedOfertadaParaPrimerCiclo = aedOfertadaParaPrimerCiclo;
       this.aedOfertadaComoFb = aedOfertadaComoFb;
       this.aedOfertadaComoPracticum = aedOfertadaComoPracticum;
       this.aedFechaCreacionSiec = aedFechaCreacionSiec;
       this.aedUsuarioCreaSiec = aedUsuarioCreaSiec;
       this.aedUsuarioActualizacionSiec = aedUsuarioActualizacionSiec;
       this.aedFechaActualizacionSiec = aedFechaActualizacionSiec;
       this.aedNumSmnEva = aedNumSmnEva;
       this.aedNumSeccionEva = aedNumSeccionEva;
       this.aedIdCursoEva = aedIdCursoEva;
       this.aedBimestreEva3 = aedBimestreEva3;
       this.aedInteractuaConEstudiantes = aedInteractuaConEstudiantes;
       this.aedTotalPostDocente = aedTotalPostDocente;
       this.aedFechaPrimerPostEstudian = aedFechaPrimerPostEstudian;
       this.aedTotalPostEstudiantes = aedTotalPostEstudiantes;
       this.aedNoCumplimiento = aedNoCumplimiento;
       this.cevId = cevId;
       this.aevId = aevId;
       this.aedVigente = aedVigente;
       this.fevId = fevId;
       this.piIdSem0 = piIdSem0;
       this.aedFechaEnrolamiento = aedFechaEnrolamiento;
       this.dpiId = dpiId;
       this.aedJustificacionId = aedJustificacionId;
    }
   
     @Id 

    
    @Column(name="AED_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getAedId() {
        return this.aedId;
    }
    
    public void setAedId(BigDecimal aedId) {
        this.aedId = aedId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CE_ID", nullable=false)
    public TdiComponenteEducativo getTdiComponenteEducativo() {
        return this.tdiComponenteEducativo;
    }
    
    public void setTdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo) {
        this.tdiComponenteEducativo = tdiComponenteEducativo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ONS_ID", nullable=false)
    public TdiOfertaNsga getTdiOfertaNsga() {
        return this.tdiOfertaNsga;
    }
    
    public void setTdiOfertaNsga(TdiOfertaNsga tdiOfertaNsga) {
        this.tdiOfertaNsga = tdiOfertaNsga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AR_ID_CE", nullable=false)
    public TdiArea getTdiArea() {
        return this.tdiArea;
    }
    
    public void setTdiArea(TdiArea tdiArea) {
        this.tdiArea = tdiArea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DE_ID_CE", nullable=false)
    public TdiDepartamento getTdiDepartamento() {
        return this.tdiDepartamento;
    }
    
    public void setTdiDepartamento(TdiDepartamento tdiDepartamento) {
        this.tdiDepartamento = tdiDepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DO_ID", nullable=false)
    public TdiDocente getTdiDocente() {
        return this.tdiDocente;
    }
    
    public void setTdiDocente(TdiDocente tdiDocente) {
        this.tdiDocente = tdiDocente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ID", nullable=false)
    public TdiIndicador getTdiIndicador() {
        return this.tdiIndicador;
    }
    
    public void setTdiIndicador(TdiIndicador tdiIndicador) {
        this.tdiIndicador = tdiIndicador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MO_ID", nullable=false)
    public TdiModalidad getTdiModalidad() {
        return this.tdiModalidad;
    }
    
    public void setTdiModalidad(TdiModalidad tdiModalidad) {
        this.tdiModalidad = tdiModalidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NA_ID", nullable=false)
    public TdiNivelAcademico getTdiNivelAcademico() {
        return this.tdiNivelAcademico;
    }
    
    public void setTdiNivelAcademico(TdiNivelAcademico tdiNivelAcademico) {
        this.tdiNivelAcademico = tdiNivelAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PE_ID", nullable=false)
    public TdiPeriodo getTdiPeriodo() {
        return this.tdiPeriodo;
    }
    
    public void setTdiPeriodo(TdiPeriodo tdiPeriodo) {
        this.tdiPeriodo = tdiPeriodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SE_ID_CE", nullable=false)
    public TdiSeccionDepartamental getTdiSeccionDepartamental() {
        return this.tdiSeccionDepartamental;
    }
    
    public void setTdiSeccionDepartamental(TdiSeccionDepartamental tdiSeccionDepartamental) {
        this.tdiSeccionDepartamental = tdiSeccionDepartamental;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AED_PARALELO_ID", nullable=false)
    public TdiGlosario getTdiGlosario() {
        return this.tdiGlosario;
    }
    
    public void setTdiGlosario(TdiGlosario tdiGlosario) {
        this.tdiGlosario = tdiGlosario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MIV_ID")
    public TevaMicrovideos getTevaMicrovideos() {
        return this.tevaMicrovideos;
    }
    
    public void setTevaMicrovideos(TevaMicrovideos tevaMicrovideos) {
        this.tevaMicrovideos = tevaMicrovideos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AED_OBSERVACIONES_ID")
    public TdiObservacionPersonalizada getTdiObservacionPersonalizada() {
        return this.tdiObservacionPersonalizada;
    }
    
    public void setTdiObservacionPersonalizada(TdiObservacionPersonalizada tdiObservacionPersonalizada) {
        this.tdiObservacionPersonalizada = tdiObservacionPersonalizada;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PI_ID", nullable=false)
    public TdiParametrosIndicador getTdiParametrosIndicador() {
        return this.tdiParametrosIndicador;
    }
    
    public void setTdiParametrosIndicador(TdiParametrosIndicador tdiParametrosIndicador) {
        this.tdiParametrosIndicador = tdiParametrosIndicador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AEC_ID", nullable=false)
    public TheActividadesDocEvaCab getTheActividadesDocEvaCab() {
        return this.theActividadesDocEvaCab;
    }
    
    public void setTheActividadesDocEvaCab(TheActividadesDocEvaCab theActividadesDocEvaCab) {
        this.theActividadesDocEvaCab = theActividadesDocEvaCab;
    }

    
    @Column(name="AED_NUMERACION_ACTIVIDAD", precision=22, scale=0)
    public BigDecimal getAedNumeracionActividad() {
        return this.aedNumeracionActividad;
    }
    
    public void setAedNumeracionActividad(BigDecimal aedNumeracionActividad) {
        this.aedNumeracionActividad = aedNumeracionActividad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AED_FECHA_ACTIVIDAD", length=7)
    public Date getAedFechaActividad() {
        return this.aedFechaActividad;
    }
    
    public void setAedFechaActividad(Date aedFechaActividad) {
        this.aedFechaActividad = aedFechaActividad;
    }

    
    @Column(name="AED_CANTIDAD", nullable=false, precision=22, scale=0)
    public BigDecimal getAedCantidad() {
        return this.aedCantidad;
    }
    
    public void setAedCantidad(BigDecimal aedCantidad) {
        this.aedCantidad = aedCantidad;
    }

    
    @Column(name="AED_CUMPLIMIENTO", nullable=false, precision=22, scale=0)
    public BigDecimal getAedCumplimiento() {
        return this.aedCumplimiento;
    }
    
    public void setAedCumplimiento(BigDecimal aedCumplimiento) {
        this.aedCumplimiento = aedCumplimiento;
    }

    
    @Column(name="AED_SEGUIMIENTO", nullable=false, precision=22, scale=0)
    public BigDecimal getAedSeguimiento() {
        return this.aedSeguimiento;
    }
    
    public void setAedSeguimiento(BigDecimal aedSeguimiento) {
        this.aedSeguimiento = aedSeguimiento;
    }

    
    @Column(name="AED_SOBRANTES", nullable=false, precision=22, scale=0)
    public BigDecimal getAedSobrantes() {
        return this.aedSobrantes;
    }
    
    public void setAedSobrantes(BigDecimal aedSobrantes) {
        this.aedSobrantes = aedSobrantes;
    }

    
    @Column(name="AED_CALIFICACION", nullable=false, precision=22, scale=0)
    public BigDecimal getAedCalificacion() {
        return this.aedCalificacion;
    }
    
    public void setAedCalificacion(BigDecimal aedCalificacion) {
        this.aedCalificacion = aedCalificacion;
    }

    
    @Column(name="AED_OFERTADA_PARA_PRIMER_CICLO", length=1)
    public String getAedOfertadaParaPrimerCiclo() {
        return this.aedOfertadaParaPrimerCiclo;
    }
    
    public void setAedOfertadaParaPrimerCiclo(String aedOfertadaParaPrimerCiclo) {
        this.aedOfertadaParaPrimerCiclo = aedOfertadaParaPrimerCiclo;
    }

    
    @Column(name="AED_OFERTADA_COMO_FB", length=1)
    public String getAedOfertadaComoFb() {
        return this.aedOfertadaComoFb;
    }
    
    public void setAedOfertadaComoFb(String aedOfertadaComoFb) {
        this.aedOfertadaComoFb = aedOfertadaComoFb;
    }

    
    @Column(name="AED_OFERTADA_COMO_PRACTICUM", length=1)
    public String getAedOfertadaComoPracticum() {
        return this.aedOfertadaComoPracticum;
    }
    
    public void setAedOfertadaComoPracticum(String aedOfertadaComoPracticum) {
        this.aedOfertadaComoPracticum = aedOfertadaComoPracticum;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AED_FECHA_CREACION_SIEC", nullable=false, length=7)
    public Date getAedFechaCreacionSiec() {
        return this.aedFechaCreacionSiec;
    }
    
    public void setAedFechaCreacionSiec(Date aedFechaCreacionSiec) {
        this.aedFechaCreacionSiec = aedFechaCreacionSiec;
    }

    
    @Column(name="AED_USUARIO_CREA_SIEC", nullable=false, length=100)
    public String getAedUsuarioCreaSiec() {
        return this.aedUsuarioCreaSiec;
    }
    
    public void setAedUsuarioCreaSiec(String aedUsuarioCreaSiec) {
        this.aedUsuarioCreaSiec = aedUsuarioCreaSiec;
    }

    
    @Column(name="AED_USUARIO_ACTUALIZACION_SIEC", length=100)
    public String getAedUsuarioActualizacionSiec() {
        return this.aedUsuarioActualizacionSiec;
    }
    
    public void setAedUsuarioActualizacionSiec(String aedUsuarioActualizacionSiec) {
        this.aedUsuarioActualizacionSiec = aedUsuarioActualizacionSiec;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AED_FECHA_ACTUALIZACION_SIEC", length=7)
    public Date getAedFechaActualizacionSiec() {
        return this.aedFechaActualizacionSiec;
    }
    
    public void setAedFechaActualizacionSiec(Date aedFechaActualizacionSiec) {
        this.aedFechaActualizacionSiec = aedFechaActualizacionSiec;
    }

    
    @Column(name="AED_NUM_SMN_EVA", precision=22, scale=0)
    public BigDecimal getAedNumSmnEva() {
        return this.aedNumSmnEva;
    }
    
    public void setAedNumSmnEva(BigDecimal aedNumSmnEva) {
        this.aedNumSmnEva = aedNumSmnEva;
    }

    
    @Column(name="AED_NUM_SECCION_EVA", precision=22, scale=0)
    public BigDecimal getAedNumSeccionEva() {
        return this.aedNumSeccionEva;
    }
    
    public void setAedNumSeccionEva(BigDecimal aedNumSeccionEva) {
        this.aedNumSeccionEva = aedNumSeccionEva;
    }

    
    @Column(name="AED_ID_CURSO_EVA", precision=22, scale=0)
    public BigDecimal getAedIdCursoEva() {
        return this.aedIdCursoEva;
    }
    
    public void setAedIdCursoEva(BigDecimal aedIdCursoEva) {
        this.aedIdCursoEva = aedIdCursoEva;
    }

    
    @Column(name="AED_BIMESTRE_EVA3", precision=22, scale=0)
    public BigDecimal getAedBimestreEva3() {
        return this.aedBimestreEva3;
    }
    
    public void setAedBimestreEva3(BigDecimal aedBimestreEva3) {
        this.aedBimestreEva3 = aedBimestreEva3;
    }

    
    @Column(name="AED_INTERACTUA_CON_ESTUDIANTES", nullable=false, length=1)
    public String getAedInteractuaConEstudiantes() {
        return this.aedInteractuaConEstudiantes;
    }
    
    public void setAedInteractuaConEstudiantes(String aedInteractuaConEstudiantes) {
        this.aedInteractuaConEstudiantes = aedInteractuaConEstudiantes;
    }

    
    @Column(name="AED_TOTAL_POST_DOCENTE", nullable=false, precision=22, scale=0)
    public BigDecimal getAedTotalPostDocente() {
        return this.aedTotalPostDocente;
    }
    
    public void setAedTotalPostDocente(BigDecimal aedTotalPostDocente) {
        this.aedTotalPostDocente = aedTotalPostDocente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AED_FECHA_PRIMER_POST_ESTUDIAN", length=7)
    public Date getAedFechaPrimerPostEstudian() {
        return this.aedFechaPrimerPostEstudian;
    }
    
    public void setAedFechaPrimerPostEstudian(Date aedFechaPrimerPostEstudian) {
        this.aedFechaPrimerPostEstudian = aedFechaPrimerPostEstudian;
    }

    
    @Column(name="AED_TOTAL_POST_ESTUDIANTES", nullable=false, precision=22, scale=0)
    public BigDecimal getAedTotalPostEstudiantes() {
        return this.aedTotalPostEstudiantes;
    }
    
    public void setAedTotalPostEstudiantes(BigDecimal aedTotalPostEstudiantes) {
        this.aedTotalPostEstudiantes = aedTotalPostEstudiantes;
    }

    
    @Column(name="AED_NO_CUMPLIMIENTO", precision=22, scale=0)
    public BigDecimal getAedNoCumplimiento() {
        return this.aedNoCumplimiento;
    }
    
    public void setAedNoCumplimiento(BigDecimal aedNoCumplimiento) {
        this.aedNoCumplimiento = aedNoCumplimiento;
    }

    
    @Column(name="CEV_ID", precision=22, scale=0)
    public BigDecimal getCevId() {
        return this.cevId;
    }
    
    public void setCevId(BigDecimal cevId) {
        this.cevId = cevId;
    }

    
    @Column(name="AEV_ID", precision=22, scale=0)
    public BigDecimal getAevId() {
        return this.aevId;
    }
    
    public void setAevId(BigDecimal aevId) {
        this.aevId = aevId;
    }

    
    @Column(name="AED_VIGENTE", length=1)
    public String getAedVigente() {
        return this.aedVigente;
    }
    
    public void setAedVigente(String aedVigente) {
        this.aedVigente = aedVigente;
    }

    
    @Column(name="FEV_ID", precision=22, scale=0)
    public BigDecimal getFevId() {
        return this.fevId;
    }
    
    public void setFevId(BigDecimal fevId) {
        this.fevId = fevId;
    }

    
    @Column(name="PI_ID_SEM0", precision=22, scale=0)
    public BigDecimal getPiIdSem0() {
        return this.piIdSem0;
    }
    
    public void setPiIdSem0(BigDecimal piIdSem0) {
        this.piIdSem0 = piIdSem0;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AED_FECHA_ENROLAMIENTO", length=7)
    public Date getAedFechaEnrolamiento() {
        return this.aedFechaEnrolamiento;
    }
    
    public void setAedFechaEnrolamiento(Date aedFechaEnrolamiento) {
        this.aedFechaEnrolamiento = aedFechaEnrolamiento;
    }

    
    @Column(name="DPI_ID", precision=22, scale=0)
    public BigDecimal getDpiId() {
        return this.dpiId;
    }
    
    public void setDpiId(BigDecimal dpiId) {
        this.dpiId = dpiId;
    }

    
    @Column(name="AED_JUSTIFICACION_ID", precision=22, scale=0)
    public BigDecimal getAedJustificacionId() {
        return this.aedJustificacionId;
    }
    
    public void setAedJustificacionId(BigDecimal aedJustificacionId) {
        this.aedJustificacionId = aedJustificacionId;
    }




}


