package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TheActividadesEvaAvance generated by hbm2java
 */
@Entity
@Table(name="THE_ACTIVIDADES_EVA_AVANCE"
    ,schema="ESQ_SIEC"
)
public class TheActividadesEvaAvance  implements java.io.Serializable {


     private BigDecimal aeaId;
     private TdiComponenteEducativo tdiComponenteEducativo;
     private TdiOfertaNsga tdiOfertaNsga;
     private TdiArea tdiArea;
     private TdiDepartamento tdiDepartamento;
     private TdiDocente tdiDocente;
     private TdiModalidad tdiModalidad;
     private TdiNivelAcademico tdiNivelAcademico;
     private TdiPeriodo tdiPeriodo;
     private TdiSeccionDepartamental tdiSeccionDepartamental;
     private TdiGlosario tdiGlosario;
     private TdiPeriodoDetalle tdiPeriodoDetalle;
     private String aeaFrecuenciaNumeracion;
     private String aeaFrecuencia;
     private BigDecimal aeaNumeracion;
     private BigDecimal aecExcepcion;
     private BigDecimal aeaObjMicro1er;
     private BigDecimal aeaTotalMicro1er;
     private BigDecimal aeaCumplimientoMicro1er;
     private BigDecimal aeaSeguimientoMicro1er;
     private BigDecimal aeaPorcObtMicro1er;
     private String aeaSemaforoMicro1er;
     private BigDecimal aeaObjMicro2do;
     private BigDecimal aeaTotalMicro2do;
     private BigDecimal aeaCumplimientoMicro2do;
     private BigDecimal aeaSeguimientoMicro2do;
     private BigDecimal aeaPorcObtMicro2do;
     private String aeaSemaforoMicro2do;
     private BigDecimal aeaObjChatAcad;
     private BigDecimal aeaTotalChatAcad;
     private BigDecimal aeaCumplimientoChatAcad;
     private BigDecimal aeaSeguimientoChatAcad;
     private BigDecimal aeaPorcObtChatAcad;
     private String aeaSemaforoChatAcad;
     private BigDecimal aeaObjChatTut;
     private BigDecimal aeaTotalChatTut;
     private BigDecimal aeaCumplimientoChatTut;
     private BigDecimal aeaSeguimientoChatTut;
     private BigDecimal aeaPorcObtChatTut;
     private String aeaSemaforoChatTut;
     private BigDecimal aeaObjCuesti;
     private BigDecimal aeaTotalCuesti;
     private BigDecimal aeaCumplimientoCuesti;
     private BigDecimal aeaSeguimientoCuesti;
     private BigDecimal aeaPorcObtCuesti;
     private String aeaSemaforoCuesti;
     private BigDecimal aeaObjForo;
     private BigDecimal aeaTotalForo;
     private BigDecimal aeaCumplimientoForo;
     private BigDecimal aeaSeguimientoForo;
     private BigDecimal aeaPorcObtForo;
     private String aeaSemaforoForo;
     private BigDecimal aeaObjAnuncio;
     private BigDecimal aeaTotalAnuncio;
     private BigDecimal aeaCumplimientoAnuncio;
     private BigDecimal aeaSeguimientoAnuncio;
     private BigDecimal aeaPorcObtAnuncio;
     private String aeaSemaforoAnuncio;
     private Date aeaFechaCreacionSiec;
     private Date aeaFechaUltActSiec;
     private String aeaProceso;
     private BigDecimal aeaTotMatriculados;
     private BigDecimal aeaCursoIdEva;

    public TheActividadesEvaAvance() {
    }

	
    public TheActividadesEvaAvance(BigDecimal aeaId, TdiComponenteEducativo tdiComponenteEducativo, TdiOfertaNsga tdiOfertaNsga, TdiArea tdiArea, TdiDepartamento tdiDepartamento, TdiDocente tdiDocente, TdiModalidad tdiModalidad, TdiNivelAcademico tdiNivelAcademico, TdiPeriodo tdiPeriodo, TdiSeccionDepartamental tdiSeccionDepartamental, TdiGlosario tdiGlosario, String aeaFrecuenciaNumeracion) {
        this.aeaId = aeaId;
        this.tdiComponenteEducativo = tdiComponenteEducativo;
        this.tdiOfertaNsga = tdiOfertaNsga;
        this.tdiArea = tdiArea;
        this.tdiDepartamento = tdiDepartamento;
        this.tdiDocente = tdiDocente;
        this.tdiModalidad = tdiModalidad;
        this.tdiNivelAcademico = tdiNivelAcademico;
        this.tdiPeriodo = tdiPeriodo;
        this.tdiSeccionDepartamental = tdiSeccionDepartamental;
        this.tdiGlosario = tdiGlosario;
        this.aeaFrecuenciaNumeracion = aeaFrecuenciaNumeracion;
    }
    public TheActividadesEvaAvance(BigDecimal aeaId, TdiComponenteEducativo tdiComponenteEducativo, TdiOfertaNsga tdiOfertaNsga, TdiArea tdiArea, TdiDepartamento tdiDepartamento, TdiDocente tdiDocente, TdiModalidad tdiModalidad, TdiNivelAcademico tdiNivelAcademico, TdiPeriodo tdiPeriodo, TdiSeccionDepartamental tdiSeccionDepartamental, TdiGlosario tdiGlosario, TdiPeriodoDetalle tdiPeriodoDetalle, String aeaFrecuenciaNumeracion, String aeaFrecuencia, BigDecimal aeaNumeracion, BigDecimal aecExcepcion, BigDecimal aeaObjMicro1er, BigDecimal aeaTotalMicro1er, BigDecimal aeaCumplimientoMicro1er, BigDecimal aeaSeguimientoMicro1er, BigDecimal aeaPorcObtMicro1er, String aeaSemaforoMicro1er, BigDecimal aeaObjMicro2do, BigDecimal aeaTotalMicro2do, BigDecimal aeaCumplimientoMicro2do, BigDecimal aeaSeguimientoMicro2do, BigDecimal aeaPorcObtMicro2do, String aeaSemaforoMicro2do, BigDecimal aeaObjChatAcad, BigDecimal aeaTotalChatAcad, BigDecimal aeaCumplimientoChatAcad, BigDecimal aeaSeguimientoChatAcad, BigDecimal aeaPorcObtChatAcad, String aeaSemaforoChatAcad, BigDecimal aeaObjChatTut, BigDecimal aeaTotalChatTut, BigDecimal aeaCumplimientoChatTut, BigDecimal aeaSeguimientoChatTut, BigDecimal aeaPorcObtChatTut, String aeaSemaforoChatTut, BigDecimal aeaObjCuesti, BigDecimal aeaTotalCuesti, BigDecimal aeaCumplimientoCuesti, BigDecimal aeaSeguimientoCuesti, BigDecimal aeaPorcObtCuesti, String aeaSemaforoCuesti, BigDecimal aeaObjForo, BigDecimal aeaTotalForo, BigDecimal aeaCumplimientoForo, BigDecimal aeaSeguimientoForo, BigDecimal aeaPorcObtForo, String aeaSemaforoForo, BigDecimal aeaObjAnuncio, BigDecimal aeaTotalAnuncio, BigDecimal aeaCumplimientoAnuncio, BigDecimal aeaSeguimientoAnuncio, BigDecimal aeaPorcObtAnuncio, String aeaSemaforoAnuncio, Date aeaFechaCreacionSiec, Date aeaFechaUltActSiec, String aeaProceso, BigDecimal aeaTotMatriculados, BigDecimal aeaCursoIdEva) {
       this.aeaId = aeaId;
       this.tdiComponenteEducativo = tdiComponenteEducativo;
       this.tdiOfertaNsga = tdiOfertaNsga;
       this.tdiArea = tdiArea;
       this.tdiDepartamento = tdiDepartamento;
       this.tdiDocente = tdiDocente;
       this.tdiModalidad = tdiModalidad;
       this.tdiNivelAcademico = tdiNivelAcademico;
       this.tdiPeriodo = tdiPeriodo;
       this.tdiSeccionDepartamental = tdiSeccionDepartamental;
       this.tdiGlosario = tdiGlosario;
       this.tdiPeriodoDetalle = tdiPeriodoDetalle;
       this.aeaFrecuenciaNumeracion = aeaFrecuenciaNumeracion;
       this.aeaFrecuencia = aeaFrecuencia;
       this.aeaNumeracion = aeaNumeracion;
       this.aecExcepcion = aecExcepcion;
       this.aeaObjMicro1er = aeaObjMicro1er;
       this.aeaTotalMicro1er = aeaTotalMicro1er;
       this.aeaCumplimientoMicro1er = aeaCumplimientoMicro1er;
       this.aeaSeguimientoMicro1er = aeaSeguimientoMicro1er;
       this.aeaPorcObtMicro1er = aeaPorcObtMicro1er;
       this.aeaSemaforoMicro1er = aeaSemaforoMicro1er;
       this.aeaObjMicro2do = aeaObjMicro2do;
       this.aeaTotalMicro2do = aeaTotalMicro2do;
       this.aeaCumplimientoMicro2do = aeaCumplimientoMicro2do;
       this.aeaSeguimientoMicro2do = aeaSeguimientoMicro2do;
       this.aeaPorcObtMicro2do = aeaPorcObtMicro2do;
       this.aeaSemaforoMicro2do = aeaSemaforoMicro2do;
       this.aeaObjChatAcad = aeaObjChatAcad;
       this.aeaTotalChatAcad = aeaTotalChatAcad;
       this.aeaCumplimientoChatAcad = aeaCumplimientoChatAcad;
       this.aeaSeguimientoChatAcad = aeaSeguimientoChatAcad;
       this.aeaPorcObtChatAcad = aeaPorcObtChatAcad;
       this.aeaSemaforoChatAcad = aeaSemaforoChatAcad;
       this.aeaObjChatTut = aeaObjChatTut;
       this.aeaTotalChatTut = aeaTotalChatTut;
       this.aeaCumplimientoChatTut = aeaCumplimientoChatTut;
       this.aeaSeguimientoChatTut = aeaSeguimientoChatTut;
       this.aeaPorcObtChatTut = aeaPorcObtChatTut;
       this.aeaSemaforoChatTut = aeaSemaforoChatTut;
       this.aeaObjCuesti = aeaObjCuesti;
       this.aeaTotalCuesti = aeaTotalCuesti;
       this.aeaCumplimientoCuesti = aeaCumplimientoCuesti;
       this.aeaSeguimientoCuesti = aeaSeguimientoCuesti;
       this.aeaPorcObtCuesti = aeaPorcObtCuesti;
       this.aeaSemaforoCuesti = aeaSemaforoCuesti;
       this.aeaObjForo = aeaObjForo;
       this.aeaTotalForo = aeaTotalForo;
       this.aeaCumplimientoForo = aeaCumplimientoForo;
       this.aeaSeguimientoForo = aeaSeguimientoForo;
       this.aeaPorcObtForo = aeaPorcObtForo;
       this.aeaSemaforoForo = aeaSemaforoForo;
       this.aeaObjAnuncio = aeaObjAnuncio;
       this.aeaTotalAnuncio = aeaTotalAnuncio;
       this.aeaCumplimientoAnuncio = aeaCumplimientoAnuncio;
       this.aeaSeguimientoAnuncio = aeaSeguimientoAnuncio;
       this.aeaPorcObtAnuncio = aeaPorcObtAnuncio;
       this.aeaSemaforoAnuncio = aeaSemaforoAnuncio;
       this.aeaFechaCreacionSiec = aeaFechaCreacionSiec;
       this.aeaFechaUltActSiec = aeaFechaUltActSiec;
       this.aeaProceso = aeaProceso;
       this.aeaTotMatriculados = aeaTotMatriculados;
       this.aeaCursoIdEva = aeaCursoIdEva;
    }
   
     @Id 

    
    @Column(name="AEA_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getAeaId() {
        return this.aeaId;
    }
    
    public void setAeaId(BigDecimal aeaId) {
        this.aeaId = aeaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CE_ID", nullable=false)
    public TdiComponenteEducativo getTdiComponenteEducativo() {
        return this.tdiComponenteEducativo;
    }
    
    public void setTdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo) {
        this.tdiComponenteEducativo = tdiComponenteEducativo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ONS_ID", nullable=false)
    public TdiOfertaNsga getTdiOfertaNsga() {
        return this.tdiOfertaNsga;
    }
    
    public void setTdiOfertaNsga(TdiOfertaNsga tdiOfertaNsga) {
        this.tdiOfertaNsga = tdiOfertaNsga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AR_ID_CE", nullable=false)
    public TdiArea getTdiArea() {
        return this.tdiArea;
    }
    
    public void setTdiArea(TdiArea tdiArea) {
        this.tdiArea = tdiArea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DE_ID_CE", nullable=false)
    public TdiDepartamento getTdiDepartamento() {
        return this.tdiDepartamento;
    }
    
    public void setTdiDepartamento(TdiDepartamento tdiDepartamento) {
        this.tdiDepartamento = tdiDepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DO_ID", nullable=false)
    public TdiDocente getTdiDocente() {
        return this.tdiDocente;
    }
    
    public void setTdiDocente(TdiDocente tdiDocente) {
        this.tdiDocente = tdiDocente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MO_ID", nullable=false)
    public TdiModalidad getTdiModalidad() {
        return this.tdiModalidad;
    }
    
    public void setTdiModalidad(TdiModalidad tdiModalidad) {
        this.tdiModalidad = tdiModalidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NA_ID", nullable=false)
    public TdiNivelAcademico getTdiNivelAcademico() {
        return this.tdiNivelAcademico;
    }
    
    public void setTdiNivelAcademico(TdiNivelAcademico tdiNivelAcademico) {
        this.tdiNivelAcademico = tdiNivelAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PE_ID", nullable=false)
    public TdiPeriodo getTdiPeriodo() {
        return this.tdiPeriodo;
    }
    
    public void setTdiPeriodo(TdiPeriodo tdiPeriodo) {
        this.tdiPeriodo = tdiPeriodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SE_ID_CE", nullable=false)
    public TdiSeccionDepartamental getTdiSeccionDepartamental() {
        return this.tdiSeccionDepartamental;
    }
    
    public void setTdiSeccionDepartamental(TdiSeccionDepartamental tdiSeccionDepartamental) {
        this.tdiSeccionDepartamental = tdiSeccionDepartamental;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AEA_PARALELO_ID", nullable=false)
    public TdiGlosario getTdiGlosario() {
        return this.tdiGlosario;
    }
    
    public void setTdiGlosario(TdiGlosario tdiGlosario) {
        this.tdiGlosario = tdiGlosario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PT_ID")
    public TdiPeriodoDetalle getTdiPeriodoDetalle() {
        return this.tdiPeriodoDetalle;
    }
    
    public void setTdiPeriodoDetalle(TdiPeriodoDetalle tdiPeriodoDetalle) {
        this.tdiPeriodoDetalle = tdiPeriodoDetalle;
    }

    
    @Column(name="AEA_FRECUENCIA_NUMERACION", nullable=false, length=5)
    public String getAeaFrecuenciaNumeracion() {
        return this.aeaFrecuenciaNumeracion;
    }
    
    public void setAeaFrecuenciaNumeracion(String aeaFrecuenciaNumeracion) {
        this.aeaFrecuenciaNumeracion = aeaFrecuenciaNumeracion;
    }

    
    @Column(name="AEA_FRECUENCIA", length=5)
    public String getAeaFrecuencia() {
        return this.aeaFrecuencia;
    }
    
    public void setAeaFrecuencia(String aeaFrecuencia) {
        this.aeaFrecuencia = aeaFrecuencia;
    }

    
    @Column(name="AEA_NUMERACION", precision=22, scale=0)
    public BigDecimal getAeaNumeracion() {
        return this.aeaNumeracion;
    }
    
    public void setAeaNumeracion(BigDecimal aeaNumeracion) {
        this.aeaNumeracion = aeaNumeracion;
    }

    
    @Column(name="AEC_EXCEPCION", precision=22, scale=0)
    public BigDecimal getAecExcepcion() {
        return this.aecExcepcion;
    }
    
    public void setAecExcepcion(BigDecimal aecExcepcion) {
        this.aecExcepcion = aecExcepcion;
    }

    
    @Column(name="AEA_OBJ_MICRO_1ER", precision=22, scale=0)
    public BigDecimal getAeaObjMicro1er() {
        return this.aeaObjMicro1er;
    }
    
    public void setAeaObjMicro1er(BigDecimal aeaObjMicro1er) {
        this.aeaObjMicro1er = aeaObjMicro1er;
    }

    
    @Column(name="AEA_TOTAL_MICRO_1ER", precision=22, scale=0)
    public BigDecimal getAeaTotalMicro1er() {
        return this.aeaTotalMicro1er;
    }
    
    public void setAeaTotalMicro1er(BigDecimal aeaTotalMicro1er) {
        this.aeaTotalMicro1er = aeaTotalMicro1er;
    }

    
    @Column(name="AEA_CUMPLIMIENTO_MICRO_1ER", precision=22, scale=0)
    public BigDecimal getAeaCumplimientoMicro1er() {
        return this.aeaCumplimientoMicro1er;
    }
    
    public void setAeaCumplimientoMicro1er(BigDecimal aeaCumplimientoMicro1er) {
        this.aeaCumplimientoMicro1er = aeaCumplimientoMicro1er;
    }

    
    @Column(name="AEA_SEGUIMIENTO_MICRO_1ER", precision=22, scale=0)
    public BigDecimal getAeaSeguimientoMicro1er() {
        return this.aeaSeguimientoMicro1er;
    }
    
    public void setAeaSeguimientoMicro1er(BigDecimal aeaSeguimientoMicro1er) {
        this.aeaSeguimientoMicro1er = aeaSeguimientoMicro1er;
    }

    
    @Column(name="AEA_PORC_OBT_MICRO_1ER", precision=22, scale=0)
    public BigDecimal getAeaPorcObtMicro1er() {
        return this.aeaPorcObtMicro1er;
    }
    
    public void setAeaPorcObtMicro1er(BigDecimal aeaPorcObtMicro1er) {
        this.aeaPorcObtMicro1er = aeaPorcObtMicro1er;
    }

    
    @Column(name="AEA_SEMAFORO_MICRO_1ER", length=15)
    public String getAeaSemaforoMicro1er() {
        return this.aeaSemaforoMicro1er;
    }
    
    public void setAeaSemaforoMicro1er(String aeaSemaforoMicro1er) {
        this.aeaSemaforoMicro1er = aeaSemaforoMicro1er;
    }

    
    @Column(name="AEA_OBJ_MICRO_2DO", precision=22, scale=0)
    public BigDecimal getAeaObjMicro2do() {
        return this.aeaObjMicro2do;
    }
    
    public void setAeaObjMicro2do(BigDecimal aeaObjMicro2do) {
        this.aeaObjMicro2do = aeaObjMicro2do;
    }

    
    @Column(name="AEA_TOTAL_MICRO_2DO", precision=22, scale=0)
    public BigDecimal getAeaTotalMicro2do() {
        return this.aeaTotalMicro2do;
    }
    
    public void setAeaTotalMicro2do(BigDecimal aeaTotalMicro2do) {
        this.aeaTotalMicro2do = aeaTotalMicro2do;
    }

    
    @Column(name="AEA_CUMPLIMIENTO_MICRO_2DO", precision=22, scale=0)
    public BigDecimal getAeaCumplimientoMicro2do() {
        return this.aeaCumplimientoMicro2do;
    }
    
    public void setAeaCumplimientoMicro2do(BigDecimal aeaCumplimientoMicro2do) {
        this.aeaCumplimientoMicro2do = aeaCumplimientoMicro2do;
    }

    
    @Column(name="AEA_SEGUIMIENTO_MICRO_2DO", precision=22, scale=0)
    public BigDecimal getAeaSeguimientoMicro2do() {
        return this.aeaSeguimientoMicro2do;
    }
    
    public void setAeaSeguimientoMicro2do(BigDecimal aeaSeguimientoMicro2do) {
        this.aeaSeguimientoMicro2do = aeaSeguimientoMicro2do;
    }

    
    @Column(name="AEA_PORC_OBT_MICRO_2DO", precision=22, scale=0)
    public BigDecimal getAeaPorcObtMicro2do() {
        return this.aeaPorcObtMicro2do;
    }
    
    public void setAeaPorcObtMicro2do(BigDecimal aeaPorcObtMicro2do) {
        this.aeaPorcObtMicro2do = aeaPorcObtMicro2do;
    }

    
    @Column(name="AEA_SEMAFORO_MICRO_2DO", length=15)
    public String getAeaSemaforoMicro2do() {
        return this.aeaSemaforoMicro2do;
    }
    
    public void setAeaSemaforoMicro2do(String aeaSemaforoMicro2do) {
        this.aeaSemaforoMicro2do = aeaSemaforoMicro2do;
    }

    
    @Column(name="AEA_OBJ_CHAT_ACAD", precision=22, scale=0)
    public BigDecimal getAeaObjChatAcad() {
        return this.aeaObjChatAcad;
    }
    
    public void setAeaObjChatAcad(BigDecimal aeaObjChatAcad) {
        this.aeaObjChatAcad = aeaObjChatAcad;
    }

    
    @Column(name="AEA_TOTAL_CHAT_ACAD", precision=22, scale=0)
    public BigDecimal getAeaTotalChatAcad() {
        return this.aeaTotalChatAcad;
    }
    
    public void setAeaTotalChatAcad(BigDecimal aeaTotalChatAcad) {
        this.aeaTotalChatAcad = aeaTotalChatAcad;
    }

    
    @Column(name="AEA_CUMPLIMIENTO_CHAT_ACAD", precision=22, scale=0)
    public BigDecimal getAeaCumplimientoChatAcad() {
        return this.aeaCumplimientoChatAcad;
    }
    
    public void setAeaCumplimientoChatAcad(BigDecimal aeaCumplimientoChatAcad) {
        this.aeaCumplimientoChatAcad = aeaCumplimientoChatAcad;
    }

    
    @Column(name="AEA_SEGUIMIENTO_CHAT_ACAD", precision=22, scale=0)
    public BigDecimal getAeaSeguimientoChatAcad() {
        return this.aeaSeguimientoChatAcad;
    }
    
    public void setAeaSeguimientoChatAcad(BigDecimal aeaSeguimientoChatAcad) {
        this.aeaSeguimientoChatAcad = aeaSeguimientoChatAcad;
    }

    
    @Column(name="AEA_PORC_OBT_CHAT_ACAD", precision=22, scale=0)
    public BigDecimal getAeaPorcObtChatAcad() {
        return this.aeaPorcObtChatAcad;
    }
    
    public void setAeaPorcObtChatAcad(BigDecimal aeaPorcObtChatAcad) {
        this.aeaPorcObtChatAcad = aeaPorcObtChatAcad;
    }

    
    @Column(name="AEA_SEMAFORO_CHAT_ACAD", length=15)
    public String getAeaSemaforoChatAcad() {
        return this.aeaSemaforoChatAcad;
    }
    
    public void setAeaSemaforoChatAcad(String aeaSemaforoChatAcad) {
        this.aeaSemaforoChatAcad = aeaSemaforoChatAcad;
    }

    
    @Column(name="AEA_OBJ_CHAT_TUT", precision=22, scale=0)
    public BigDecimal getAeaObjChatTut() {
        return this.aeaObjChatTut;
    }
    
    public void setAeaObjChatTut(BigDecimal aeaObjChatTut) {
        this.aeaObjChatTut = aeaObjChatTut;
    }

    
    @Column(name="AEA_TOTAL_CHAT_TUT", precision=22, scale=0)
    public BigDecimal getAeaTotalChatTut() {
        return this.aeaTotalChatTut;
    }
    
    public void setAeaTotalChatTut(BigDecimal aeaTotalChatTut) {
        this.aeaTotalChatTut = aeaTotalChatTut;
    }

    
    @Column(name="AEA_CUMPLIMIENTO_CHAT_TUT", precision=22, scale=0)
    public BigDecimal getAeaCumplimientoChatTut() {
        return this.aeaCumplimientoChatTut;
    }
    
    public void setAeaCumplimientoChatTut(BigDecimal aeaCumplimientoChatTut) {
        this.aeaCumplimientoChatTut = aeaCumplimientoChatTut;
    }

    
    @Column(name="AEA_SEGUIMIENTO_CHAT_TUT", precision=22, scale=0)
    public BigDecimal getAeaSeguimientoChatTut() {
        return this.aeaSeguimientoChatTut;
    }
    
    public void setAeaSeguimientoChatTut(BigDecimal aeaSeguimientoChatTut) {
        this.aeaSeguimientoChatTut = aeaSeguimientoChatTut;
    }

    
    @Column(name="AEA_PORC_OBT_CHAT_TUT", precision=22, scale=0)
    public BigDecimal getAeaPorcObtChatTut() {
        return this.aeaPorcObtChatTut;
    }
    
    public void setAeaPorcObtChatTut(BigDecimal aeaPorcObtChatTut) {
        this.aeaPorcObtChatTut = aeaPorcObtChatTut;
    }

    
    @Column(name="AEA_SEMAFORO_CHAT_TUT", length=15)
    public String getAeaSemaforoChatTut() {
        return this.aeaSemaforoChatTut;
    }
    
    public void setAeaSemaforoChatTut(String aeaSemaforoChatTut) {
        this.aeaSemaforoChatTut = aeaSemaforoChatTut;
    }

    
    @Column(name="AEA_OBJ_CUESTI", precision=22, scale=0)
    public BigDecimal getAeaObjCuesti() {
        return this.aeaObjCuesti;
    }
    
    public void setAeaObjCuesti(BigDecimal aeaObjCuesti) {
        this.aeaObjCuesti = aeaObjCuesti;
    }

    
    @Column(name="AEA_TOTAL_CUESTI", precision=22, scale=0)
    public BigDecimal getAeaTotalCuesti() {
        return this.aeaTotalCuesti;
    }
    
    public void setAeaTotalCuesti(BigDecimal aeaTotalCuesti) {
        this.aeaTotalCuesti = aeaTotalCuesti;
    }

    
    @Column(name="AEA_CUMPLIMIENTO_CUESTI", precision=22, scale=0)
    public BigDecimal getAeaCumplimientoCuesti() {
        return this.aeaCumplimientoCuesti;
    }
    
    public void setAeaCumplimientoCuesti(BigDecimal aeaCumplimientoCuesti) {
        this.aeaCumplimientoCuesti = aeaCumplimientoCuesti;
    }

    
    @Column(name="AEA_SEGUIMIENTO_CUESTI", precision=22, scale=0)
    public BigDecimal getAeaSeguimientoCuesti() {
        return this.aeaSeguimientoCuesti;
    }
    
    public void setAeaSeguimientoCuesti(BigDecimal aeaSeguimientoCuesti) {
        this.aeaSeguimientoCuesti = aeaSeguimientoCuesti;
    }

    
    @Column(name="AEA_PORC_OBT_CUESTI", precision=22, scale=0)
    public BigDecimal getAeaPorcObtCuesti() {
        return this.aeaPorcObtCuesti;
    }
    
    public void setAeaPorcObtCuesti(BigDecimal aeaPorcObtCuesti) {
        this.aeaPorcObtCuesti = aeaPorcObtCuesti;
    }

    
    @Column(name="AEA_SEMAFORO_CUESTI", length=15)
    public String getAeaSemaforoCuesti() {
        return this.aeaSemaforoCuesti;
    }
    
    public void setAeaSemaforoCuesti(String aeaSemaforoCuesti) {
        this.aeaSemaforoCuesti = aeaSemaforoCuesti;
    }

    
    @Column(name="AEA_OBJ_FORO", precision=22, scale=0)
    public BigDecimal getAeaObjForo() {
        return this.aeaObjForo;
    }
    
    public void setAeaObjForo(BigDecimal aeaObjForo) {
        this.aeaObjForo = aeaObjForo;
    }

    
    @Column(name="AEA_TOTAL_FORO", precision=22, scale=0)
    public BigDecimal getAeaTotalForo() {
        return this.aeaTotalForo;
    }
    
    public void setAeaTotalForo(BigDecimal aeaTotalForo) {
        this.aeaTotalForo = aeaTotalForo;
    }

    
    @Column(name="AEA_CUMPLIMIENTO_FORO", precision=22, scale=0)
    public BigDecimal getAeaCumplimientoForo() {
        return this.aeaCumplimientoForo;
    }
    
    public void setAeaCumplimientoForo(BigDecimal aeaCumplimientoForo) {
        this.aeaCumplimientoForo = aeaCumplimientoForo;
    }

    
    @Column(name="AEA_SEGUIMIENTO_FORO", precision=22, scale=0)
    public BigDecimal getAeaSeguimientoForo() {
        return this.aeaSeguimientoForo;
    }
    
    public void setAeaSeguimientoForo(BigDecimal aeaSeguimientoForo) {
        this.aeaSeguimientoForo = aeaSeguimientoForo;
    }

    
    @Column(name="AEA_PORC_OBT_FORO", precision=22, scale=0)
    public BigDecimal getAeaPorcObtForo() {
        return this.aeaPorcObtForo;
    }
    
    public void setAeaPorcObtForo(BigDecimal aeaPorcObtForo) {
        this.aeaPorcObtForo = aeaPorcObtForo;
    }

    
    @Column(name="AEA_SEMAFORO_FORO", length=15)
    public String getAeaSemaforoForo() {
        return this.aeaSemaforoForo;
    }
    
    public void setAeaSemaforoForo(String aeaSemaforoForo) {
        this.aeaSemaforoForo = aeaSemaforoForo;
    }

    
    @Column(name="AEA_OBJ_ANUNCIO", precision=22, scale=0)
    public BigDecimal getAeaObjAnuncio() {
        return this.aeaObjAnuncio;
    }
    
    public void setAeaObjAnuncio(BigDecimal aeaObjAnuncio) {
        this.aeaObjAnuncio = aeaObjAnuncio;
    }

    
    @Column(name="AEA_TOTAL_ANUNCIO", precision=22, scale=0)
    public BigDecimal getAeaTotalAnuncio() {
        return this.aeaTotalAnuncio;
    }
    
    public void setAeaTotalAnuncio(BigDecimal aeaTotalAnuncio) {
        this.aeaTotalAnuncio = aeaTotalAnuncio;
    }

    
    @Column(name="AEA_CUMPLIMIENTO_ANUNCIO", precision=22, scale=0)
    public BigDecimal getAeaCumplimientoAnuncio() {
        return this.aeaCumplimientoAnuncio;
    }
    
    public void setAeaCumplimientoAnuncio(BigDecimal aeaCumplimientoAnuncio) {
        this.aeaCumplimientoAnuncio = aeaCumplimientoAnuncio;
    }

    
    @Column(name="AEA_SEGUIMIENTO_ANUNCIO", precision=22, scale=0)
    public BigDecimal getAeaSeguimientoAnuncio() {
        return this.aeaSeguimientoAnuncio;
    }
    
    public void setAeaSeguimientoAnuncio(BigDecimal aeaSeguimientoAnuncio) {
        this.aeaSeguimientoAnuncio = aeaSeguimientoAnuncio;
    }

    
    @Column(name="AEA_PORC_OBT_ANUNCIO", precision=22, scale=0)
    public BigDecimal getAeaPorcObtAnuncio() {
        return this.aeaPorcObtAnuncio;
    }
    
    public void setAeaPorcObtAnuncio(BigDecimal aeaPorcObtAnuncio) {
        this.aeaPorcObtAnuncio = aeaPorcObtAnuncio;
    }

    
    @Column(name="AEA_SEMAFORO_ANUNCIO", length=15)
    public String getAeaSemaforoAnuncio() {
        return this.aeaSemaforoAnuncio;
    }
    
    public void setAeaSemaforoAnuncio(String aeaSemaforoAnuncio) {
        this.aeaSemaforoAnuncio = aeaSemaforoAnuncio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AEA_FECHA_CREACION_SIEC", length=7)
    public Date getAeaFechaCreacionSiec() {
        return this.aeaFechaCreacionSiec;
    }
    
    public void setAeaFechaCreacionSiec(Date aeaFechaCreacionSiec) {
        this.aeaFechaCreacionSiec = aeaFechaCreacionSiec;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AEA_FECHA_ULT_ACT_SIEC", length=7)
    public Date getAeaFechaUltActSiec() {
        return this.aeaFechaUltActSiec;
    }
    
    public void setAeaFechaUltActSiec(Date aeaFechaUltActSiec) {
        this.aeaFechaUltActSiec = aeaFechaUltActSiec;
    }

    
    @Column(name="AEA_PROCESO", length=30)
    public String getAeaProceso() {
        return this.aeaProceso;
    }
    
    public void setAeaProceso(String aeaProceso) {
        this.aeaProceso = aeaProceso;
    }

    
    @Column(name="AEA_TOT_MATRICULADOS", precision=22, scale=0)
    public BigDecimal getAeaTotMatriculados() {
        return this.aeaTotMatriculados;
    }
    
    public void setAeaTotMatriculados(BigDecimal aeaTotMatriculados) {
        this.aeaTotMatriculados = aeaTotMatriculados;
    }

    
    @Column(name="AEA_CURSO_ID_EVA", precision=22, scale=0)
    public BigDecimal getAeaCursoIdEva() {
        return this.aeaCursoIdEva;
    }
    
    public void setAeaCursoIdEva(BigDecimal aeaCursoIdEva) {
        this.aeaCursoIdEva = aeaCursoIdEva;
    }




}


