package ec.edu.utpl.svied.model;
// Generated 01/09/2017 12:34:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TheActividadesDocEvaCab generated by hbm2java
 */
@Entity
@Table(name="THE_ACTIVIDADES_DOC_EVA_CAB"
    ,schema="ESQ_SIEC"
)
public class TheActividadesDocEvaCab  implements java.io.Serializable {


     private BigDecimal aecId;
     private TdiComponenteEducativo tdiComponenteEducativo;
     private TdiOfertaNsga tdiOfertaNsga;
     private TdiArea tdiArea;
     private TdiDepartamento tdiDepartamento;
     private TdiDocente tdiDocente;
     private TdiIndicador tdiIndicador;
     private TdiModalidad tdiModalidad;
     private TdiNivelAcademico tdiNivelAcademico;
     private TdiPeriodo tdiPeriodo;
     private TdiSeccionDepartamental tdiSeccionDepartamental;
     private TdiGlosario tdiGlosario;
     private TdiParametrosIndicador tdiParametrosIndicador;
     private TdiPeriodoDetalle tdiPeriodoDetalle;
     private TdiExcepciones tdiExcepciones;
     private BigDecimal aecTotal;
     private BigDecimal aecCumplimiento;
     private BigDecimal aecSeguimiento;
     private BigDecimal aecObjetivo;
     private Date aecFechaCreacionSiec;
     private String aecUsuarioCreaSiec;
     private Date aecFechaActualizacionSiec;
     private String aecUsuarioActualizacionSiec;
     private BigDecimal aecSobrantes;
     private String aecColoresSemaforo;
     private BigDecimal aecCantidadDocentes;
     private BigDecimal aecIdCursoEva;
     private String aecVigente;
     private BigDecimal aecPorcentajeObtenido;
     private BigDecimal aecNoCumplimiento;
     private Date aecFechaEnrolamiento;
     private Date aecFechaMaximaEnrolamiento;
     private String aecEnrolamientoTardio;
     private String aecObservacion;
     private BigDecimal aecJustificacionId;
     private Set<TheActividadesDocEvaDet> theActividadesDocEvaDets = new HashSet<TheActividadesDocEvaDet>(0);

    public TheActividadesDocEvaCab() {
    }

	
    public TheActividadesDocEvaCab(BigDecimal aecId, TdiComponenteEducativo tdiComponenteEducativo, TdiOfertaNsga tdiOfertaNsga, TdiArea tdiArea, TdiDepartamento tdiDepartamento, TdiDocente tdiDocente, TdiIndicador tdiIndicador, TdiModalidad tdiModalidad, TdiNivelAcademico tdiNivelAcademico, TdiPeriodo tdiPeriodo, TdiSeccionDepartamental tdiSeccionDepartamental, TdiGlosario tdiGlosario, TdiParametrosIndicador tdiParametrosIndicador, Date aecFechaCreacionSiec, String aecUsuarioCreaSiec, String aecColoresSemaforo, String aecVigente, BigDecimal aecJustificacionId) {
        this.aecId = aecId;
        this.tdiComponenteEducativo = tdiComponenteEducativo;
        this.tdiOfertaNsga = tdiOfertaNsga;
        this.tdiArea = tdiArea;
        this.tdiDepartamento = tdiDepartamento;
        this.tdiDocente = tdiDocente;
        this.tdiIndicador = tdiIndicador;
        this.tdiModalidad = tdiModalidad;
        this.tdiNivelAcademico = tdiNivelAcademico;
        this.tdiPeriodo = tdiPeriodo;
        this.tdiSeccionDepartamental = tdiSeccionDepartamental;
        this.tdiGlosario = tdiGlosario;
        this.tdiParametrosIndicador = tdiParametrosIndicador;
        this.aecFechaCreacionSiec = aecFechaCreacionSiec;
        this.aecUsuarioCreaSiec = aecUsuarioCreaSiec;
        this.aecColoresSemaforo = aecColoresSemaforo;
        this.aecVigente = aecVigente;
        this.aecJustificacionId = aecJustificacionId;
    }
    public TheActividadesDocEvaCab(BigDecimal aecId, TdiComponenteEducativo tdiComponenteEducativo, TdiOfertaNsga tdiOfertaNsga, TdiArea tdiArea, TdiDepartamento tdiDepartamento, TdiDocente tdiDocente, TdiIndicador tdiIndicador, TdiModalidad tdiModalidad, TdiNivelAcademico tdiNivelAcademico, TdiPeriodo tdiPeriodo, TdiSeccionDepartamental tdiSeccionDepartamental, TdiGlosario tdiGlosario, TdiParametrosIndicador tdiParametrosIndicador, TdiPeriodoDetalle tdiPeriodoDetalle, TdiExcepciones tdiExcepciones, BigDecimal aecTotal, BigDecimal aecCumplimiento, BigDecimal aecSeguimiento, BigDecimal aecObjetivo, Date aecFechaCreacionSiec, String aecUsuarioCreaSiec, Date aecFechaActualizacionSiec, String aecUsuarioActualizacionSiec, BigDecimal aecSobrantes, String aecColoresSemaforo, BigDecimal aecCantidadDocentes, BigDecimal aecIdCursoEva, String aecVigente, BigDecimal aecPorcentajeObtenido, BigDecimal aecNoCumplimiento, Date aecFechaEnrolamiento, Date aecFechaMaximaEnrolamiento, String aecEnrolamientoTardio, String aecObservacion, BigDecimal aecJustificacionId, Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
       this.aecId = aecId;
       this.tdiComponenteEducativo = tdiComponenteEducativo;
       this.tdiOfertaNsga = tdiOfertaNsga;
       this.tdiArea = tdiArea;
       this.tdiDepartamento = tdiDepartamento;
       this.tdiDocente = tdiDocente;
       this.tdiIndicador = tdiIndicador;
       this.tdiModalidad = tdiModalidad;
       this.tdiNivelAcademico = tdiNivelAcademico;
       this.tdiPeriodo = tdiPeriodo;
       this.tdiSeccionDepartamental = tdiSeccionDepartamental;
       this.tdiGlosario = tdiGlosario;
       this.tdiParametrosIndicador = tdiParametrosIndicador;
       this.tdiPeriodoDetalle = tdiPeriodoDetalle;
       this.tdiExcepciones = tdiExcepciones;
       this.aecTotal = aecTotal;
       this.aecCumplimiento = aecCumplimiento;
       this.aecSeguimiento = aecSeguimiento;
       this.aecObjetivo = aecObjetivo;
       this.aecFechaCreacionSiec = aecFechaCreacionSiec;
       this.aecUsuarioCreaSiec = aecUsuarioCreaSiec;
       this.aecFechaActualizacionSiec = aecFechaActualizacionSiec;
       this.aecUsuarioActualizacionSiec = aecUsuarioActualizacionSiec;
       this.aecSobrantes = aecSobrantes;
       this.aecColoresSemaforo = aecColoresSemaforo;
       this.aecCantidadDocentes = aecCantidadDocentes;
       this.aecIdCursoEva = aecIdCursoEva;
       this.aecVigente = aecVigente;
       this.aecPorcentajeObtenido = aecPorcentajeObtenido;
       this.aecNoCumplimiento = aecNoCumplimiento;
       this.aecFechaEnrolamiento = aecFechaEnrolamiento;
       this.aecFechaMaximaEnrolamiento = aecFechaMaximaEnrolamiento;
       this.aecEnrolamientoTardio = aecEnrolamientoTardio;
       this.aecObservacion = aecObservacion;
       this.aecJustificacionId = aecJustificacionId;
       this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }
   
     @Id 

    
    @Column(name="AEC_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getAecId() {
        return this.aecId;
    }
    
    public void setAecId(BigDecimal aecId) {
        this.aecId = aecId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CE_ID", nullable=false)
    public TdiComponenteEducativo getTdiComponenteEducativo() {
        return this.tdiComponenteEducativo;
    }
    
    public void setTdiComponenteEducativo(TdiComponenteEducativo tdiComponenteEducativo) {
        this.tdiComponenteEducativo = tdiComponenteEducativo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ONS_ID", nullable=false)
    public TdiOfertaNsga getTdiOfertaNsga() {
        return this.tdiOfertaNsga;
    }
    
    public void setTdiOfertaNsga(TdiOfertaNsga tdiOfertaNsga) {
        this.tdiOfertaNsga = tdiOfertaNsga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AR_ID_CE", nullable=false)
    public TdiArea getTdiArea() {
        return this.tdiArea;
    }
    
    public void setTdiArea(TdiArea tdiArea) {
        this.tdiArea = tdiArea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DE_ID_CE", nullable=false)
    public TdiDepartamento getTdiDepartamento() {
        return this.tdiDepartamento;
    }
    
    public void setTdiDepartamento(TdiDepartamento tdiDepartamento) {
        this.tdiDepartamento = tdiDepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DO_ID", nullable=false)
    public TdiDocente getTdiDocente() {
        return this.tdiDocente;
    }
    
    public void setTdiDocente(TdiDocente tdiDocente) {
        this.tdiDocente = tdiDocente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ID", nullable=false)
    public TdiIndicador getTdiIndicador() {
        return this.tdiIndicador;
    }
    
    public void setTdiIndicador(TdiIndicador tdiIndicador) {
        this.tdiIndicador = tdiIndicador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MO_ID", nullable=false)
    public TdiModalidad getTdiModalidad() {
        return this.tdiModalidad;
    }
    
    public void setTdiModalidad(TdiModalidad tdiModalidad) {
        this.tdiModalidad = tdiModalidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NA_ID", nullable=false)
    public TdiNivelAcademico getTdiNivelAcademico() {
        return this.tdiNivelAcademico;
    }
    
    public void setTdiNivelAcademico(TdiNivelAcademico tdiNivelAcademico) {
        this.tdiNivelAcademico = tdiNivelAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PE_ID", nullable=false)
    public TdiPeriodo getTdiPeriodo() {
        return this.tdiPeriodo;
    }
    
    public void setTdiPeriodo(TdiPeriodo tdiPeriodo) {
        this.tdiPeriodo = tdiPeriodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SE_ID_CE", nullable=false)
    public TdiSeccionDepartamental getTdiSeccionDepartamental() {
        return this.tdiSeccionDepartamental;
    }
    
    public void setTdiSeccionDepartamental(TdiSeccionDepartamental tdiSeccionDepartamental) {
        this.tdiSeccionDepartamental = tdiSeccionDepartamental;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AEC_PARALELO_ID", nullable=false)
    public TdiGlosario getTdiGlosario() {
        return this.tdiGlosario;
    }
    
    public void setTdiGlosario(TdiGlosario tdiGlosario) {
        this.tdiGlosario = tdiGlosario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PI_ID", nullable=false)
    public TdiParametrosIndicador getTdiParametrosIndicador() {
        return this.tdiParametrosIndicador;
    }
    
    public void setTdiParametrosIndicador(TdiParametrosIndicador tdiParametrosIndicador) {
        this.tdiParametrosIndicador = tdiParametrosIndicador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PT_ID_ENROLAMIENTO")
    public TdiPeriodoDetalle getTdiPeriodoDetalle() {
        return this.tdiPeriodoDetalle;
    }
    
    public void setTdiPeriodoDetalle(TdiPeriodoDetalle tdiPeriodoDetalle) {
        this.tdiPeriodoDetalle = tdiPeriodoDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AEC_EXCEPCION")
    public TdiExcepciones getTdiExcepciones() {
        return this.tdiExcepciones;
    }
    
    public void setTdiExcepciones(TdiExcepciones tdiExcepciones) {
        this.tdiExcepciones = tdiExcepciones;
    }

    
    @Column(name="AEC_TOTAL", precision=22, scale=0)
    public BigDecimal getAecTotal() {
        return this.aecTotal;
    }
    
    public void setAecTotal(BigDecimal aecTotal) {
        this.aecTotal = aecTotal;
    }

    
    @Column(name="AEC_CUMPLIMIENTO", precision=22, scale=0)
    public BigDecimal getAecCumplimiento() {
        return this.aecCumplimiento;
    }
    
    public void setAecCumplimiento(BigDecimal aecCumplimiento) {
        this.aecCumplimiento = aecCumplimiento;
    }

    
    @Column(name="AEC_SEGUIMIENTO", precision=22, scale=0)
    public BigDecimal getAecSeguimiento() {
        return this.aecSeguimiento;
    }
    
    public void setAecSeguimiento(BigDecimal aecSeguimiento) {
        this.aecSeguimiento = aecSeguimiento;
    }

    
    @Column(name="AEC_OBJETIVO", precision=22, scale=0)
    public BigDecimal getAecObjetivo() {
        return this.aecObjetivo;
    }
    
    public void setAecObjetivo(BigDecimal aecObjetivo) {
        this.aecObjetivo = aecObjetivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AEC_FECHA_CREACION_SIEC", nullable=false, length=7)
    public Date getAecFechaCreacionSiec() {
        return this.aecFechaCreacionSiec;
    }
    
    public void setAecFechaCreacionSiec(Date aecFechaCreacionSiec) {
        this.aecFechaCreacionSiec = aecFechaCreacionSiec;
    }

    
    @Column(name="AEC_USUARIO_CREA_SIEC", nullable=false, length=100)
    public String getAecUsuarioCreaSiec() {
        return this.aecUsuarioCreaSiec;
    }
    
    public void setAecUsuarioCreaSiec(String aecUsuarioCreaSiec) {
        this.aecUsuarioCreaSiec = aecUsuarioCreaSiec;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AEC_FECHA_ACTUALIZACION_SIEC", length=7)
    public Date getAecFechaActualizacionSiec() {
        return this.aecFechaActualizacionSiec;
    }
    
    public void setAecFechaActualizacionSiec(Date aecFechaActualizacionSiec) {
        this.aecFechaActualizacionSiec = aecFechaActualizacionSiec;
    }

    
    @Column(name="AEC_USUARIO_ACTUALIZACION_SIEC", length=100)
    public String getAecUsuarioActualizacionSiec() {
        return this.aecUsuarioActualizacionSiec;
    }
    
    public void setAecUsuarioActualizacionSiec(String aecUsuarioActualizacionSiec) {
        this.aecUsuarioActualizacionSiec = aecUsuarioActualizacionSiec;
    }

    
    @Column(name="AEC_SOBRANTES", precision=22, scale=0)
    public BigDecimal getAecSobrantes() {
        return this.aecSobrantes;
    }
    
    public void setAecSobrantes(BigDecimal aecSobrantes) {
        this.aecSobrantes = aecSobrantes;
    }

    
    @Column(name="AEC_COLORES_SEMAFORO", nullable=false, length=10)
    public String getAecColoresSemaforo() {
        return this.aecColoresSemaforo;
    }
    
    public void setAecColoresSemaforo(String aecColoresSemaforo) {
        this.aecColoresSemaforo = aecColoresSemaforo;
    }

    
    @Column(name="AEC_CANTIDAD_DOCENTES", precision=22, scale=0)
    public BigDecimal getAecCantidadDocentes() {
        return this.aecCantidadDocentes;
    }
    
    public void setAecCantidadDocentes(BigDecimal aecCantidadDocentes) {
        this.aecCantidadDocentes = aecCantidadDocentes;
    }

    
    @Column(name="AEC_ID_CURSO_EVA", precision=22, scale=0)
    public BigDecimal getAecIdCursoEva() {
        return this.aecIdCursoEva;
    }
    
    public void setAecIdCursoEva(BigDecimal aecIdCursoEva) {
        this.aecIdCursoEva = aecIdCursoEva;
    }

    
    @Column(name="AEC_VIGENTE", nullable=false, length=1)
    public String getAecVigente() {
        return this.aecVigente;
    }
    
    public void setAecVigente(String aecVigente) {
        this.aecVigente = aecVigente;
    }

    
    @Column(name="AEC_PORCENTAJE_OBTENIDO", precision=22, scale=0)
    public BigDecimal getAecPorcentajeObtenido() {
        return this.aecPorcentajeObtenido;
    }
    
    public void setAecPorcentajeObtenido(BigDecimal aecPorcentajeObtenido) {
        this.aecPorcentajeObtenido = aecPorcentajeObtenido;
    }

    
    @Column(name="AEC_NO_CUMPLIMIENTO", precision=22, scale=0)
    public BigDecimal getAecNoCumplimiento() {
        return this.aecNoCumplimiento;
    }
    
    public void setAecNoCumplimiento(BigDecimal aecNoCumplimiento) {
        this.aecNoCumplimiento = aecNoCumplimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AEC_FECHA_ENROLAMIENTO", length=7)
    public Date getAecFechaEnrolamiento() {
        return this.aecFechaEnrolamiento;
    }
    
    public void setAecFechaEnrolamiento(Date aecFechaEnrolamiento) {
        this.aecFechaEnrolamiento = aecFechaEnrolamiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="AEC_FECHA_MAXIMA_ENROLAMIENTO", length=7)
    public Date getAecFechaMaximaEnrolamiento() {
        return this.aecFechaMaximaEnrolamiento;
    }
    
    public void setAecFechaMaximaEnrolamiento(Date aecFechaMaximaEnrolamiento) {
        this.aecFechaMaximaEnrolamiento = aecFechaMaximaEnrolamiento;
    }

    
    @Column(name="AEC_ENROLAMIENTO_TARDIO", length=1)
    public String getAecEnrolamientoTardio() {
        return this.aecEnrolamientoTardio;
    }
    
    public void setAecEnrolamientoTardio(String aecEnrolamientoTardio) {
        this.aecEnrolamientoTardio = aecEnrolamientoTardio;
    }

    
    @Column(name="AEC_OBSERVACION", length=200)
    public String getAecObservacion() {
        return this.aecObservacion;
    }
    
    public void setAecObservacion(String aecObservacion) {
        this.aecObservacion = aecObservacion;
    }

    
    @Column(name="AEC_JUSTIFICACION_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getAecJustificacionId() {
        return this.aecJustificacionId;
    }
    
    public void setAecJustificacionId(BigDecimal aecJustificacionId) {
        this.aecJustificacionId = aecJustificacionId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="theActividadesDocEvaCab")
    public Set<TheActividadesDocEvaDet> getTheActividadesDocEvaDets() {
        return this.theActividadesDocEvaDets;
    }
    
    public void setTheActividadesDocEvaDets(Set<TheActividadesDocEvaDet> theActividadesDocEvaDets) {
        this.theActividadesDocEvaDets = theActividadesDocEvaDets;
    }




}


